//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.NAATI._20221212_AddPracticeTestSkillApplicationTypes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.NAATI._20221212_AddPracticeTestSkillApplicati" +
                            "onTypes.sql", typeof(sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION
        ///insert into tblskill (skilltypeid, Language1Id,Language2Id,DirectionTypeId,ModifiedByNaati,ModifiedDate,ModifiedUser) values
        ///(38, 3,3, 4,0,getdate(),40),
        ///(38, 7,7, 4,0,getdate(),40),
        ///(38, 9,9, 4,0,getdate(),40),
        ///(38, 13,13, 4,0,getdate(),40),
        ///(38, 16,16, 4,0,getdate(),40),
        ///(38, 17,17, 4,0,getdate(),40),
        ///(38, 18,18, 4,0,getdate(),40),
        ///(38, 20,20, 4,0,getdate(),40),
        ///(38, 27,27, 4,0,getdate(),40),
        ///(38, 28,28, 4,0,getdate(),40),
        ///(38, 30,30, 4,0,getdate(),40),
        ///(38, 36,36, 4,0,getda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddPracticeTestSkillApplicationTypes {
            get {
                return ResourceManager.GetString("AddPracticeTestSkillApplicationTypes", resourceCulture);
            }
        }
    }
}
