//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.NAATIScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.NAATIScripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[AddressSelect]
        ///(
        ///	@EntityId int
        ///)
        ///AS 
        ///declare @true bit = 1
        ///declare @false bit = 0
        ///
        ///SELECT	a.AddressId,
        ///		a.EntityId,
        ///		a.StreetDetails,
        ///		s.Suburb + &apos;, &apos; + pc.Postcode + &apos;, &apos; + st.State AS Suburb,
        ///		s.Suburb as SuburbName,
        ///		st.State as StateAbbreviation,
        ///		pc.Postcode,
        ///		c.Name AS CountryName,
        ///		a.PostcodeId,
        ///		a.CountryId,
        ///		a.Note,
        ///		a.StartDate,
        ///		a.EndDate, 
        ///		a.PrimaryContact,
        ///		a.ODAddressVisibilityTypeId,
        ///		odadtype.DisplayName,
        ///		a.SubscriptionExpiryD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddressSelect {
            get {
                return ResourceManager.GetString("AddressSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE CheckNewCredentialSiblingsCanProgressToEligibleForTesting
        ///@credentialApplicationId as int,
        ///@credentialRequestId as int
        ///AS
        ///--DECLARE @credentialApplicationId as int
        ///--DECLARE @credentialRequestId as int
        ///--select 		@credentialApplicationId = 670346,
        ///--		@credentialRequestId = 533495
        ///
        ///IF OBJECT_ID(N&apos;tempdb..#tmpCredentialTypes&apos;) IS NOT NULL
        ///BEGIN
        ///DROP TABLE #tmpCredentialTypes
        ///END
        ///
        ///IF OBJECT_ID(N&apos;tempdb..#tmpFoundCredentialTypes&apos;) IS NOT NULL
        ///BEGIN
        ///DROP TABLE #tmpFoundCredential [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckNewCredentialSiblingsCanProgressToEligibleForTesting {
            get {
                return ResourceManager.GetString("CheckNewCredentialSiblingsCanProgressToEligibleForTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[DeletedApplications]
        ///@Days int
        ///AS
        ///
        ///Declare @DeletedTypeId int, @DraftTypeId int
        ///	
        ///	BEGIN TRANSACTION
        ///	
        ///		IF OBJECT_ID(&apos;tempdb..#TempCredentialApplicationId&apos;) IS NOT NULL DROP TABLE #TempCredentialApplicationId
        ///		IF OBJECT_ID(&apos;tempdb..#TempEmailMessageId&apos;) IS NOT NULL DROP TABLE #TempEmailMessageId
        ///
        ///		set @DeletedTypeId = (select CredentialApplicationStatusTypeId from tblCredentialApplicationStatusType where [Name] = &apos;Deleted&apos;)
        ///		set @DraftTypeId = (select CredentialApplica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeletedApplications {
            get {
                return ResourceManager.GetString("DeletedApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[EmailSelect]
        ///(
        ///	@EntityId int
        ///)
        ///AS 
        ///
        ///SELECT		e.EmailId, e.EntityId, e.Email, e.Note, e.IncludeInPD, e.Invalid, e.IsPreferredEmail, e.ExaminerCorrespondence
        ///FROM		tblEmail e
        ///WHERE		e.EntityId = @EntityId and (e.IsPreferredEmail = 1 or e.Invalid = 0).
        /// </summary>
        internal static string EmailSelect {
            get {
                return ResourceManager.GetString("EmailSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FUNCTION [dbo].fnGetNextNAATINumber (@NAATINumberType INT) 
        ///RETURNS INT 
        ///AS 
        ///  BEGIN 
        ///      DECLARE @NewNAATINumber INT 
        ///
        ///      IF ( @NAATINumberType = 3 ) 
        ///        SET @NewNAATINumber = (SELECT Max(NAATINumber) + 1 
        ///                               FROM   tblEntity 
        ///                               WHERE  NAATINumber &gt;= 910000) 
        ///      ELSE 
        ///        SET @NewNAATINumber = (SELECT Max(NAATINumber) + 1 
        ///                               FROM   tblEntity 
        ///                               WHERE  NAATI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fnGetNextNaatiNumber {
            get {
                return ResourceManager.GetString("fnGetNextNaatiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT 1 FROM sys.fulltext_catalogs WHERE [name] = &apos;FT_Audit&apos;)
        ///	CREATE FULLTEXT CATALOG FT_Audit;
        ///
        ///IF NOT EXISTS (SELECT 1 FROM sys.fulltext_indexes where object_id = object_id(&apos;tblAuditLog&apos;))
        ///	CREATE FULLTEXT INDEX ON tblAuditLog(ChangeDetail) KEY INDEX PK_tblAuditLog ON FT_Audit;.
        /// </summary>
        internal static string FT_Audit {
            get {
                return ResourceManager.GetString("FT_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[GetNewCredentialsThatCanProgressToEligibleForTesting]
        ///AS
        ///SELECT DISTINCT
        ///	newCredentialRequest.CredentialApplicationId,
        ///	newCredentialRequest.CredentialRequestId
        ///FROM
        ///	tblCredentialRequest existingCredentialRequest
        ///	join tblCredentialApplication existingCredentialApplication on existingCredentialRequest.CredentialApplicationId = existingCredentialApplication.CredentialApplicationId
        ///	join tblCredentialApplication newCredentialApplication on existingCredentialApplication.PersonI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetNewCredentialsThatCanProgressToEligibleForTesting {
            get {
                return ResourceManager.GetString("GetNewCredentialsThatCanProgressToEligibleForTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE GetRemainingStoredFilesForDeletionCount
        ///@Log NVARCHAR(MAX) OUTPUT, 
        ///@TotalCount int OUTPUT
        ///AS
        ///declare @Policy1 as int;set @Policy1 = 365;
        ///declare @Policy2 as int;set @Policy2 = 1095;
        ///declare @Policy3 as int;set @Policy3 = 1095;
        ///declare @Policy4 as int;set @Policy4 = 1095;
        ///declare @Policy5 as int;set @Policy5 = 1095;
        ///declare @Policy6 as int;set @Policy6 = 183;
        ///declare @Policy7 as int;set @Policy7 = 1825;
        ///declare @Policy8 as int;set @Policy8 = 1460;
        ///declare @Policy9 as int;set @Pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetRemainingStoredFilesForDeletionCount {
            get {
                return ResourceManager.GetString("GetRemainingStoredFilesForDeletionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[GetSingleKey] (@TableName VARCHAR(100), 
        ///                                       @NextKey   INT OUTPUT) 
        ///AS 
        ///    DECLARE @table TABLE 
        ///      ( 
        ///         id INT 
        ///      ) 
        ///
        ///    UPDATE tblTableData 
        ///    SET    NextKey = NextKey + 1 
        ///    OUTPUT inserted.NextKey 
        ///    INTO @table 
        ///    WHERE  TableName = @TableName 
        ///
        ///    SELECT @NextKey = Id 
        ///    FROM   @table 
        ///.
        /// </summary>
        internal static string GetSingleKey {
            get {
                return ResourceManager.GetString("GetSingleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE GetStoredFilesForFileDeletion
        ///	@DocumentType int,
        ///	@Entity nvarchar(500),
        ///	@IncludeQueued bit,
        ///	@SelectLimit int
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///
        ///	-- SPECIAL CASES WITH NO Entity and Document Type
        ///	-- Policy 8: &quot;MarkedTestAsset&quot;, TestSittingDocumentEntity
        ///	IF @Entity like &apos;%tblTestSittingDocument%&apos; and @DocumentType = 0
        ///		SELECT TOP(@SelectLimit)
        ///		storedFile.StoredFileId
        ///	FROM
        ///		tblStoredFile storedFile JOIN
        ///		tluDocumentType documentType ON storedFile.DocumentTypeId = documentTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetStoredFilesForFileDeletion {
            get {
                return ResourceManager.GetString("GetStoredFilesForFileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER PROCEDURE [dbo].[LegacyAccreditationMerge]
        ///AS
        ///insert into [naati_db].[dbo].[tblLegacyAccreditation]
        ///select 
        ///a.ApplicationId,
        ///al.WebDisplay as &apos;Level&apos;, ac.Description as&apos;Category&apos;,
        ///(CASE WHEN am.AccreditationMethodId != (select AccreditationMethodId from [sam4_db].[dbo].[tluAccreditationMethod] where Code = &apos;E&apos;) 
        ///THEN (CASE WHEN ToEnglish is null THEN &apos;B&apos; ELSE (CASE WHEN ToEnglish = 1 THEN &apos;E&apos; ELSE &apos;O&apos; END) END) 
        ///ELSE (CASE WHEN LanguageToBoth = 1 THEN &apos;B&apos; ELSE &apos;O&apos; END) END) 
        ///as &apos;Direction&apos;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LegacyAccreditationMerge {
            get {
                return ResourceManager.GetString("LegacyAccreditationMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[NH_EntityInsert]
        ///	--@NAATINumberType int,
        ///	@EntityTypeId int, 
        ///	@ABN varchar (50), 
        ///	@UseEmail bit, 
        ///	@GSTApplies bit,
        ///	@WebsiteInPD bit,
        ///	@WebsiteURL varchar (200), 	
        ///	@Note varchar (8000), 
        ///	@AccountNumber varchar(255),
        ///	@NaatiNumber int
        ///AS
        ///
        ///BEGIN
        ///	INSERT INTO tblEntity ( NAATINumber, WebsiteURL, ABN, Note, UseEmail, WebsiteInPD, GSTApplies,EntityTypeId, AccountNumber) 
        ///	VALUES ((case @NaatiNumber when 0 then dbo.fnGetNextNAATINumber(@EntityTypeId) else @NaatiNumber e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NH_EntityInsert {
            get {
                return ResourceManager.GetString("NH_EntityInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[PersonSelect]
        ///@EntityId int
        ///AS
        ///
        ///DECLARE @IsRolePlayerAvailable bit
        ///
        ///DECLARE @PersonId int
        ///
        ///SET @IsRolePlayerAvailable = (SELECT CASE Value WHEN &apos;true&apos; THEN 1 ELSE 0 END FROM tblSystemValue WHERE ValueKey = &apos;RolePlayerAvailable&apos;)
        ///
        ///SELECT @PersonId = PersonId from tblPerson WHERE EntityId = @EntityId
        ///
        ///SELECT *
        ///	,CAST(CASE WHEN PersonCredentials &gt; 0 AND PersonCredentials = ExpiredCredentials THEN 1 ELSE 0 END AS BIT) IsFormerPractitioner
        ///	,CAST(CASE WHEN PersonCredentials &gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonSelect {
            get {
                return ResourceManager.GetString("PersonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [PhoneSelect]
        ///@EntityId int
        ///WITH EXEC AS CALLER
        ///AS
        ///SELECT		p.PhoneId, p.EntityId, p.Number, p.CountryCode, p.AreaCode, p.LocalNumber, p.Note, p.IncludeInPD, p.PrimaryContact, p.Invalid, p.AllowSmsNotification,  p.ExaminerCorrespondence
        ///FROM		tblPhone p
        ///WHERE		EntityId = @EntityId and (p.PrimaryContact = 1 or p.Invalid = 0).
        /// </summary>
        internal static string PhoneSelect {
            get {
                return ResourceManager.GetString("PhoneSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[PrerequisiteApplications]
        ///
        ///@ApplicationId int
        ///
        ///AS
        ///
        ///------------------------------------- CLEAN UP OF TEMP TABLES IN CASE THE PROCEDURE BOMBED BEFORE IT COULD DROP THE TABLE LAST RUN -------------------------------------
        ///	DROP TABLE IF EXISTS #TempPrerequisiteHeirarchy;
        ///
        ///------------------------------------- RECURSION TO EXTRACT THE PREREQUISITE HIERARCHY FOR THE GIVEN CREDENTIAL REQUEST -------------------------------------
        ///
        ///	-- Using a technique called Common Table Express [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrerequisiteApplications {
            get {
                return ResourceManager.GetString("PrerequisiteApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[PrerequisiteApplicationsNullableApplications]
        ///	-- Add the parameters for the stored procedure here
        ///	@CredentialRequestId int
        ///AS
        ///BEGIN
        ///
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///------------------------------------- CLEAN UP OF TEMP TABLES IN CASE THE PROCEDURE BOMBED BEFORE IT COULD DROP THE TABLE LAST RUN -------------------------------------
        ///	DROP TABLE IF EXISTS #TempPrerequisiteHeirarchy;
        ///
        ///---- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrerequisiteApplicationsNullableApplications {
            get {
                return ResourceManager.GetString("PrerequisiteApplicationsNullableApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[PrerequisiteSummary]
        ///	@CredentialRequestId int
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///------------------------------------- CLEAN UP OF TEMP TABLES IN CASE THE PROCEDURE BOMBED BEFORE IT COULD DROP THE TABLE LAST RUN -------------------------------------
        ///	DROP TABLE IF EXISTS #TempPrerequisiteHeirarchy;
        ///
        ///------------------------------------- RECURSION TO EXTRACT THE PREREQUISITE HIERARCHY FOR THE GIVEN CREDENTIAL REQUEST -------------------------------------
        ///
        ///	-- Using a technique called [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrerequisiteSummary {
            get {
                return ResourceManager.GetString("PrerequisiteSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].RebuildIndexes
        ///AS
        ///
        ///DECLARE @Table NVARCHAR(255);  
        ///DECLARE @cmd NVARCHAR(1000);
        ///
        ///   DECLARE TableCursor CURSOR READ_ONLY FOR SELECT TABLE_NAME as tableName 
        ///   FROM INFORMATION_SCHEMA.TABLES WHERE table_type = &apos;BASE TABLE&apos;   
        ///   And TABLE_SCHEMA = &apos;dbo&apos; --Ignore hangfire tables
        ///
        ///   OPEN TableCursor   
        ///
        ///   FETCH NEXT FROM TableCursor INTO @Table       
        ///
        ///   WHILE @@FETCH_STATUS = 0   
        ///   BEGIN
        ///      BEGIN TRY   
        ///         SET @cmd = &apos;ALTER INDEX ALL ON &apos; + @Table + &apos; REBU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RebuildIndexes {
            get {
                return ResourceManager.GetString("RebuildIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE REGIONSELECT (@RowVersion ROWVERSION = NULL) 
        ///AS 
        ///    SELECT RegionId, 
        ///           [Name], 
        ///           StateId, 
        ///           CountryId, 
        ///           RowVersion 
        ///    FROM   tluRegion 
        ///    WHERE  ( tluRegion.RowVersion &gt; @RowVersion 
        ///              OR @RowVersion IS NULL ) 
        ///    ORDER  BY NAME .
        /// </summary>
        internal static string RegionSelect {
            get {
                return ResourceManager.GetString("RegionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReleaseJobToken]
        ///(@JobName varchar(100),
        /// @Success bit OUTPUT)
        ///AS	
        ///	DECLARE @table table ([Value] nvarchar(max))
        ///	UPDATE tblSystemValue SET [Value] = &apos;0&apos;
        ///	OUTPUT inserted.[Value] 
        ///	INTO @table
        ///	WHERE ValueKey = @JobName AND TRY_CONVERT(datetime, [VALUE])  IS NOT NULL
        ///
        ///	select @Success = CAST(COUNT(*) AS BIT) from @table.
        /// </summary>
        internal static string ReleaseJobToken {
            get {
                return ResourceManager.GetString("ReleaseJobToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201712141000,
        ///201804051100,
        ///201807061101,
        ///201904301700,
        ///201917051700
        ///.
        /// </summary>
        internal static string RemovedMigrations {
            get {
                return ResourceManager.GetString("RemovedMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemovedSystemValues {
            get {
                return ResourceManager.GetString("RemovedSystemValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[RequestJobToken]
        ///(@JobName varchar(100),
        /// @Success bit OUTPUT)
        ///AS
        ///	DECLARE @MaximunRunningTime int = 61;
        ///	DECLARE @table table ([Value] nvarchar(max))
        ///	UPDATE tblSystemValue SET [Value] =  CONVERT(nvarchar(max), GETDATE(), 126)
        ///	OUTPUT inserted.[Value] 
        ///	INTO @table
        ///	--If the time is greater than running time then token is assigned.
        ///	WHERE ValueKey = @JobName AND  ([Value] = &apos;0&apos; OR (TRY_CONVERT(datetime, [VALUE])  IS NOT NULL AND  DATEADD(MINUTE, -@MaximunRunningTime, GETDAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestJobToken {
            get {
                return ResourceManager.GetString("RequestJobToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE dbo.RevertTestResult @attendanceId INT 
        ///AS 
        ///    DECLARE @appType		  INT,
        ///			@testStatus		  INT,
        ///			@oldStatus        VARCHAR(50), 
        ///            @newStatus        VARCHAR(50), 
        ///            @newStatusDisplay VARCHAR(50), 
        ///            @crId             INT, 
        ///            @credId           INT, 
        ///            @skillName        VARCHAR(100), 
        ///            @appId            INT, 
        ///            @note             VARCHAR(100) = &apos;&apos; 
        ///
        ///    SET xact_abort ON 
        ///
        ///	SELECT @appType = CredentialAppli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RevertTestResult {
            get {
                return ResourceManager.GetString("RevertTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- this is used when sending out test materials for supplementary tests
        ///-- it identifies which components passed so that the material is not sent out
        ///
        ///CREATE PROCEDURE SupplementaryMaterialsFilterTestComponentsThatPassed 
        ///
        ///	@CredentialRequestId int
        ///AS
        ///BEGIN
        ///	SELECT 
        ///	d.Successful,
        ///	e.TestComponentId 
        ///	FROM 
        ///	tblTestSitting a inner join
        ///	tbltestresult b ON b.TestSittingId = a.TestSittingId inner join
        ///	tblTestResultRubricTestComponentResult c ON b.TestResultId = c.TestResultId inner join
        ///	tblRu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupplementaryMaterialsFilterTestComponentsThatPassed {
            get {
                return ResourceManager.GetString("SupplementaryMaterialsFilterTestComponentsThatPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vwDistinctInstitutionName 
        ///AS 
        ///  SELECT InstitutionId, 
        ///         MAX(InstitutionNameId) AS InstitutionNameId 
        ///  FROM   dbo.tblInstitutionName 
        ///  GROUP  BY InstitutionId .
        /// </summary>
        internal static string vwDistinctInstitutionName {
            get {
                return ResourceManager.GetString("vwDistinctInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vwDistinctPersonName 
        ///AS 
        ///  SELECT pn.PersonId, 
        ///         MAX(PersonNameId) AS PersonNameId 
        ///  FROM   tblPersonName pn 
        ///         INNER JOIN vwMaxPersonNameEffectiveDate vef 
        ///                 ON vef.PersonId = pn.PersonId 
        ///                    AND vef.EffectiveDate = pn.EffectiveDate 
        ///  GROUP  BY pn.PersonId .
        /// </summary>
        internal static string vwDistinctPersonName {
            get {
                return ResourceManager.GetString("vwDistinctPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.vwIssuedCredentialCredentialRequest 
        ///AS 
        ///SELECT C.CREDENTIALID as CredentialId, MAX(CR.CREDENTIALREQUESTID) as CredentialRequestId
        ///FROM TBLCREDENTIAL C 
        ///INNER JOIN TBLCREDENTIALCREDENTIALREQUEST CCR ON C.CREDENTIALID = CCR.CredentialId
        ///INNER JOIN TBLCREDENTIALREQUEST CR ON CCR.CREDENTIALREQUESTID = CR.CREDENTIALREQUESTID AND CR.CREDENTIALREQUESTSTATUSTYPEID = 12 -- CERTIFICATION ISSUED
        ///GROUP BY C.CREDENTIALID 
        ///.
        /// </summary>
        internal static string vwIssuedCredentialCredentialRequest {
            get {
                return ResourceManager.GetString("vwIssuedCredentialCredentialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[vwJobExaminerPayrollStatus] 
        ///AS
        ///WITH js
        ///AS
        ///(
        ///	SELECT
        ///		tblJobExaminer.JobExaminerID
        ///		,CASE
        ///			WHEN ExaminerToPayrollDate IS NOT NULL
        ///					-- this cutoff prevents old markings without a SentToPayroll date being shown in the Validate Payroll screen. We&apos;ll probably fine tune this, or run a DB update to make it unnecessary
        ///					OR ExaminerReceivedDate &lt; &apos;2017/02/01&apos; THEN &apos;ClaimForm&apos;
        ///			WHEN ExaminerReceivedDate IS NULL THEN &apos;NotReceived&apos;
        ///			WHEN ValidatedDate IS NULL THEN &apos;Receiv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwJobExaminerPayrollStatus {
            get {
                return ResourceManager.GetString("vwJobExaminerPayrollStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[vwMarkingsForPayroll]
        ///AS
        ///SELECT
        ///    u1.FullName									AS ProductSpecificationChangedUser
        ///    ,ct.InternalName							AS TestType
        ///    ,REPLACE(REPLACE(d.DisplayName, &apos;[Language 1]&apos;, l1.[Name]), &apos;[Language 2]&apos;, l2.[Name]) AS [Language]
        ///    ,Surname + &apos;, &apos; + GivenName					AS Examiner
        ///    ,pm.PersonId								AS ExaminerPersonId
        ///    ,ent.EntityId								AS ExaminerEntityId
        ///    ,ent.NaatiNumber							AS ExaminerNaatiNumber
        ///    ,ent.AccountNumber							AS ExaminerAccountNumber
        ///    ,j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwMarkingsForPayroll {
            get {
                return ResourceManager.GetString("vwMarkingsForPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vwMaxPersonNameEffectiveDate 
        ///AS 
        ///  SELECT PersonId, 
        ///         MAX(EffectiveDate) AS EffectiveDate 
        ///  FROM   tblPersonName 
        ///  GROUP  BY PersonId .
        /// </summary>
        internal static string vwMaxPersonNameEffectiveDate {
            get {
                return ResourceManager.GetString("vwMaxPersonNameEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vwPersonDistinct 
        ///AS 
        ///  SELECT tblPerson.EntityId, 
        ///         tblPersonName.GivenName, 
        ///         tblPersonName.Surname 
        ///  FROM   tblPerson 
        ///         INNER JOIN tblPersonName 
        ///                 ON tblPerson.PersonId = tblPersonName.PersonId 
        ///         INNER JOIN vwDistinctPersonName 
        ///                 ON tblPersonName.PersonNameId = vwDistinctPersonName.PersonNameId .
        /// </summary>
        internal static string vwPersonDistinct {
            get {
                return ResourceManager.GetString("vwPersonDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE   VIEW [dbo].[vwRolePlayerLastTestSession]
        ///--WITH SCHEMABINDING  
        ///AS 
        ///WITH RolePlayerSessions
        ///as
        ///(
        ///SELECT testSessionRolePlayer.RolePlayerId, Max(testSession.TestDateTime) AS LastAttendedDate FROM tblTestSessionRolePlayer testSessionRolePlayer
        ///INNER JOIN tblTestSession testSession on testSession.TestSessionId = testSessionRolePlayer.TestSessionId
        ///where testSessionRolePlayer.Rejected = 0 And testSessionRolePlayer.Attended = 1
        ///group by testSessionRolePlayer.RolePlayerId
        ///)
        ///select  RolePlaye [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwRolePlayerLastTestSession {
            get {
                return ResourceManager.GetString("vwRolePlayerLastTestSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.vwSkillDisplayName 
        ///AS 
        ///  SELECT SkillId, 
        ///         Replace(Replace(d.DisplayName, &apos;[Language 1]&apos;, 
        ///            l1.[Name]), &apos;[Language 2]&apos;, 
        ///         l2.[Name]) AS DisplayName 
        ///  FROM   tblSkill 
        ///         JOIN tblLanguage l1 
        ///           ON l1.LanguageId = tblSkill.Language1Id 
        ///         JOIN tblLanguage l2 
        ///           ON l2.LanguageId = tblSkill.Language2Id 
        ///         JOIN tblDirectionType d 
        ///           ON d.DirectionTypeId = tblSkill.DirectionTypeId .
        /// </summary>
        internal static string vwSkillDisplayName {
            get {
                return ResourceManager.GetString("vwSkillDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[vwTestMaterialCreationPayments]
        ///AS
        ///SELECT 
        ///mr.OutputMaterialId as &apos;TestMaterialId&apos;,
        ///mrr.SubmittedDate as &apos;MaterialCreationSubmittedDate&apos;,
        ///CASE 
        ///WHEN mrr.MaterialRequestRoundStatusTypeId = 1 THEN &apos;Awaiting Development&apos; 
        ///WHEN mrr.MaterialRequestRoundStatusTypeId = 2 THEN &apos;Awaiting NAATI&apos;&apos;s Approval&apos; 
        ///WHEN mrr.MaterialRequestRoundStatusTypeId = 3 THEN &apos;Rejected&apos; 
        ///WHEN mrr.MaterialRequestRoundStatusTypeId = 4 THEN &apos;Approved&apos; 
        ///WHEN mrr.MaterialRequestRoundStatusTypeId = 5 THEN &apos;Cance [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwTestMaterialCreationPayments {
            get {
                return ResourceManager.GetString("vwTestMaterialCreationPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.vwTestMaterialLastUsed 
        ///AS 
        ///
        ///SELECT TM.TESTMATERIALID as TestMaterialId, MAX(TSS.TESTDATETIME) as LastUsedDate
        ///FROM TBLTESTMATERIAL TM 
        ///LEFT JOIN TBLTESTSITTINGTESTMATERIAL TSTM ON TM.TESTMATERIALID = TSTM.TESTMATERIALID
        ///LEFT JOIN TBLTESTSITTING TS ON TS.TESTSITTINGID = TSTM.TESTSITTINGID AND  TS.REJECTED = 0 AND TS.SAT = 1
        ///LEFT JOIN TBLTESTSESSION TSS ON TSS.TESTSESSIONID = TS.TESTSESSIONID 
        ///GROUP BY TM.TESTMATERIALID
        ///.
        /// </summary>
        internal static string vwTestMaterialLastUsed {
            get {
                return ResourceManager.GetString("vwTestMaterialLastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.vwTestMaterialRequestRoundLatest 
        ///AS 
        ///
        ///SELECT MRR.MATERIALREQUESTID AS MATERIALREQUESTID, MAX(MRR.MATERIALREQUESTROUNDID) AS LATESTMATERIALROUNDID FROM TBLMATERIALREQUESTROUND MRR
        ///INNER JOIN TBLMATERIALREQUEST MR ON MR.MATERIALREQUESTID = MRR.MATERIALREQUESTID
        ///GROUP BY MRR.MATERIALREQUESTID.
        /// </summary>
        internal static string vwTestMaterialRequestRoundLatest {
            get {
                return ResourceManager.GetString("vwTestMaterialRequestRoundLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[vwTestSittingAsset]
        ///AS
        ///SELECT tblTestSittingDocument.TestSittingDocumentId, 
        ///    tblTestSitting.TestSittingId, 
        ///    tblTestMaterialAttachment.TestMaterialId,
        ///    tblTestMaterialAttachment.TestMaterialAttachmentId,
        ///    tblEntity.NaatiNumber, 
        ///    tblStoredFile.StoredFileId, 
        ///    tblStoredFile.FileName, 
        ///    ISNULL(tblTestSittingDocument.Title, tblTestMaterialAttachment.Title) Title, 
        ///    u1.UserId                               AS UploadedByUserId, 
        ///    u1.FullName                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwTestSittingAsset {
            get {
                return ResourceManager.GetString("vwTestSittingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE   VIEW [dbo].[vwTestStatus]
        ///--WITH SCHEMABINDING  
        ///AS 
        ///
        ///WITH TestStatusInfo
        ///as
        ///(
        ///select testSitting.TestSittingId,
        ///MAX(Cast(testSitting.Supplementary as int)) AS IsSupplementaryTestSitting,
        ///MAX(cast(credentialRequest.Supplementary as int)) AS IsSupplementaryCredentialRequest,
        ///sum(CASE WHEN testResult.ResultChecked IS NOT NULL AND  testResult.ResultChecked = 1 THEN 0 ELSE 1 END) AS ResultsToBeChecked,
        ///sum(CASE WHEN jobExaminer.PaidReviewer = 1 THEN 1 ELSE 0 END) AS SumPaidViewer, 
        ///sum(CA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwTestStatus {
            get {
                return ResourceManager.GetString("vwTestStatus", resourceCulture);
            }
        }
    }
}
