//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.Reports._20171013_AddOrganisationTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.Reports._20171013_AddOrganisationTable.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[ReportingSnapshot_OrganisationContacts]
        ///AS
        ///BEGIN
        ///	SELECT
        ///		CASE WHEN [Source].[ContactPersonId] IS NULL THEN [OrganisationContacts].[ContactPersonId] ELSE [Source].[ContactPersonId] END AS [ContactPersonId]
        ///		,CASE WHEN [Source].[ContactPersonId] IS NULL THEN [OrganisationContacts].[OrganisationId] ELSE [Source].[OrganisationId] END AS [OrganisationId]
        ///		,CASE WHEN [Source].[ContactPersonId] IS NULL THEN [OrganisationContacts].[Name] ELSE [Source].[Name] END AS [Name]
        ///		,CASE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddOrganisationContactsProcedure {
            get {
                return ResourceManager.GetString("AddOrganisationContactsProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[OrganisationContacts] AS
        ///SELECT
        ///	[ContactPersonId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[OrganisationId]
        ///	,[Name]
        ///	,[Email]
        ///	,[Phone]
        ///	,[Address]
        ///	,[Description]
        ///FROM [OrganisationContactsHistory] a
        ///WHERE a.[ModifiedDate] =
        ///(
        ///    SELECT MAX([ModifiedDate])
        ///    FROM [OrganisationContactsHistory] a2
        ///    WHERE a2.[ContactPersonId] = a.[ContactPersonId]
        ///)
        ///AND [DeletedDate] IS NULL.
        /// </summary>
        internal static string AddOrganisationContactsView {
            get {
                return ResourceManager.GetString("AddOrganisationContactsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[ReportingSnapshot_Organisation]
        ///AS
        ///BEGIN
        ///	SELECT
        ///		CASE WHEN [Source].[OrganisationId] IS NULL THEN [Organisation].[OrganisationId] ELSE [Source].[OrganisationId] END AS [OrganisationId]
        ///		,CASE WHEN [Source].[OrganisationId] IS NULL THEN [Organisation].[NAATINumber] ELSE [Source].[NAATINumber] END AS [NAATINumber]
        ///		,CASE WHEN [Source].[OrganisationId] IS NULL THEN [Organisation].[Name] ELSE [Source].[Name] END AS [Name]
        ///		,CASE WHEN [Source].[OrganisationId] IS NULL THEN [Or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddOrganisationProcedure {
            get {
                return ResourceManager.GetString("AddOrganisationProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[Organisation] AS
        ///SELECT
        ///	[OrganisationId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[NAATINumber]
        ///	,[Name]
        ///	,[PrimaryAddress]
        ///	,[Suburb]
        ///	,[Country]
        ///	,[PrimaryPhone]
        ///	,[PrimaryEmail]
        ///	,[TrustedPayer]
        ///FROM [OrganisationHistory] a
        ///WHERE a.[ModifiedDate] =
        ///(
        ///    SELECT MAX([ModifiedDate])
        ///    FROM [OrganisationHistory] a2
        ///    WHERE a2.[OrganisationId] = a.[OrganisationId]
        ///)
        ///AND [DeletedDate] IS NULL.
        /// </summary>
        internal static string AddOrganisationView {
            get {
                return ResourceManager.GetString("AddOrganisationView", resourceCulture);
            }
        }
    }
}
