//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.NAATI._20170821_ChangesToContacts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.NAATI._20170821_ChangesToContacts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblPhone]
        ///ADD PrimaryContact BIT NOT NULL DEFAULT 0.
        /// </summary>
        internal static string AddPrimaryContact {
            get {
                return ResourceManager.GetString("AddPrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblAddress]
        ///DROP CONSTRAINT FK_tblAddress_tluContactType
        ///
        ///ALTER TABLE [dbo].[tblAddress]
        ///DROP COLUMN ContactTypeId.
        /// </summary>
        internal static string DropAddressColumn {
            get {
                return ResourceManager.GetString("DropAddressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE [dbo].[tluContactType].
        /// </summary>
        internal static string DropContactTypeTable {
            get {
                return ResourceManager.GetString("DropContactTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblEmail]
        ///DROP CONSTRAINT FK_tblEmail_tluContactType
        ///
        ///DROP INDEX _dta_index_tblEmail_9_5575058__K6_K5_K2_K3
        ///ON [dbo].[tblEmail]
        ///
        ///DROP STATISTICS [dbo].[tblEmail]._dta_stat_5575058_2_6
        ///DROP STATISTICS [dbo].[tblEmail]._dta_stat_5575058_3_6_5
        ///DROP STATISTICS [dbo].[tblEmail]._dta_stat_5575058_5_2_6_3
        ///
        ///ALTER TABLE [dbo].[tblEmail]
        ///DROP COLUMN ContactTypeId.
        /// </summary>
        internal static string DropEmailColumn {
            get {
                return ResourceManager.GetString("DropEmailColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblPhone]
        ///DROP CONSTRAINT FK_tblPhone_tluContactType
        ///
        ///DROP INDEX IX_ContactTypeId_IncludeInPD_EntityId
        ///ON [dbo].[tblPhone]
        ///
        ///DROP INDEX IX_EntityId_ContactTypeId
        ///ON [dbo].[tblPhone]
        ///
        ///DROP STATISTICS [dbo].[tblPhone]._dta_stat_760389778_2_9_8
        ///
        ///ALTER TABLE [dbo].[tblPhone]
        ///DROP COLUMN ContactTypeId.
        /// </summary>
        internal static string DropPhoneColumn {
            get {
                return ResourceManager.GetString("DropPhoneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE [dbo].[ContactTypeSelect].
        /// </summary>
        internal static string DropProcedureContactTypeSelect {
            get {
                return ResourceManager.GetString("DropProcedureContactTypeSelect", resourceCulture);
            }
        }
    }
}
