apiVersion: v1
kind: Secret
metadata:
  name: dev-naati-storage
type: Opaque
data:
  # Base64_Encoded account name
  azurestorageaccountname: bmFhdGlkZXZhcHBmaWxlc2kwcTAK
  # Base64_Encoded key
  azurestorageaccountkey: QXZTcmdubUI3MjU5VnRrbVRVa2kvZFh2a3lGM1lLdGUxenFFSUlmYTJWYW5HRzhTcVpWV1ZqL1RFQmt1VFpnK3ZNYkRvQnBBRWZLUStBU3RpUzBHWGc9PQo=


