apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-naati-temp-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: dev-naati-temp-persistent-storage