apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-naati-temp-persistent-storage
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: dev-naati-temp-storage
    shareName: temp-files-share
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777