apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mynaati-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta2
    kind: Deployment
    name: my-mynaati-release-mynaati
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 175