namespace F1Solutions.Naati.Common.Contracts.Dal.Enum
{
    public enum CredentialRequestStatusTypeName
    {
        None = 0,
        Draft = 1,
        Rejected = 2,
        RequestEntered = 3,
        ReadyForAssessment = 4,
        BeingAssessed = 5,
        Pending = 6,
        AssessmentFailed = 7,
        AssessmentPaidReview = 8,
        AssessmentComplete = 9,
        EligibleForTesting = 10,
        TestFailed = 11,
        CertificationIssued = 12,
        Cancelled = 13,
        Deleted = 14,
        AwaitingTestPayment = 15,
        Withdrawn = 16,
        TestAccepted = 17,
        TestSessionAccepted = 19,
        CheckedIn = 20,
        TestSat = 21,
        IssuedPassResult = 22,
        UnderPaidTestReview = 23,
        AwaitingSupplementaryTestPayment = 24,
        AwaitingApplicationPayment = 25,
        ProcessingSubmission = 26,
        ProcessingPaidReviewInvoice = 27,
        AwaitingPaidReviewPayment = 28,
        ProcessingSupplementaryTestInvoice = 29,
        TestInvalidated = 30,
        ToBeIssued = 31,
        ProcessingTestInvoice = 32,
        ProcessingRequest = 33,
        RefundRequested = 34,
        ProcessingCreditNote = 35,
        AwaitingCreditNotePayment = 36,
        RefundRequestApproved = 37,
        RefundFailed = 38,
        CredentialOnHold = 39,
        IssuePracticeTestResults=40,
        OnHoldToBeIssued=41,
    }
}