apiVersion: v1
kind: Secret
metadata:
  name: timezone-setter-ssh-key
  namespace: default
type: Opaque
stringData:
  id_rsa: |-
   -----BEGIN OPENSSH PRIVATE KEY-----
   b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDOxmUsCw
   m/aKr48KO1xMYlAAAAGAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQC9y0LDcasT
   5oWMt01OWNF08PpSqaQqGw07aDDtMvXbDCsii2wL0mX7Ra46u/Xfcljxg/7W9UJEkm9Ce1
   1aQR7nn/mipRLojG3sdeDpGyaaXch/hoSFArdX6/rIy9eKyz8N/jKqxTqWnh9She/QqoWM
   8FQUTnDWWPsro1ROej0WQ2v3pBAaCOu3v/U9YnfjD1yI3NkdR1kLMkZZfb7wqXqke8myjS
   KZ8ytU2yjT1tzQun1TSjLyQlWpiSq4+SS5/6/XUFhAwTfXzhHtZc0RRimSaU4yYviHxRWS
   iu9i+H8EkEYcuCMDlRVLgr1GKs982W/z86Zpa6CCwTIxs7dznMgk5Phjb7pc0vtGTeH90m
   re42o/7kla93Zf2ZOXhcLRJoFgp1YQNLi9/bHhn96MSloRSbVaOA7WBSTZll/vsa1caT/q
   Nk9ersiooF9u5uital7JJv66d2lHPBe+1mCnMZ9yZ6izMkIzrsHdWY835YVtN3x3tV7jl6
   dj5ZnsUpcGyKYq0dgmohJ1hOdX8LPMHNJbeht2NSIKY+5StI2GumT4rfXGr0PBmzw3p/h9
   HdAxozm0Ar+5jrOAdCHy6MPd6LPWxkrTRPc3gOJZ9+lJp6iA8Io31KjBZ8t9wE99vgwlig
   aLUvYnjHH4XsS3tLUd4OsRIWwO53t9rRX1JGRVZbKPTwAAB1CSvswCzimHHEAD3I3QDAUy
   3pbbSJm9L55KqlZeLmfYiq0wsOd88BcYTDVMb2xhTqnfY83ZQR/tfrbof8Q3n65BkggOLW
   UImpD5wcEqXQo0FMiAj411ujAQCtmKbyllcv4Jj+cU/IYot1J/d87Jj5BlE3oQQFMXXHc4
   kXldHGFAcJPj+EvvZU2S2oHOi2PN7e/GboFewg0XnwuDNlBa8SPdUVNfaqlgTii4hWp2vb
   MKZTWq+uqqisLY3r//rNd/LufMQ1LzhUGLW0gnFasHR4/6sNy5jo7n0YajwnVgg0RZjq+z
   TYFzQSCEdzkKrPlIbQhu9RCk7Uo5jMCU+OBZADrRa89N/rcrkSY1+w0lQcsa2g82o4ZkOp
   oPKA+U4BZLjx3gmCQOQVRD+5k+bQEt4W9d7PJxm/nGlyMa9S8JBkEbIwSXPFklnVE8oAxz
   dcXVQFfZWcMm4s6F2gFg4w5pM48geRG/tghWxTVIMaMUarGQ6qn1v1pG8RwQpdQGx6yHGN
   mc7C/M4jTuk2ei8gZHD6xrnTetUw//3Zp+hcYYqZ/XYWLt5eO2gw1jKkwT9B2wsL+0uR1G
   7bWs+LcWCahLEJemrc1eTY/k8MUF8PPIP+U38lowEDUFOBnmAHI2sMa3PM3WDY5N9YBgnq
   gAloA5iAsnxHgkZSc8A8Mc5b26fNqVgLUvcFeppeK+6RZ/J9LIQA1fLM1PZzJA0cSeBeBP
   AAb+qJlpmlgtv3foCFzxcWIBI1L3uwRDVKlP7QIzKCIG0YBAHSLOVMKFISufOBypYsJwry
   OKzIrNR4p1s3oF6gvQa14MCwoQaGfNB4zY/M3WjMqX4MvrtAryzl9TFfg5d+H3mJTNW4Tx
   vPvmOLsfJqOfcWdhNBoexpblfihd2xDEdO6EJrEW7CJSxvFOIcQTewHnAcFnpTvsC21Fqh
   /0JZzFihzGUvi999Ujb+7a9HwIz/UYCC3Dq1THhotPl2CVqmED9rBQ4466mbFiMQOg7Q9t
   IMvCBiCuQriezVzCtoPkusx8cg5iuEApRC8wirIIgcWb4N+WbtxVpmIr301TfDDNItElwF
   9T7H5wyJ1Y4L30THSUfPDCrcosJIoKZJbqosIxErAQS1U3V2We6XYt5c3mjW6jxsixEctD
   ClyRZyiQr3RXW9SiG8/yxHOoUix56SH9lM5Rx4qNXr0EQCSpnOGOMmY+PS5WzZliXoqFQu
   nAsI5K2p9woin6AfFlz9HwkavraWUQulkkdaIVqbTX00oYfJ8b6GwdwPWrgoCWrIljtvwB
   y1TqzhJ1c+ytEbRaFghyJ71ZSk9M92EZrv++qIEghufbKTQIVl6ZCT32vTbmur5zgcPsXI
   gvfXCIzBSjIwYWC2ubCI3iKHnh7Jv+Cl/UOvioxv5lBGseTPj+dU9wK8ZS3mrjOOCFALLe
   FsiTDeGSnqD5i+WU0weipFJx39vcywgTY/gjdeDXBF9mM4l4057crH3P/NmhBexaPkrPMH
   XMv8gub4Se2Smc92r+yNS7nr9yWaiaZuJEemqjklbahkGrb115SzKVJ8hYJ6ApLlQ2a11+
   14//P63XqtfoTC/3Qyjcoe5nQgAsUYBiPleRuct1TpobbxH9/xf3lTW5rjLBmo8jPpGCwm
   DsbddUnSMETJSXr83uI8tHPvv16wNsABMtgHAtR8Sh2ofcvO3n1diVRkmebIRLvF06F3un
   8ULhbnsl++S7P7z84o8nPnEHsXenNpo+UPL/cqLrpkA2M5WHJ3RHWj81STzGG+1nO3fN0Y
   O5apwiYhIhp7BZXOhSiOFQzxAjjD/JvDYtJ7HNtQy/ncCLu7NYP9kvXdHvyF8OUP9HzYnv
   TmhyLkMnGGzCLKzH6wn1hgY7yBCCkTjxZ+T1C0d9WuNqUqgevUqcHkzcrDue5IRh6sofKV
   15bNkGX85oWaexRsYW/w31N/wMQs5JfmQl7ZUFkGIqWvqpXIbgOiY/cwXOdGwDZNN8rJpb
   enD8FSBYiOcLZ6Vj0A/QqybjXO//egYH3ZtY28d8gk52MQEq7fCThCo155c0/nob6MwuV/
   dZqXjLeC6lojXDrqQJAah12m6c+PnT+XK7c8KQxUso1Srf3N2GWYAueWVFgG9VS004JBWX
   GhsWXDxTfVuScY25IGoS5EWQDymcMmwROm92SN1wJ0EXwPpqovKZrK2j8PZW7l7T1AlJUm
   yJ2j8uO7Y6pkog2Do/TzU4xIcjnfWYXNZ2Bf+Ya/lB4EAk0ocgNxvf6beX8paSVerXnF3K
   s0ThSW4ZMkAIIhOJG7vXFN2o4RnbFQ4seMFYl8DOohOxtAW5b2m1pp/txoUXQ25MtKUhNE
   qFnA8sB4MjLKatHRRgX64RExNhiJ908Qnx4qtrVNqznxD84R8QIGaOQT9tNFpqSGkTL4YI
   YHIjTzrXvNX/OLgCYgSg5Tj+NpZGLVlc/H7F5Lvxxrt5YiRlCaXbzik6nQTTPOcH0BY1ks
   3tlxNVfE6jF7Ovy7ExFnSTlKo=
   -----END OPENSSH PRIVATE KEY-----