UPDATE TBLSKILL SET SKILLTYPEID =20 WHERE SKILLID = 423
UPDATE TBLSKILL SET SKILLTYPEID =21 WHERE SKILLID = 541
UPDATE TBLSKILL SET SKILLTYPEID =23 WHERE SKILLID = 696
UPDATE TBLSKILL SET SKILLTYPEID =24 WHERE SKILLID = 713
UPDATE TBLSKILL SET SKILLTYPEID =22 WHERE SKILLID = 731
UPDATE TBLSKILL SET SKILLTYPEID =22 WHERE SKILLID = 732


UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 217
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 220
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 221
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 227
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 234
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 235
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 237
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 238
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 247
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 249
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 252
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 253
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 263
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 264
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 266
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 267
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 268
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 271
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 276
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 277
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 278
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 279
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 280
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 281
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 282
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 289
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 296
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 301
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 303
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 306
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 309
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 314
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 317
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 318
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 349
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 354
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 355
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 356
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 357
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 358
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 359
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 360
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 361
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 363
UPDATE TBLSKILL SET SKILLTYPEID =25 WHERE SKILLID = 364
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 416
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 418
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 419
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 427
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 436
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 437
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 439
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 440
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 445
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 446
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 449
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 450
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 458
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 460
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 461
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 462
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 463
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 465
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 469
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 470
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 471
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 472
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 473
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 474
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 475
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 478
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 483
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 485
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 487
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 489
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 492
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 495
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 499
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 500
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 523
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 528
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 529
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 530
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 531
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 532
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 533
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 534
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 535
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 536
UPDATE TBLSKILL SET SKILLTYPEID =26 WHERE SKILLID = 537

UPDATE TBLSKILL SET SKILLTYPEID =27 WHERE SKILLID = 551

UPDATE tblSkill SET Language1Id = 48, Language2Id = 145 WHERE SkillId = 795
UPDATE tblSkill SET Language1Id = 59, Language2Id = 155 WHERE SkillId = 797
UPDATE tblSkill SET Language1Id = 138, Language2Id = 155 WHERE SkillId = 799



