//#pragma warning disable 1591
////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace F1Solutions.Naati.Common.Dal.Portal.Repositories
//{
//	using System.Data.Linq;
//	using System.Data.Linq.Mapping;
//	using System.Data;
//	using System.Collections.Generic;
//	using System.Reflection;
//	using System.Linq;
//	using System.Linq.Expressions;
//	using System.ComponentModel;
//	using System;
	
	
//	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NAATI_SAM_Phase1_Vinhlan")]
//	public partial class SamLinqRepositoryDataContext : System.Data.Linq.DataContext
//	{
		
//		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
//    #region Extensibility Method Definitions
//    partial void OnCreated();
//    #endregion
		
//		public SamLinqRepositoryDataContext(string connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public SamLinqRepositoryDataContext(System.Data.IDbConnection connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public SamLinqRepositoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public SamLinqRepositoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public System.Data.Linq.Table<vwEPortalUser> vwEPortalUsers
//		{
//			get
//			{
//				return this.GetTable<vwEPortalUser>();
//			}
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwEPortalUser")]
//	public partial class vwEPortalUser
//	{
		
//		private System.Nullable<int> _NAATINumber;
		
//		private string _Surname;
		
//		private string _GivenName;
		
//		private string _OtherNames;
		
//		private bool _Deceased;
		
//		private string _Email;
		
//		private System.Nullable<System.DateTime> _CreationDate;
		
//		public vwEPortalUser()
//		{
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAATINumber", DbType="Int")]
//		public System.Nullable<int> NAATINumber
//		{
//			get
//			{
//				return this._NAATINumber;
//			}
//			set
//			{
//				if ((this._NAATINumber != value))
//				{
//					this._NAATINumber = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
//		public string Surname
//		{
//			get
//			{
//				return this._Surname;
//			}
//			set
//			{
//				if ((this._Surname != value))
//				{
//					this._Surname = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
//		public string GivenName
//		{
//			get
//			{
//				return this._GivenName;
//			}
//			set
//			{
//				if ((this._GivenName != value))
//				{
//					this._GivenName = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherNames", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
//		public string OtherNames
//		{
//			get
//			{
//				return this._OtherNames;
//			}
//			set
//			{
//				if ((this._OtherNames != value))
//				{
//					this._OtherNames = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deceased", DbType="Bit NOT NULL")]
//		public bool Deceased
//		{
//			get
//			{
//				return this._Deceased;
//			}
//			set
//			{
//				if ((this._Deceased != value))
//				{
//					this._Deceased = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
//		public string Email
//		{
//			get
//			{
//				return this._Email;
//			}
//			set
//			{
//				if ((this._Email != value))
//				{
//					this._Email = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
//		public System.Nullable<System.DateTime> WebAccountCreateDate
//		{
//			get
//			{
//				return this._CreationDate;
//			}
//			set
//			{
//				if ((this._CreationDate != value))
//				{
//					this._CreationDate = value;
//				}
//			}
//		}
//	}
//}
//#pragma warning restore 1591
