DELETE FROM tblEmailTemplate 
DELETE FROM tblEmailMessage 
DELETE FROM tblCredentialCredentialRequest 
DELETE FROM tblCredentialRequestFieldData 
DELETE FROM tblCredentialRequest 
DELETE FROM tblCredentialApplicationFieldData 
DELETE FROM tblCredentialApplicationNote 
DELETE FROM tblCredentialApplicationAttachment 
DELETE FROM tblCredentialApplication 
DELETE FROM tblCredentialApplicationTypeCredentialType 
DELETE FROM tblCredentialType 
DELETE FROM tblCredentialApplicationField 
DELETE FROM tblCredentialApplicationTypeDocumentType 
DELETE FROM tblCredentialApplicationType 
DELETE FROM tblSkill 
DELETE FROM tblSkillType 
DELETE FROM tblDirectionType 
DELETE FROM tblCredentialCategory 
DELETE FROM tblDataType 
DELETE FROM tblCredentialApplicationStatusType 
DELETE FROM tblCredentialRequestStatusType 
DELETE FROM tblCredentialApplication 
DELETE FROM tblCredentialRequest 
DELETE FROM tblCredential 
DELETE FROM tblCredentialCredentialRequest 