//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.NAATI._20171003_ConfigureInitialData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.NAATI._20171003_ConfigureInitialData.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM tblEmailTemplate 
        ///DELETE FROM tblEmailMessage 
        ///DELETE FROM tblCredentialCredentialRequest 
        ///DELETE FROM tblCredentialRequestFieldData 
        ///DELETE FROM tblCredentialRequest 
        ///DELETE FROM tblCredentialApplicationFieldData 
        ///DELETE FROM tblCredentialApplicationNote 
        ///DELETE FROM tblCredentialApplicationAttachment 
        ///DELETE FROM tblCredentialApplication 
        ///DELETE FROM tblCredentialApplicationTypeCredentialType 
        ///DELETE FROM tblCredentialType 
        ///DELETE FROM tblCredentialApplicationField 
        ///DELETE FROM tbl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClearExistingData {
            get {
                return ResourceManager.GetString("ClearExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationField] ON 
        ///
        ///INSERT [dbo].[tblCredentialApplicationField] 
        ///       ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) 
        ///VALUES (1, 1, NULL, N&apos;Transition All Credentials&apos;,N&apos;Credentials (mandatory)&apos;, 1, NULL, 0,N&apos;Does the applicant wish to transition all of the current credentials?&apos;, 1, NULL),
        ///       (2, 1, NULL, N&apos;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblCredentialApplicationField {
            get {
                return ResourceManager.GetString("LoadtblCredentialApplicationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblcredentialapplicationstatustype ON 
        ///
        ///INSERT INTO tblCredentialApplicationStatusType 
        ///			(CredentialApplicationStatusTypeId,  [Name],  DisplayName) 
        ///VALUES      (1, &apos;Draft&apos;, &apos;Draft&apos;),  
        ///            (2, &apos;Entered&apos;, &apos;Entered&apos;),  
        ///            (3, &apos;BeingChecked&apos;, &apos;Being Checked&apos;),  
        ///            (4, &apos;Rejected&apos;, &apos;Rejected&apos;),  
        ///            (5, &apos;InProgress&apos;, &apos;In Progress&apos;),  
        ///            (6, &apos;Completed&apos;, &apos;Completed&apos;) 
        ///
        ///SET IDENTITY_INSERT tblcredentialapplicationstatustype OFF .
        /// </summary>
        internal static string LoadtblCredentialApplicationStatusType {
            get {
                return ResourceManager.GetString("LoadtblCredentialApplicationStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblcredentialapplicationtype ON 
        ///
        ///INSERT INTO tblCredentialApplicationType 
        ///            (CredentialApplicationTypeId, [Name], DisplayName, [Online], BackOffice, RequiresChecking,  
        ///             RequiresAssessment, PendingAllowed, AssessmentReviewAllowed) 
        ///VALUES      (1, &apos;Transition&apos;, &apos;Transition&apos;, 0, 1, 1, 1, 1, 0) 
        ///
        ///SET IDENTITY_INSERT tblcredentialapplicationtype OFF .
        /// </summary>
        internal static string LoadtblCredentialApplicationType {
            get {
                return ResourceManager.GetString("LoadtblCredentialApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblcredentialapplicationtypecredentialtype ON 
        ///
        ///INSERT INTO tblCredentialApplicationTypeCredentialType 
        ///            (CredentialApplicationTypeCredentialTypeId, CredentialApplicationTypeId, CredentialTypeId, HasTest)
        ///VALUES      (1, 1, 1, 0),  
        ///            (2, 1, 2, 0),  
        ///            (3, 1, 3, 0),  
        ///            (4, 1, 4, 0),  
        ///            (5, 1, 5, 0),  
        ///            (6, 1, 6, 0),  
        ///            (7, 1, 7, 0),  
        ///            (8, 1, 8, 0),  
        ///            (9, 1, 9, 0),  
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblCredentialApplicationTypeCredentialType {
            get {
                return ResourceManager.GetString("LoadtblCredentialApplicationTypeCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationTypeDocumentType] ON 
        ///
        ///INSERT [dbo].[tblCredentialApplicationTypeDocumentType] 
        ///       ([CredentialApplicationTypeDocumentTypeId], [CredentialApplicationTypeId], [DocumentTypeId], [Mandatory]) 
        ///VALUES (1, 1, 10, 0),  
        ///       (2, 1, 17, 0),  
        ///       (3, 1, 18, 0),  
        ///       (4, 1, 21, 1) 
        ///
        ///SET IDENTITY_INSERT [dbo].[tblCredentialApplicationTypeDocumentType] OFF .
        /// </summary>
        internal static string LoadtblCredentialApplicationTypeDocumentType {
            get {
                return ResourceManager.GetString("LoadtblCredentialApplicationTypeDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblcredentialcategory ON 
        ///
        ///INSERT INTO tblCredentialCategory 
        ///            (CredentialCategoryId, [Name], DisplayName) 
        ///VALUES      (1, &apos;Translator&apos;, &apos;Translator&apos;),  
        ///            (2, &apos;Interpreter&apos;, &apos;Interpreter&apos;),  
        ///            (3, &apos;DeafInterpreter&apos;, &apos;Deaf Interpreter&apos;),  
        ///            (4, &apos;CCL&apos;, &apos;Credentialed Community Language&apos;),  
        ///            (5, &apos;CLA&apos;, &apos;Community Language Aide&apos;),  
        ///            (6, &apos;Ethics&apos;, &apos;Ethics&apos;),  
        ///            (7, &apos;Intercultural&apos;, &apos;Intercultural&apos;),  
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblCredentialCategory {
            get {
                return ResourceManager.GetString("LoadtblCredentialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblcredentialrequeststatustype ON 
        ///
        ///INSERT INTO tblCredentialRequestStatusType 
        ///            (CredentialRequestStatusTypeId, [Name], DisplayName) 
        ///VALUES      (1, &apos;Draft&apos;, &apos;Draft&apos;),  
        ///            (2, &apos;Rejected&apos;, &apos;Application Rejected&apos;),  
        ///            (3, &apos;RequestEntered&apos;, &apos;Request Entered&apos;),  
        ///            (4, &apos;ReadyForAssessment&apos;, &apos;Ready for Assessment&apos;),  
        ///            (5, &apos;BeingAssessed&apos;, &apos;Being Assessed&apos;),  
        ///            (6, &apos;Pending&apos;, &apos;Pending&apos;),  
        ///            (7, &apos;AssessmentF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblCredentialRequestStatusType {
            get {
                return ResourceManager.GetString("LoadtblCredentialRequestStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblcredentialtype ON 
        ///
        ///INSERT INTO tblCredentialType 
        ///            (CredentialTypeId, CredentialCategoryId, InternalName, ExternalName, UpgradePath, Simultaneous, SkillTypeId, Certification)
        ///VALUES      (1, 1, &apos;Recognised Practising Translator&apos;, &apos;Recognised Practising Translator&apos;, 100, 0, 1, 1), 
        ///            (2, 1, &apos;Certified Translator&apos;, &apos;Certified Translator&apos;, 200, 0, 2, 1),  
        ///            (3, 1, &apos;Certified Advanced Translator&apos;, &apos;Certified Advanced Translator&apos;, 300, 1, 3, 1),  
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblCredentialType {
            get {
                return ResourceManager.GetString("LoadtblCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tbldatatype ON 
        ///
        ///INSERT INTO tblDataType 
        ///            (DataTypeId, [Name], DisplayName) 
        ///VALUES      (1, &apos;Bool&apos;, &apos;Boolean&apos;)
        ///
        ///SET IDENTITY_INSERT tbldatatype OFF .
        /// </summary>
        internal static string LoadtblDataType {
            get {
                return ResourceManager.GetString("LoadtblDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tbldirectiontype ON 
        ///
        ///INSERT INTO tblDirectionType 
        ///            (DirectionTypeId, NAME, DisplayName) 
        ///VALUES      (1, &apos;L1toL2&apos;, &apos;[Language 1] into [Language 2]&apos;),  
        ///            (2, &apos;L2toL1&apos;, &apos;[Language 2] into [Language 1]&apos;),  
        ///            (3, &apos;L1andL2&apos;, &apos;[Language 1] and [Language 2]&apos;),  
        ///            (4, &apos;L1&apos;, &apos;[Language 1]&apos;) 
        ///
        ///SET IDENTITY_INSERT tbldirectiontype OFF .
        /// </summary>
        internal static string LoadtblDirectionType {
            get {
                return ResourceManager.GetString("LoadtblDirectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tblEmailTemplate 
        ///			([Name], [Content], [Active], [Subject]) 
        ///VALUES 
        ///(
        ///   N&apos;Application Rejected&apos; 
        ///  ,N&apos;&lt;html&gt;&lt;head&gt;&lt;style&gt;body{{font-family:calibri}}&lt;/style&gt;&lt;/head&gt;&lt;body&gt;
        ///&lt;p&gt;Dear [[Given Name]],&lt;/p&gt;
        ///&lt;p&gt;Thank you for submitting your transition application. Unfortunately, we have chosen to reject your application.&lt;/p&gt;
        ///&lt;p&gt;[[Action Public Note]]&lt;/p&gt;
        ///&lt;p&gt;We would urge you to look at the information regarding NAATI certification on our website to learn more about alternative pathways of gai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblEmailTemplate {
            get {
                return ResourceManager.GetString("LoadtblEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblskill ON 
        ///
        ///INSERT INTO tblSkill 
        ///            (SkillId, SkillTypeId, Language1Id, Language2Id, DirectionTypeId) 
        ///VALUES      (1, 1, 1095, 40, 1),  
        ///            (2, 1, 1095, 40, 2),  
        ///            (3, 1, 396, 40, 1),  
        ///            (4, 1, 396, 40, 2),  
        ///            (5, 1, 1, 40, 1),  
        ///            (6, 1, 1, 40, 2),  
        ///            (7, 1, 3, 40, 1),  
        ///            (8, 1, 3, 40, 2),  
        ///            (9, 1, 4, 40, 1),  
        ///            (10, 1, 4, 40, 2),  
        ///            (11, 1, 996, 40, 1), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblSkill {
            get {
                return ResourceManager.GetString("LoadtblSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblskilltype ON 
        ///
        ///INSERT INTO tblSkillType 
        ///            (SkillTypeId, [Name], DisplayName) 
        ///VALUES      (1, &apos;RPT&apos;, &apos;Recognised Practising Translator&apos;),  
        ///            (2, &apos;CT&apos;, &apos;Certified Translator&apos;),  
        ///            (3, &apos;CAT&apos;, &apos;Certified Advanced Translator&apos;),  
        ///            (4, &apos;CTLOTE&apos;, &apos;Certified Advanced Translator LOTE to LOTE&apos;),  
        ///            (5, &apos;RPI&apos;, &apos;Recognised Practising Interpreter&apos;),  
        ///            (6, &apos;CPI&apos;, &apos;Certified Provisional Interpreter&apos;),  
        ///            (7, &apos;CI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadtblSkillType {
            get {
                return ResourceManager.GetString("LoadtblSkillType", resourceCulture);
            }
        }
    }
}
