apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-naati-volume-claim
  namespace: {{ .Values.pvc.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeName: dev-naati-persistent-storage
