apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-naati-temp-volume-claim
  namespace: {{ .Values.pvcTemp.namespace }}
spec:
  accessModes:
    - {{ .Values.pvcTemp.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvcTemp.storage }}
  storageClassName: {{ .Values.pvcTemp.storageClassName }}
  volumeName: dev-naati-temp-persistent-storage
