ALTER VIEW [dbo].[Application] AS
SELECT
	[ApplicationId]
	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[PersonId]
	,[NAATINumber]
	,[PractitionerNumber]
	,[EnteredDate]
	,[EnteredOffice]
	,[ApplicationStatus]
	,[StatusDateModified]
	,[Sponsor]
	,[Title]
	,[GivenName]
	,[OtherNames]
	,[FamilyName]
	,[PrimaryAddress]
	,[State]
	,[Postcode]
	,[Country]
	,[PrimaryPhone]
	,[PrimaryEmail]
	,[ApplicationType]
	,[ApplicationReference]
	,[ApplicationOwner]
	,[EnteredUser]
	,[SponsoredOrganisationId]
	,[SponsoredOrganisationName]
	,[SponsoredContactId]
	,[SponsoredContactName]
	,[StatusModifiedUser]
	,[PreferredTestLocationState]
	,[PreferredTestLocationCity]
	,[AutoCreated]
FROM [ApplicationLatest] a
--FROM [ApplicationHistory] a
--where [RowStatus] = 'Latest'