ALTER VIEW [dbo].[CredentialRequests] AS
SELECT
	[CredentialRequestId]
	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[PersonId]
	,[NAATINumber]
	,[PractitionerNumber]
	,[Title]
	,[GivenName]
	,[OtherNames]
	,[FamilyName]
	,[PrimaryAddress]
	,[State]
	,[Postcode]
	,[Country]
	,[PrimaryPhone]
	,[PrimaryEmail]
	,[ApplicationId]
	,[ApplicationType]
	,[ApplicationReference]
	,[ApplicationOwner]
	,[CredentialTypeInternalName]
	,[CredentialTypeExternalName]
	,[Certification]
	,[Language1]
	,[Language1Code]
	,[Language1Group]
	,[Language2]
	,[Language2Code]
	,[Language2Group]
	,[DirectionDisplayName]
	,[ModifiedDate]	
	,[StatusDateModified]
	,[StatusModifiedUser]
	,[Status]
	,[CredentialId]
	,[LinkedCredentialRequestId]
	,[LinkedCredentialRequestReason]
	,[AutoCreated]
FROM [CredentialRequestsLatest]

--SELECT
--	[CredentialRequestId]
--	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
--	,[PersonId]
--	,[NAATINumber]
--	,[PractitionerNumber]
--	,[Title]
--	,[GivenName]
--	,[OtherNames]
--	,[FamilyName]
--	,[PrimaryAddress]
--	,[State]
--	,[Postcode]
--	,[Country]
--	,[PrimaryPhone]
--	,[PrimaryEmail]
--	,[ApplicationId]
--	,[ApplicationType]
--	,[ApplicationReference]
--	,[ApplicationOwner]
--	,[CredentialTypeInternalName]
--	,[CredentialTypeExternalName]
--	,[Certification]
--	,[Language1]
--	,[Language1Code]
--	,[Language1Group]
--	,[Language2]
--	,[Language2Code]
--	,[Language2Group]
--	,[DirectionDisplayName]
--	,[ModifiedDate]	
--	,[StatusDateModified]
--	,[StatusModifiedUser]
--	,[Status]
--	,[CredentialId]
--	,[LinkedCredentialRequestId]
--	,[LinkedCredentialRequestReason]
--	,[AutoCreated]
--FROM [CredentialRequestsHistory] c
--where [RowStatus] = 'Latest'