ALTER VIEW [dbo].[Credentials] AS
SELECT
	[CredentialId]
	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[PersonId]
	,[NAATINumber]
	,[PractitionerNumber]
	,[Title]
	,[GivenName]
	,[OtherNames]
	,[FamilyName]
	,[PrimaryAddress]
	,[State]
	,[Postcode]
	,[Country]
	,[PrimaryPhone]
	,[PrimaryEmail]
	,[CredentialTypeInternalName]
	,[CredentialTypeExternalName]
	,[Language1]
	,[Language1Code]
	,[Language1Group]
	,[Language2]
	,[Language2Code]
	,[Language2Group]
	,[Certification]
	,[DirectionDisplayName]
	,[StartDate]
	,[ExpiryDate]
	,[ModifiedDate]
	,[TerminationDate]
	,[Status]
	,[ShowInOnlineDirectory]	
FROM [CredentialsHistory] c
where [RowStatus] = 'Latest'