ALTER VIEW [dbo].[ExaminerJob] AS
SELECT
	[JobExaminerId]
	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[TestSittingId]
	,[JobId]
	,[ApplicationTypeId]
	,[ApplicationType]
	,[ExaminerCustomerNumber]
	,[CredentialTypeId]
	,[CredentialType]
	,[SkillId]
	,[Skill]
	,[DateAllocated]
	,[ReceivedDate]
	,[DueDate]
	,[ExaminerCost]
	,[ProductSpecificationId]
	,[ProductSpecificationCode]
	,[ProductSpecificationDescription]
	,[GLCodeId]
	,[GLCode]
	,[ExaminerPayRollStatusId]
	,[ExaminerPayRollStatus]	
	,[PayRollModifiedDate]	
	,[PayRollModifiedUser]	
	,[PayRollAccountingReference]		
FROM [ExaminerJobHistory] c
where [RowStatus] = 'Latest'
