ALTER VIEW [dbo].[MarkRubric] AS
SELECT
    [TestResultId]
    ,[TestComponentId]
    ,[JobExaminerId]
    ,[RubricAssessementCriterionResultId]
	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[TestSittingId]
	,[TestSessionId]
	,[PersonId]
	,[CustomerNo]
	,[CandidateName]
	,[PaidReview]
	,[Supplementary]
	,[TestTaskTypeLabel]
	,[TestTaskTypeName]
	,[TestTaskLabel]
	,[TestTaskName]
	,[TestTaskNumber]
	,[MarkType]
	,[ResultType]
	,[ExaminerCustomerNo]
	,[ExaminerName]
	,[ExaminerType]
	,[Cost]
	,[ExaminerSubmittedDate]
	,[IncludeMarks]
	,[WasAttempted]
	,[Successful]
	,[RubricCompetencyLabel]
	,[RubricCompetencyName]
	,[RubricCriterionName]
	,[RubricCriterionLabel]
	,[RubricSelectedBandLabel]
	,[RubricSelectedBandLevel]	
FROM [MarkRubricLatest] m	
--FROM [MarkRubricHistory] m	
--where [RowStatus] = 'Latest'