ALTER VIEW [dbo].[Person] AS
SELECT
    [PersonId]
    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[NAATINumber]
	,[PractitionerNumber]
    ,[GivenName]
    ,[OtherNames]
    ,[FamilyName]
    ,[Title]
    ,[Gender]
    ,[DateOfBirth]
    ,[CountryOfBirth]
    ,[PrimaryAddress]
    ,[Suburb]
	,[State]
	,[Postcode]
    ,[Country]
    ,[PrimaryEmail]
    ,[PrimaryPhone]
	,[SecondaryAddress]
	,[SecondaryPhone]
	,[SecondaryEmail]
	,[DoNotSendCorrespondence]
	,[EthicalCompetency]
	,[InterculturalCompetency]
	,[KnowledgeTest]
	,[RolePlayerRating]
	,[RolePlayerSenior]	
    ,[Deceased]
FROM [PersonHistory] p
where [RowStatus] = 'Latest'
