ALTER VIEW [dbo].[TestSittingTestMaterial] AS
SELECT
	[TestSittingTestMaterialId]
    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
	,[TestSittingId]
	,[TestSessionId]
	,[TestMaterialId]
	,[SatDate]
	,[TestLocationName]
	,[TestLocationState]
	,[CredentialRequestId]
	,[CredentialApplicationId]
	,[PersonId]
	,[CustomerNo]
	,[CandidateName]
	,[Language1]
	,[Language1Code]
	,[Language1Group]
	,[Language2]
	,[Language2Code]
	,[Language2Group]
	,[Skill]
	,[TestMaterialTitle]
	,[TestTaskTypeLabel]
	,[TestTaskTypeName]
	,[TestTaskLabel]
	,[TestTaskName]	
FROM [TestSittingTestMaterialHistory] tr
where [RowStatus] = 'Latest'