//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.Reports._20180228_UpdateTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.Reports._20180228_UpdateTests.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[ReportingSnapshot_TestSessions]
        ///AS
        ///BEGIN
        ///	DECLARE 
        ///		@testSessionAllocated INT = 18,
        ///		@testSessionAccepted INT = 19
        ///
        ///	SELECT 
        ///		CASE WHEN [Source].[TestSessionCredentialRequestId] IS NULL THEN [TestSessions].[TestSessionCredentialRequestId] ELSE [Source].[TestSessionCredentialRequestId] END AS [TestSessionCredentialRequestId]
        ///		,CASE WHEN [Source].[TestSessionId] IS NULL THEN [TestSessions].[TestSessionId] ELSE [Source].[TestSessionId] END AS [TestSessionId]
        ///		,CASE WHEN [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTestSessionsProcedure {
            get {
                return ResourceManager.GetString("CreateTestSessionsProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[TestSessions] AS
        ///SELECT
        ///	[TestSessionCredentialRequestId]
        ///	,[TestSessionId]
        ///	,[CredentialRequestId]
        ///	,[TestSessionName]
        ///	,[TestLocationState]
        ///	,[TestLocationCountry]
        ///	,[TestLocationName]
        ///	,[VenueName]
        ///	,[VenueAddress]
        ///	,[TestDate]
        ///	,[TestStartTime]
        ///	,[TestArrivalTime]
        ///	,[TestEndTime]
        ///	,[ApplicationType]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[TestSessionCompleted]
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[Title]
        ///	,[GivenName]
        ///	,[OtherNames]
        ///	,[FamilyN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTestSessionsView {
            get {
                return ResourceManager.GetString("CreateTestSessionsView", resourceCulture);
            }
        }
    }
}
