BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ApplicationHistory ADD
	AutoCreated bit NULL
GO
ALTER TABLE dbo.ApplicationHistory SET (LOCK_ESCALATION = TABLE)
GO
GO
ALTER TABLE dbo.CredentialRequestsHistory ADD
	AutoCreated bit NULL
GO
ALTER TABLE dbo.CredentialRequestsHistory SET (LOCK_ESCALATION = TABLE)
GO
COMMIT