BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tblCredentialQrCode ADD
	InactiveDate date NULL,
	ModifiedBy int NOT NULL CONSTRAINT DF_tblCredentialQrCode_ModifiedBy DEFAULT 0
GO
ALTER TABLE dbo.tblCredentialQrCode SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
