using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FluentMigrator.Runner.Extensions;

namespace F1Solutions.Naati.Common.Migrations.NAATI._20200115_AddAccreditationTemplates
{
    [NaatiMigration(202001151530)]
    public class AddAccreditationTemplates : NaatiMigration
    {
        public override void Up()
        {
            //skill types
            Insert.IntoTable("tblSkillType").Row(new { SkillTypeId = 33, Name = "Para-ProfessionalInterpreter", DisplayName = "Para-professional Interpreter", ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkillType").Row(new { SkillTypeId = 34, Name = "Professional Interpreter", DisplayName = "Professional Interpreter", ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkillType").Row(new { SkillTypeId = 35, Name = "Professional Translator", DisplayName = "Professional Translator", ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            
            Execute.Sql(Sql.AddAccreditaionTemplatesScript);

            //skills
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1347, SkillTypeId = 35, Language1Id = 3, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1348, SkillTypeId = 35, Language1Id = 3, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1349, SkillTypeId = 35, Language1Id = 4, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1350, SkillTypeId = 35, Language1Id = 4, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1351, SkillTypeId = 35, Language1Id = 7, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1352, SkillTypeId = 35, Language1Id = 7, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1353, SkillTypeId = 35, Language1Id = 13, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1354, SkillTypeId = 35, Language1Id = 13, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1355, SkillTypeId = 35, Language1Id = 16, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1356, SkillTypeId = 35, Language1Id = 16, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1357, SkillTypeId = 35, Language1Id = 17, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1358, SkillTypeId = 35, Language1Id = 17, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1359, SkillTypeId = 35, Language1Id = 18, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1360, SkillTypeId = 35, Language1Id = 18, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1361, SkillTypeId = 35, Language1Id = 24, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1362, SkillTypeId = 35, Language1Id = 24, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1363, SkillTypeId = 35, Language1Id = 27, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1364, SkillTypeId = 35, Language1Id = 27, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1365, SkillTypeId = 35, Language1Id = 28, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1366, SkillTypeId = 35, Language1Id = 28, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1367, SkillTypeId = 35, Language1Id = 29, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1368, SkillTypeId = 35, Language1Id = 29, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1369, SkillTypeId = 35, Language1Id = 30, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1370, SkillTypeId = 35, Language1Id = 30, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1371, SkillTypeId = 35, Language1Id = 36, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1372, SkillTypeId = 35, Language1Id = 36, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1373, SkillTypeId = 35, Language1Id = 45, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1374, SkillTypeId = 35, Language1Id = 45, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1375, SkillTypeId = 35, Language1Id = 46, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1376, SkillTypeId = 35, Language1Id = 46, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1377, SkillTypeId = 35, Language1Id = 48, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1378, SkillTypeId = 35, Language1Id = 48, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1379, SkillTypeId = 35, Language1Id = 59, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1380, SkillTypeId = 35, Language1Id = 59, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1381, SkillTypeId = 35, Language1Id = 61, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1382, SkillTypeId = 35, Language1Id = 61, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1383, SkillTypeId = 35, Language1Id = 71, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1384, SkillTypeId = 35, Language1Id = 71, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1385, SkillTypeId = 35, Language1Id = 76, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1386, SkillTypeId = 35, Language1Id = 76, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1387, SkillTypeId = 35, Language1Id = 78, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1388, SkillTypeId = 35, Language1Id = 78, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1389, SkillTypeId = 35, Language1Id = 81, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1390, SkillTypeId = 35, Language1Id = 81, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1391, SkillTypeId = 35, Language1Id = 82, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1392, SkillTypeId = 35, Language1Id = 82, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1393, SkillTypeId = 35, Language1Id = 84, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1394, SkillTypeId = 35, Language1Id = 84, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1395, SkillTypeId = 35, Language1Id = 91, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1396, SkillTypeId = 35, Language1Id = 91, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1397, SkillTypeId = 35, Language1Id = 98, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1398, SkillTypeId = 35, Language1Id = 98, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1399, SkillTypeId = 35, Language1Id = 104, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1400, SkillTypeId = 35, Language1Id = 104, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1401, SkillTypeId = 35, Language1Id = 112, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1402, SkillTypeId = 35, Language1Id = 112, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1403, SkillTypeId = 35, Language1Id = 113, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1404, SkillTypeId = 35, Language1Id = 113, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1405, SkillTypeId = 35, Language1Id = 115, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1406, SkillTypeId = 35, Language1Id = 115, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1407, SkillTypeId = 35, Language1Id = 1410, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1408, SkillTypeId = 35, Language1Id = 1410, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1409, SkillTypeId = 35, Language1Id = 128, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1410, SkillTypeId = 35, Language1Id = 128, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1411, SkillTypeId = 35, Language1Id = 134, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1412, SkillTypeId = 35, Language1Id = 134, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1413, SkillTypeId = 35, Language1Id = 137, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1414, SkillTypeId = 35, Language1Id = 137, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1415, SkillTypeId = 35, Language1Id = 138, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1416, SkillTypeId = 35, Language1Id = 138, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1417, SkillTypeId = 35, Language1Id = 141, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1418, SkillTypeId = 35, Language1Id = 141, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1419, SkillTypeId = 35, Language1Id = 143, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1420, SkillTypeId = 35, Language1Id = 143, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1421, SkillTypeId = 35, Language1Id = 145, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1422, SkillTypeId = 35, Language1Id = 145, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1423, SkillTypeId = 35, Language1Id = 148, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1424, SkillTypeId = 35, Language1Id = 148, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1425, SkillTypeId = 35, Language1Id = 151, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1426, SkillTypeId = 35, Language1Id = 151, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1427, SkillTypeId = 35, Language1Id = 152, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1428, SkillTypeId = 35, Language1Id = 152, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1429, SkillTypeId = 35, Language1Id = 154, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1430, SkillTypeId = 35, Language1Id = 154, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1431, SkillTypeId = 35, Language1Id = 155, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1432, SkillTypeId = 35, Language1Id = 155, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1433, SkillTypeId = 35, Language1Id = 159, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1434, SkillTypeId = 35, Language1Id = 159, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1435, SkillTypeId = 35, Language1Id = 162, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1436, SkillTypeId = 35, Language1Id = 162, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1437, SkillTypeId = 35, Language1Id = 168, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1438, SkillTypeId = 35, Language1Id = 168, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1439, SkillTypeId = 35, Language1Id = 174, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1440, SkillTypeId = 35, Language1Id = 174, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1441, SkillTypeId = 35, Language1Id = 176, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1442, SkillTypeId = 35, Language1Id = 176, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1443, SkillTypeId = 35, Language1Id = 178, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1444, SkillTypeId = 35, Language1Id = 178, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1445, SkillTypeId = 35, Language1Id = 179, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1446, SkillTypeId = 35, Language1Id = 179, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1447, SkillTypeId = 35, Language1Id = 181, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1448, SkillTypeId = 35, Language1Id = 181, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1449, SkillTypeId = 35, Language1Id = 996, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1450, SkillTypeId = 35, Language1Id = 996, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1451, SkillTypeId = 35, Language1Id = 42, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1452, SkillTypeId = 35, Language1Id = 42, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1453, SkillTypeId = 35, Language1Id = 1200, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1454, SkillTypeId = 35, Language1Id = 1200, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1455, SkillTypeId = 35, Language1Id = 146, Language2Id = 40, DirectionTypeId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1456, SkillTypeId = 35, Language1Id = 146, Language2Id = 40, DirectionTypeId = 2, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1457, SkillTypeId = 34, Language1Id = 3, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1458, SkillTypeId = 34, Language1Id = 4, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1459, SkillTypeId = 34, Language1Id = 7, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1460, SkillTypeId = 34, Language1Id = 13, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1461, SkillTypeId = 34, Language1Id = 16, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1462, SkillTypeId = 34, Language1Id = 17, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1463, SkillTypeId = 34, Language1Id = 18, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1464, SkillTypeId = 34, Language1Id = 20, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1465, SkillTypeId = 34, Language1Id = 27, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1466, SkillTypeId = 34, Language1Id = 28, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1467, SkillTypeId = 34, Language1Id = 29, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1468, SkillTypeId = 34, Language1Id = 30, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1469, SkillTypeId = 34, Language1Id = 36, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1470, SkillTypeId = 34, Language1Id = 45, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1471, SkillTypeId = 34, Language1Id = 46, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1472, SkillTypeId = 34, Language1Id = 48, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1473, SkillTypeId = 34, Language1Id = 59, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1474, SkillTypeId = 34, Language1Id = 61, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1475, SkillTypeId = 34, Language1Id = 1195, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1476, SkillTypeId = 34, Language1Id = 71, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1477, SkillTypeId = 34, Language1Id = 76, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1478, SkillTypeId = 34, Language1Id = 81, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1479, SkillTypeId = 34, Language1Id = 82, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1480, SkillTypeId = 34, Language1Id = 84, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1481, SkillTypeId = 34, Language1Id = 91, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1482, SkillTypeId = 34, Language1Id = 98, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1483, SkillTypeId = 34, Language1Id = 104, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1484, SkillTypeId = 34, Language1Id = 112, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1485, SkillTypeId = 34, Language1Id = 113, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1486, SkillTypeId = 34, Language1Id = 115, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1487, SkillTypeId = 34, Language1Id = 116, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1488, SkillTypeId = 34, Language1Id = 1410, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1489, SkillTypeId = 34, Language1Id = 1395, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1490, SkillTypeId = 34, Language1Id = 128, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1491, SkillTypeId = 34, Language1Id = 134, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1492, SkillTypeId = 34, Language1Id = 137, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1493, SkillTypeId = 34, Language1Id = 138, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1494, SkillTypeId = 34, Language1Id = 141, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1495, SkillTypeId = 34, Language1Id = 143, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1496, SkillTypeId = 34, Language1Id = 145, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1497, SkillTypeId = 34, Language1Id = 148, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1498, SkillTypeId = 34, Language1Id = 151, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1499, SkillTypeId = 34, Language1Id = 152, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1500, SkillTypeId = 34, Language1Id = 154, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1501, SkillTypeId = 34, Language1Id = 155, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1502, SkillTypeId = 34, Language1Id = 159, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1503, SkillTypeId = 34, Language1Id = 162, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1504, SkillTypeId = 34, Language1Id = 168, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1505, SkillTypeId = 34, Language1Id = 174, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1506, SkillTypeId = 34, Language1Id = 176, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1507, SkillTypeId = 34, Language1Id = 178, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1508, SkillTypeId = 34, Language1Id = 179, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1509, SkillTypeId = 34, Language1Id = 181, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1510, SkillTypeId = 34, Language1Id = 146, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1511, SkillTypeId = 33, Language1Id = 3, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1512, SkillTypeId = 33, Language1Id = 4, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1513, SkillTypeId = 33, Language1Id = 7, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1514, SkillTypeId = 33, Language1Id = 996, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1515, SkillTypeId = 33, Language1Id = 9, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1516, SkillTypeId = 33, Language1Id = 13, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1517, SkillTypeId = 33, Language1Id = 16, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1518, SkillTypeId = 33, Language1Id = 17, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1519, SkillTypeId = 33, Language1Id = 18, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1520, SkillTypeId = 33, Language1Id = 20, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1521, SkillTypeId = 33, Language1Id = 1545, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1522, SkillTypeId = 33, Language1Id = 27, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1523, SkillTypeId = 33, Language1Id = 28, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1524, SkillTypeId = 33, Language1Id = 29, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1525, SkillTypeId = 33, Language1Id = 30, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1526, SkillTypeId = 33, Language1Id = 997, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1527, SkillTypeId = 33, Language1Id = 36, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1528, SkillTypeId = 33, Language1Id = 795, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1529, SkillTypeId = 33, Language1Id = 45, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1530, SkillTypeId = 33, Language1Id = 46, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1531, SkillTypeId = 33, Language1Id = 48, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1532, SkillTypeId = 33, Language1Id = 59, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1533, SkillTypeId = 33, Language1Id = 61, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1534, SkillTypeId = 33, Language1Id = 1195, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1535, SkillTypeId = 33, Language1Id = 71, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1536, SkillTypeId = 33, Language1Id = 72, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1537, SkillTypeId = 33, Language1Id = 76, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1538, SkillTypeId = 33, Language1Id = 78, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1539, SkillTypeId = 33, Language1Id = 81, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1540, SkillTypeId = 33, Language1Id = 82, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1541, SkillTypeId = 33, Language1Id = 84, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1542, SkillTypeId = 33, Language1Id = 91, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1543, SkillTypeId = 33, Language1Id = 93, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1544, SkillTypeId = 33, Language1Id = 98, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1545, SkillTypeId = 33, Language1Id = 99, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1546, SkillTypeId = 33, Language1Id = 102, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1547, SkillTypeId = 33, Language1Id = 104, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1548, SkillTypeId = 33, Language1Id = 112, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1549, SkillTypeId = 33, Language1Id = 113, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1550, SkillTypeId = 33, Language1Id = 115, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1551, SkillTypeId = 33, Language1Id = 116, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1552, SkillTypeId = 33, Language1Id = 1505, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1553, SkillTypeId = 33, Language1Id = 1203, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1554, SkillTypeId = 33, Language1Id = 496, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1555, SkillTypeId = 33, Language1Id = 1410, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1556, SkillTypeId = 33, Language1Id = 1395, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1557, SkillTypeId = 33, Language1Id = 128, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1558, SkillTypeId = 33, Language1Id = 998, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1559, SkillTypeId = 33, Language1Id = 999, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1560, SkillTypeId = 33, Language1Id = 142, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1561, SkillTypeId = 33, Language1Id = 134, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1562, SkillTypeId = 33, Language1Id = 137, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1563, SkillTypeId = 33, Language1Id = 138, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1564, SkillTypeId = 33, Language1Id = 141, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1565, SkillTypeId = 33, Language1Id = 1551, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1566, SkillTypeId = 33, Language1Id = 143, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1567, SkillTypeId = 33, Language1Id = 145, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1568, SkillTypeId = 33, Language1Id = 146, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1569, SkillTypeId = 33, Language1Id = 148, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1570, SkillTypeId = 33, Language1Id = 1412, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1571, SkillTypeId = 33, Language1Id = 151, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1572, SkillTypeId = 33, Language1Id = 152, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1573, SkillTypeId = 33, Language1Id = 154, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1574, SkillTypeId = 33, Language1Id = 103, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1575, SkillTypeId = 33, Language1Id = 1546, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1576, SkillTypeId = 33, Language1Id = 155, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1577, SkillTypeId = 33, Language1Id = 1000, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1578, SkillTypeId = 33, Language1Id = 159, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1579, SkillTypeId = 33, Language1Id = 162, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1580, SkillTypeId = 33, Language1Id = 166, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1581, SkillTypeId = 33, Language1Id = 168, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1582, SkillTypeId = 33, Language1Id = 170, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1583, SkillTypeId = 33, Language1Id = 174, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1584, SkillTypeId = 33, Language1Id = 176, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1585, SkillTypeId = 33, Language1Id = 178, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1586, SkillTypeId = 33, Language1Id = 179, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1587, SkillTypeId = 33, Language1Id = 181, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1588, SkillTypeId = 33, Language1Id = 1425, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1589, SkillTypeId = 33, Language1Id = 1415, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1590, SkillTypeId = 33, Language1Id = 996, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();
            Insert.IntoTable("tblSkill").Row(new { SkillId = 1591, SkillTypeId = 33, Language1Id = 1200, Language2Id = 40, DirectionTypeId = 3, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40 }).WithIdentityInsert();

            //credentialApplicationType
            Insert.IntoTable("tblCredentialApplicationType").Row(new {CredentialApplicationTypeId = 16, Name = "Accreditation", DisplayName = "Accreditation", Online = 0, RequiresChecking = 1, RequiresAssessment = 1, BackOffice = 1, PendingAllowed = 1, AssessmentReviewAllowed = 0, DisplayBills = 1, CredentialApplicationTypeCategoryId = 1, ModifiedByNaati = 0, ModifiedDate = DateTime.Now, ModifiedUser = 40, AllowMultiple = 0 }).WithIdentityInsert();
            
            //SkillApplicationTypes
            for (int i = 1347; i <= 1591; i++)
            {
                Insert.IntoTable("tblSkillApplicationType").Row(new
                {
                    SkillId = i,
                    CredentialApplicationTypeId = 16,
                    ModifiedByNaati = false,
                    ModifiedDate = DateTime.Now,
                    ModifiedUser = 40
                });
            }
        }
    }
}
