//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CredentialRequestType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CredentialRequestType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naati.Resources.CredentialRequestType", typeof(CredentialRequestType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential RequestType 1.
        /// </summary>
        internal static string CredentialRequestType1 {
            get {
                return ResourceManager.GetString("CredentialRequestType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential RequestType 2.
        /// </summary>
        internal static string CredentialRequestType2 {
            get {
                return ResourceManager.GetString("CredentialRequestType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentia lRequestType 3.
        /// </summary>
        internal static string CredentialRequestType3 {
            get {
                return ResourceManager.GetString("CredentialRequestType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential RequestType 4.
        /// </summary>
        internal static string CredentialRequestType4 {
            get {
                return ResourceManager.GetString("CredentialRequestType4", resourceCulture);
            }
        }
    }
}
