//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CredentialRequestSummary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CredentialRequestSummary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naati.Resources.CredentialRequestSummary", typeof(CredentialRequestSummary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Test Session.
        /// </summary>
        internal static string AcceptTestSessionActionLabel {
            get {
                return ResourceManager.GetString("AcceptTestSessionActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate Test Session.
        /// </summary>
        internal static string AllocateTestSession {
            get {
                return ResourceManager.GetString("AllocateTestSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate Test Session.
        /// </summary>
        internal static string AllocateTestSessionActionLabel {
            get {
                return ResourceManager.GetString("AllocateTestSessionActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant(s).
        /// </summary>
        internal static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Submitted Date.
        /// </summary>
        internal static string ApplicationSubmittedDate {
            get {
                return ResourceManager.GetString("ApplicationSubmittedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Type.
        /// </summary>
        internal static string ApplicationType {
            get {
                return ResourceManager.GetString("ApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available seats: {0}.
        /// </summary>
        internal static string AvailableSeats {
            get {
                return ResourceManager.GetString("AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Request Status.
        /// </summary>
        internal static string CredentialRequestStatus {
            get {
                return ResourceManager.GetString("CredentialRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Request Type.
        /// </summary>
        internal static string CredentialRequestType {
            get {
                return ResourceManager.GetString("CredentialRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type.
        /// </summary>
        internal static string CredentialType {
            get {
                return ResourceManager.GetString("CredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since Submission.
        /// </summary>
        internal static string DaysSinceSubmission {
            get {
                return ResourceManager.GetString("DaysSinceSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of the test session in minutes..
        /// </summary>
        internal static string DurationHelp {
            get {
                return ResourceManager.GetString("DurationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest application submitted on.
        /// </summary>
        internal static string EarliestApplicationSubmittedOn {
            get {
                return ResourceManager.GetString("EarliestApplicationSubmittedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Applicants.
        /// </summary>
        internal static string ExistingApplicants {
            get {
                return ResourceManager.GetString("ExistingApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Invite for Testing.
        /// </summary>
        internal static string FutureInviteForTesting {
            get {
                return ResourceManager.GetString("FutureInviteForTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future View Details.
        /// </summary>
        internal static string FutureViewDetails {
            get {
                return ResourceManager.GetString("FutureViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite for Testing.
        /// </summary>
        internal static string InviteForTestingActionLabel {
            get {
                return ResourceManager.GetString("InviteForTestingActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last application submitted on.
        /// </summary>
        internal static string LastApplicationSubmittedOn {
            get {
                return ResourceManager.GetString("LastApplicationSubmittedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Applicants.
        /// </summary>
        internal static string NewApplicants {
            get {
                return ResourceManager.GetString("NewApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No actions available.
        /// </summary>
        internal static string NoActionsAvailable {
            get {
                return ResourceManager.GetString("NoActionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Applicants.
        /// </summary>
        internal static string NumberOfApplicants {
            get {
                return ResourceManager.GetString("NumberOfApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a new one.
        /// </summary>
        internal static string OrCreateANewOne {
            get {
                return ResourceManager.GetString("OrCreateANewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Test Location.
        /// </summary>
        internal static string PreferredTestLocation {
            get {
                return ResourceManager.GetString("PreferredTestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation Time.
        /// </summary>
        internal static string PreparationTime {
            get {
                return ResourceManager.GetString("PreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in minutes prior to the test start time that candidates should arrive at the venue..
        /// </summary>
        internal static string PreparationTimeHelp {
            get {
                return ResourceManager.GetString("PreparationTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Invoice.
        /// </summary>
        internal static string PreviewInvoice {
            get {
                return ResourceManager.GetString("PreviewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        internal static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a test session.
        /// </summary>
        internal static string SelectATestSession {
            get {
                return ResourceManager.GetString("SelectATestSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Duration.
        /// </summary>
        internal static string SessionDuration {
            get {
                return ResourceManager.GetString("SessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Name.
        /// </summary>
        internal static string SessionName {
            get {
                return ResourceManager.GetString("SessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the Skill for these applicants do not match the allowed Skills for this Test Session.
        /// </summary>
        internal static string SkillNotMatched {
            get {
                return ResourceManager.GetString("SkillNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Action.
        /// </summary>
        internal static string TakeAction {
            get {
                return ResourceManager.GetString("TakeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        internal static string TestDate {
            get {
                return ResourceManager.GetString("TestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Location:.
        /// </summary>
        internal static string TestLocation {
            get {
                return ResourceManager.GetString("TestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Session.
        /// </summary>
        internal static string TestSession {
            get {
                return ResourceManager.GetString("TestSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Time.
        /// </summary>
        internal static string TestTime {
            get {
                return ResourceManager.GetString("TestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        internal static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string VenueCapacity {
            get {
                return ResourceManager.GetString("VenueCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue is overcrowded.
        /// </summary>
        internal static string VenueOvercrowded {
            get {
                return ResourceManager.GetString("VenueOvercrowded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Email &amp; Attachments.
        /// </summary>
        internal static string ViewEmailAttachments {
            get {
                return ResourceManager.GetString("ViewEmailAttachments", resourceCulture);
            }
        }
    }
}
