//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logbook {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logbook() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naati.Resources.Logbook", typeof(Logbook).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Reference.
        /// </summary>
        public static string ApplicationReference {
            get {
                return ResourceManager.GetString("ApplicationReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Activity.
        /// </summary>
        public static string AttachActivity {
            get {
                return ResourceManager.GetString("AttachActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being Assessed.
        /// </summary>
        public static string BeingAssessed {
            get {
                return ResourceManager.GetString("BeingAssessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Completed.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible.
        /// </summary>
        public static string EligibleForExisiting {
            get {
                return ResourceManager.GetString("EligibleForExisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible.
        /// </summary>
        public static string EligibleForNew {
            get {
                return ResourceManager.GetString("EligibleForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - {2}.
        /// </summary>
        public static string LogbookPdHeadingFormat {
            get {
                return ResourceManager.GetString("LogbookPdHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&quot;_blank&quot; href=&quot;{0}&quot; class=&quot;text-info&quot;&gt;Click here&lt;/a&gt; to see the Professional Development (PD) catalogue which describes the types of activities a practitioner can claim..
        /// </summary>
        public static string ProfessionalDevelopmentCatalogue {
            get {
                return ResourceManager.GetString("ProfessionalDevelopmentCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recertification Points.
        /// </summary>
        public static string RecertificationPoints {
            get {
                return ResourceManager.GetString("RecertificationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view submitted activites, select one of the following applications..
        /// </summary>
        public static string SelectSubmittedLogbookHelp {
            get {
                return ResourceManager.GetString("SelectSubmittedLogbookHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Submitted Logbook.
        /// </summary>
        public static string SelectSubmittedLogbookTitle {
            get {
                return ResourceManager.GetString("SelectSubmittedLogbookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Current.
        /// </summary>
        public static string ShowCurrent {
            get {
                return ResourceManager.GetString("ShowCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing current logbook.
        /// </summary>
        public static string ShowingCurrent {
            get {
                return ResourceManager.GetString("ShowingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing logbook activities submitted with application APP{0} on {1}.
        /// </summary>
        public static string ShowingSubmitted {
            get {
                return ResourceManager.GetString("ShowingSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Submitted.
        /// </summary>
        public static string ShowSubmitted {
            get {
                return ResourceManager.GetString("ShowSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Date.
        /// </summary>
        public static string SubmittedDate {
            get {
                return ResourceManager.GetString("SubmittedDate", resourceCulture);
            }
        }
    }
}
