//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RolePlayer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RolePlayer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naati.Resources.RolePlayer", typeof(RolePlayer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string RolePlayerMarkAsAccepted {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehearsed.
        /// </summary>
        public static string RolePlayerMarkAsAttendedRehearsal {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsAttendedRehearsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended.
        /// </summary>
        public static string RolePlayerMarkAsAttendedTest {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsAttendedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Show.
        /// </summary>
        public static string RolePlayerMarkAsNoShow {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsNoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string RolePlayerMarkAsPending {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RolePlayerMarkAsRejected {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string RolePlayerMarkAsRemoved {
            get {
                return ResourceManager.GetString("RolePlayerMarkAsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-player status for Test Session {0} has been changed from {1} to {2}.
        /// </summary>
        public static string RolePlayerStatusUpdated {
            get {
                return ResourceManager.GetString("RolePlayerStatusUpdated", resourceCulture);
            }
        }
    }
}
