//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naati.Resources.SystemResources", typeof(SystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        internal static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure authorisation was successful.
        /// </summary>
        internal static string AzureAuthSuccess {
            get {
                return ResourceManager.GetString("AzureAuthSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Batch Report Settings.
        /// </summary>
        internal static string ChangeGeneralBatchReportSettingsSystemValues {
            get {
                return ResourceManager.GetString("ChangeGeneralBatchReportSettingsSystemValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Process File Deletes Past Expiry System Values.
        /// </summary>
        internal static string ChangeProcessFileDeletesPastExpirySystemValues {
            get {
                return ResourceManager.GetString("ChangeProcessFileDeletesPastExpirySystemValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Please try the operation again. If the error persists, please contact F1 Solutions Support..
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Message of the Day here -.
        /// </summary>
        internal static string MessageOfTheDayLabel {
            get {
                return ResourceManager.GetString("MessageOfTheDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myNAATI Message and Accessibility.
        /// </summary>
        internal static string Motd {
            get {
                return ResourceManager.GetString("Motd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Account.
        /// </summary>
        internal static string PaymentAccount {
            get {
                return ResourceManager.GetString("PaymentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payments for invoices will be recorded against this account on Wiise.  Note that this should be the Clearing Account..
        /// </summary>
        internal static string PaymentAccountHelp {
            get {
                return ResourceManager.GetString("PaymentAccountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process File Deletes Past Expiry Date Batch Size.
        /// </summary>
        internal static string ProcessFileDeletesPastExpiryDateBatchSizeLabel {
            get {
                return ResourceManager.GetString("ProcessFileDeletesPastExpiryDateBatchSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process File Deletes Past Expiry Date Include Previously Queued.
        /// </summary>
        internal static string ProcessFileDeletesPastExpiryDateIncludePreviouslyQueuedLabel {
            get {
                return ResourceManager.GetString("ProcessFileDeletesPastExpiryDateIncludePreviouslyQueuedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process File Deletes Past Expiry Date Retention Days.
        /// </summary>
        internal static string ProcessFileDeletesPastExpiryDateRetentionDaysLabel {
            get {
                return ResourceManager.GetString("ProcessFileDeletesPastExpiryDateRetentionDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice Branding.
        /// </summary>
        internal static string SalesInvoiceBranding {
            get {
                return ResourceManager.GetString("SalesInvoiceBranding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Branding has been discontinued in Wiise..
        /// </summary>
        internal static string SalesInvoiceBrandingHelp {
            get {
                return ResourceManager.GetString("SalesInvoiceBrandingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you aren&apos;t authorised to access that screen..
        /// </summary>
        internal static string ScreenAccessDenied {
            get {
                return ResourceManager.GetString("ScreenAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Successful Batch Report Email.
        /// </summary>
        internal static string SendSuccessfulBatchReportLabel {
            get {
                return ResourceManager.GetString("SendSuccessfulBatchReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Delete Report.
        /// </summary>
        internal static string ShowFileDeleteReport {
            get {
                return ResourceManager.GetString("ShowFileDeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Inactive.
        /// </summary>
        internal static string ShowInactive {
            get {
                return ResourceManager.GetString("ShowInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In To Azure.
        /// </summary>
        internal static string SignInToAzure {
            get {
                return ResourceManager.GetString("SignInToAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In To Wiise.
        /// </summary>
        internal static string SignInToWiise {
            get {
                return ResourceManager.GetString("SignInToWiise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Specifications.
        /// </summary>
        internal static string TestSpecifications {
            get {
                return ResourceManager.GetString("TestSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Message Of The Day.
        /// </summary>
        internal static string TurnOnMessageOfTheDay {
            get {
                return ResourceManager.GetString("TurnOnMessageOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable myNaati Logon.
        /// </summary>
        internal static string TurnOnMyNaatiAvailable {
            get {
                return ResourceManager.GetString("TurnOnMyNaatiAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to upload this spreadsheet? This will create the test specification data as per the selected spreadsheet..
        /// </summary>
        internal static string UploadConfirmMessage {
            get {
                return ResourceManager.GetString("UploadConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Succeeded.
        /// </summary>
        internal static string VerificationSucceeded {
            get {
                return ResourceManager.GetString("VerificationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiise.
        /// </summary>
        internal static string Wiise {
            get {
                return ResourceManager.GetString("Wiise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiise authorisation was successful.
        /// </summary>
        internal static string WiiseAuthSuccess {
            get {
                return ResourceManager.GetString("WiiseAuthSuccess", resourceCulture);
            }
        }
    }
}
