//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naati.Resources.Test", typeof(Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Expiry Date.
        /// </summary>
        public static string AccreditationExpiryDate {
            get {
                return ResourceManager.GetString("AccreditationExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredit for.
        /// </summary>
        public static string AccreditFor {
            get {
                return ResourceManager.GetString("AccreditFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Examiners.
        /// </summary>
        public static string AddExaminer {
            get {
                return ResourceManager.GetString("AddExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional examiner.
        /// </summary>
        public static string AdditionalExaminer {
            get {
                return ResourceManager.GetString("AdditionalExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Batch.
        /// </summary>
        public static string AddToBatch {
            get {
                return ResourceManager.GetString("AddToBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All filters were added.
        /// </summary>
        public static string AllFiltersWereAdded {
            get {
                return ResourceManager.GetString("AllFiltersWereAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Marks Received.
        /// </summary>
        public static string AllMarksReceived {
            get {
                return ResourceManager.GetString("AllMarksReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Calculate.
        /// </summary>
        public static string AllowCalculate {
            get {
                return ResourceManager.GetString("AllowCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results can&apos;t be selected.
        /// </summary>
        public static string AllResultsSelected {
            get {
                return ResourceManager.GetString("AllResultsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Type.
        /// </summary>
        public static string ApplicationType {
            get {
                return ResourceManager.GetString("ApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This assessment have been changed.
        /// </summary>
        public static string AssessmentChanged {
            get {
                return ResourceManager.GetString("AssessmentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance ID.
        /// </summary>
        public static string AttendanceId {
            get {
                return ResourceManager.GetString("AttendanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Filters.
        /// </summary>
        public static string AvailableFilters {
            get {
                return ResourceManager.GetString("AvailableFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Confirmation.
        /// </summary>
        public static string AwaitingConfirmation {
            get {
                return ResourceManager.GetString("AwaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        public static string Band {
            get {
                return ResourceManager.GetString("Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This band have been changed.
        /// </summary>
        public static string BandChanged {
            get {
                return ResourceManager.GetString("BandChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Marks.
        /// </summary>
        public static string CalculateMarks {
            get {
                return ResourceManager.GetString("CalculateMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot alter the due date of a test without an examiner..
        /// </summary>
        public static string CannotAlterDueDateWithoutAMarker {
            get {
                return ResourceManager.GetString("CannotAlterDueDateWithoutAMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot submit assets on a test which has not been sat.
        /// </summary>
        public static string CannotSubmitAssets {
            get {
                return ResourceManager.GetString("CannotSubmitAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update due date of a test with no markers assigned..
        /// </summary>
        public static string CannotUpdateDueDate {
            get {
                return ResourceManager.GetString("CannotUpdateDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Result.
        /// </summary>
        public static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment added.
        /// </summary>
        public static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code (Group 1).
        /// </summary>
        public static string Comments1 {
            get {
                return ResourceManager.GetString("Comments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code (Group 2).
        /// </summary>
        public static string Comments2 {
            get {
                return ResourceManager.GetString("Comments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethics / Social / Cultural.
        /// </summary>
        public static string CommentsEthics {
            get {
                return ResourceManager.GetString("CommentsEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string CommentsGeneral {
            get {
                return ResourceManager.GetString("CommentsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed Result.
        /// </summary>
        public static string ComputedResult {
            get {
                return ResourceManager.GetString("ComputedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowing marks to be calculated will overwrite any currently overridden marks.
        /// </summary>
        public static string ConfirmAllowCalculate {
            get {
                return ResourceManager.GetString("ConfirmAllowCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost (per test).
        /// </summary>
        public static string CostPerTest {
            get {
                return ResourceManager.GetString("CostPerTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new batch.
        /// </summary>
        public static string CreateNewBatch {
            get {
                return ResourceManager.GetString("CreateNewBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Allocated.
        /// </summary>
        public static string DateAllocated {
            get {
                return ResourceManager.GetString("DateAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Due.
        /// </summary>
        public static string DateDue {
            get {
                return ResourceManager.GetString("DateDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type.
        /// </summary>
        public static string DateFilterType {
            get {
                return ResourceManager.GetString("DateFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Received.
        /// </summary>
        public static string DateReceived {
            get {
                return ResourceManager.GetString("DateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sent.
        /// </summary>
        public static string DateSent {
            get {
                return ResourceManager.GetString("DateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Submitted.
        /// </summary>
        public static string DateSubmitted {
            get {
                return ResourceManager.GetString("DateSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUAAAAFACAYAAADNkKWqAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC42/Ixj3wAAM8dJREFUeF7tnfeTW9eV579IDTQanXPOudkUo0RSYpAoamzvzO7s1szUhtqa/WH/sa3Zmd3aql2PbdnjGtvKokiKsXPO6ICOCI1uxL3nAi2TEmVLDMB7wPcjP3fjPZAEbvjec+4991xLUgFCCMlDrOmfhBCSd1AACSF5CwWQEJK3UAAJIXkLBZAQkrdQAAkheQsFkBCSt1AACSF5CwWQEJK3UAAJIXkLBZAQkrdQAAkheQsFkBCSt1AACSF5CwWQEJK3UAAJIXkLBZAQkrcwIzR5LSQSifRvL47FYtEXIa8LCiB5YaTpxOPxZ8QuIfdicWxsbGB7extW64sJWCKRRE1NDW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultAvatarBase64 {
            get {
                return ResourceManager.GetString("DefaultAvatarBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due By.
        /// </summary>
        public static string DueBy {
            get {
                return ResourceManager.GetString("DueBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The due date will be applied to all selected tests..
        /// </summary>
        public static string DueDateApplicability {
            get {
                return ResourceManager.GetString("DueDateApplicability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit examiner.
        /// </summary>
        public static string EditExaminer {
            get {
                return ResourceManager.GetString("EditExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Final Marks.
        /// </summary>
        public static string EditFinalMarks {
            get {
                return ResourceManager.GetString("EditFinalMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit marks.
        /// </summary>
        public static string EditMarks {
            get {
                return ResourceManager.GetString("EditMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rubric Result.
        /// </summary>
        public static string EditRubricResult {
            get {
                return ResourceManager.GetString("EditRubricResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible for Conceded Pass.
        /// </summary>
        public static string EligibleForConcededPass {
            get {
                return ResourceManager.GetString("EligibleForConcededPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible for Supplementary Test.
        /// </summary>
        public static string EligibleForSupplementary {
            get {
                return ResourceManager.GetString("EligibleForSupplementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner.
        /// </summary>
        public static string Examiner {
            get {
                return ResourceManager.GetString("Examiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tests do not have a valid status for adding a examiner..
        /// </summary>
        public static string ExaminerAddFail {
            get {
                return ResourceManager.GetString("ExaminerAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner &apos;{0}&apos; added to {1} tests..
        /// </summary>
        public static string ExaminerAddSuccess {
            get {
                return ResourceManager.GetString("ExaminerAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add &apos;{0}&apos; because these examiner(s) have already been assigned..
        /// </summary>
        public static string ExaminerAlreadyExists {
            get {
                return ResourceManager.GetString("ExaminerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner Files.
        /// </summary>
        public static string ExaminerFiles {
            get {
                return ResourceManager.GetString("ExaminerFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner marks removed.
        /// </summary>
        public static string ExaminerMarksRemoved {
            get {
                return ResourceManager.GetString("ExaminerMarksRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner Name.
        /// </summary>
        public static string ExaminerName {
            get {
                return ResourceManager.GetString("ExaminerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper received.
        /// </summary>
        public static string ExaminerPaperReceivedDate {
            get {
                return ResourceManager.GetString("ExaminerPaperReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following marking assignments have been created. &lt;br&gt;&lt;br&gt;&lt;b&gt;Examiner(s):&lt;/b&gt; {0}&lt;br&gt;&lt;br&gt;&lt;b&gt;Test(s):&lt;/b&gt; {1}.
        /// </summary>
        public static string ExaminersAddedSuccess {
            get {
                return ResourceManager.GetString("ExaminersAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiners &apos;{0}&apos; added to {1} tests..
        /// </summary>
        public static string ExaminersAddSuccess {
            get {
                return ResourceManager.GetString("ExaminersAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner saved..
        /// </summary>
        public static string ExaminerSavedSuccessfully {
            get {
                return ResourceManager.GetString("ExaminerSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner Status.
        /// </summary>
        public static string ExaminerStatus {
            get {
                return ResourceManager.GetString("ExaminerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ExaminerType {
            get {
                return ResourceManager.GetString("ExaminerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string ExaminerTypeOriginal {
            get {
                return ResourceManager.GetString("ExaminerTypeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Reviewer.
        /// </summary>
        public static string ExaminerTypePaidReviewer {
            get {
                return ResourceManager.GetString("ExaminerTypePaidReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Examiner.
        /// </summary>
        public static string ExaminerTypeThirdExaminer {
            get {
                return ResourceManager.GetString("ExaminerTypeThirdExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test cannot be unmarked as Sat because it has associated assets or examiners allocated..
        /// </summary>
        public static string FailOnUnmarkSat {
            get {
                return ResourceManager.GetString("FailOnUnmarkSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure reason.
        /// </summary>
        public static string FailureReason {
            get {
                return ResourceManager.GetString("FailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a Processed Fee for Application Id {0}.
        /// </summary>
        public static string FeeNotFound {
            get {
                return ResourceManager.GetString("FeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final mark.
        /// </summary>
        public static string FinalMark {
            get {
                return ResourceManager.GetString("FinalMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Marks Rubric Result.
        /// </summary>
        public static string FinalMarksRubricResult {
            get {
                return ResourceManager.GetString("FinalMarksRubricResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Result.
        /// </summary>
        public static string FinalResult {
            get {
                return ResourceManager.GetString("FinalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From English.
        /// </summary>
        public static string FromEnglish {
            get {
                return ResourceManager.GetString("FromEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Examiner Comments.
        /// </summary>
        public static string GetExaminerComments {
            get {
                return ResourceManager.GetString("GetExaminerComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has assets.
        /// </summary>
        public static string HasAssets {
            get {
                return ResourceManager.GetString("HasAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test is related to other tests in a job. Any changes you make to this test will be applied to all related tests. Select the Split option to only make changes to this test..
        /// </summary>
        public static string HasRelatedTestsInTheSameJob {
            get {
                return ResourceManager.GetString("HasRelatedTestsInTheSameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include previous marks.
        /// </summary>
        public static string IncludePreviousMark {
            get {
                return ResourceManager.GetString("IncludePreviousMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Without Assets.
        /// </summary>
        public static string IncludeWithoutAssets {
            get {
                return ResourceManager.GetString("IncludeWithoutAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results entered are not sufficient for a pass. Are you sure you wish to continue?.
        /// </summary>
        public static string InsufficientForPass {
            get {
                return ResourceManager.GetString("InsufficientForPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test must be finalised and the test result must be in the following status: {0}.
        /// </summary>
        public static string InvalidTestResultStatus {
            get {
                return ResourceManager.GetString("InvalidTestResultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue result.
        /// </summary>
        public static string IssueResult {
            get {
                return ResourceManager.GetString("IssueResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Supplementary.
        /// </summary>
        public static string IsSupplementary {
            get {
                return ResourceManager.GetString("IsSupplementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        public static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job(s) {0} created..
        /// </summary>
        public static string JobsCreated {
            get {
                return ResourceManager.GetString("JobsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language ID.
        /// </summary>
        public static string LanguageId {
            get {
                return ResourceManager.GetString("LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter added to batch.
        /// </summary>
        public static string LetterAddedToBatchSuccessfully {
            get {
                return ResourceManager.GetString("LetterAddedToBatchSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Batch.
        /// </summary>
        public static string LetterBatch {
            get {
                return ResourceManager.GetString("LetterBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not sent a letter for this result..
        /// </summary>
        public static string LetterNotSent {
            get {
                return ResourceManager.GetString("LetterNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sent a letter to this recipient. Are you sure you wish to send another?.
        /// </summary>
        public static string LetterSentSendAnother {
            get {
                return ResourceManager.GetString("LetterSentSendAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load search.
        /// </summary>
        public static string LoadSearch {
            get {
                return ResourceManager.GetString("LoadSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When loading a new search the current search data will be lost. Are you sure you want to do this?.
        /// </summary>
        public static string LoadSearchConfirm {
            get {
                return ResourceManager.GetString("LoadSearchConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a saved search from the list below or select filters from right side to begin your search..
        /// </summary>
        public static string LoadSearchOrSelectFilter {
            get {
                return ResourceManager.GetString("LoadSearchOrSelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Sat.
        /// </summary>
        public static string MarkAsSat {
            get {
                return ResourceManager.GetString("MarkAsSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner.
        /// </summary>
        public static string Marker {
            get {
                return ResourceManager.GetString("Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner Allocated.
        /// </summary>
        public static string MarkerAllocated {
            get {
                return ResourceManager.GetString("MarkerAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner Status.
        /// </summary>
        public static string MarkerStatus {
            get {
                return ResourceManager.GetString("MarkerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks.
        /// </summary>
        public static string Marks {
            get {
                return ResourceManager.GetString("Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tests cannot be marked as Sat.
        /// </summary>
        public static string MarkSatFail {
            get {
                return ResourceManager.GetString("MarkSatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tests marked as Sat.
        /// </summary>
        public static string MarkSatSuccess {
            get {
                return ResourceManager.GetString("MarkSatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks Overridden.
        /// </summary>
        public static string MarksOverridden {
            get {
                return ResourceManager.GetString("MarksOverridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to override test results.
        /// </summary>
        public static string MarksOverriddenRequiresAdministratorTooltip {
            get {
                return ResourceManager.GetString("MarksOverriddenRequiresAdministratorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to manually overwrite the final marks.
        /// </summary>
        public static string MarksOverriddenTooltip {
            get {
                return ResourceManager.GetString("MarksOverriddenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks saved..
        /// </summary>
        public static string MarksSavedSuccessfully {
            get {
                return ResourceManager.GetString("MarksSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Must be less than {0} characters).
        /// </summary>
        public static string MaxLengthCommentText {
            get {
                return ResourceManager.GetString("MaxLengthCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Must be between {0} characters and {1} characters).
        /// </summary>
        public static string MinMaxLengthCommentText {
            get {
                return ResourceManager.GetString("MinMaxLengthCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myNAATI Date Submitted.
        /// </summary>
        public static string myNAATIDateSubmitted {
            get {
                return ResourceManager.GetString("myNAATIDateSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string NaatiEntityDetailsHeadingFormat {
            get {
                return ResourceManager.GetString("NaatiEntityDetailsHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Candidates Only.
        /// </summary>
        public static string NewCandidatesOnly {
            get {
                return ResourceManager.GetString("NewCandidatesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ID card.
        /// </summary>
        public static string NoIdCard {
            get {
                return ResourceManager.GetString("NoIdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test does not have examiners..
        /// </summary>
        public static string NoMarkers {
            get {
                return ResourceManager.GetString("NoMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Test Task must be selected.
        /// </summary>
        public static string NoResultsSelected {
            get {
                return ResourceManager.GetString("NoResultsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable for this result.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Attempted.
        /// </summary>
        public static string NotAttempted {
            get {
                return ResourceManager.GetString("NotAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Test Specification.
        /// </summary>
        public static string NotDefaultSpecification {
            get {
                return ResourceManager.GetString("NotDefaultSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations On Performance.
        /// </summary>
        public static string ObservationsOnPerformance {
            get {
                return ResourceManager.GetString("ObservationsOnPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final rubric can only be calculated when there are 1 or 2 examiners.
        /// </summary>
        public static string OneOrTwoExaminerRequired {
            get {
                return ResourceManager.GetString("OneOrTwoExaminerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original result.
        /// </summary>
        public static string OriginalResult {
            get {
                return ResourceManager.GetString("OriginalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This candidate has outstanding invoices! Are you sure you wish to save this test result?.
        /// </summary>
        public static string OutstandingInvoices {
            get {
                return ResourceManager.GetString("OutstandingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall result.
        /// </summary>
        public static string OverallResult {
            get {
                return ResourceManager.GetString("OverallResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to override the system result?.
        /// </summary>
        public static string OverrideResultQuestion {
            get {
                return ResourceManager.GetString("OverrideResultQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Review.
        /// </summary>
        public static string PaidReview {
            get {
                return ResourceManager.GetString("PaidReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Review Not Allowed.
        /// </summary>
        public static string PaidReviewNotAllowed {
            get {
                return ResourceManager.GetString("PaidReviewNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper lost.
        /// </summary>
        public static string PaperLost {
            get {
                return ResourceManager.GetString("PaperLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Result.
        /// </summary>
        public static string PassFailed {
            get {
                return ResourceManager.GetString("PassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll status.
        /// </summary>
        public static string PayrollStatus {
            get {
                return ResourceManager.GetString("PayrollStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Paid Reviewers.
        /// </summary>
        public static string PendingToAssignPaidReviewers {
            get {
                return ResourceManager.GetString("PendingToAssignPaidReviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}{2}{3}{4}.
        /// </summary>
        public static string PersonDetailsHeadingFormat {
            get {
                return ResourceManager.GetString("PersonDetailsHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - {2} - {3}.
        /// </summary>
        public static string PersonLogbookHeadingFormat {
            get {
                return ResourceManager.GetString("PersonLogbookHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see your manager..
        /// </summary>
        public static string PleaseSeeYourManager {
            get {
                return ResourceManager.GetString("PleaseSeeYourManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filters from right side to begin your search.
        /// </summary>
        public static string PleaseSelectAFilter {
            get {
                return ResourceManager.GetString("PleaseSelectAFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate the comments field from the examiner comments.
        /// </summary>
        public static string PopulateFromExaminers {
            get {
                return ResourceManager.GetString("PopulateFromExaminers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary address for this recipient is invalid. Please ensure this entity has a valid primary address..
        /// </summary>
        public static string PrimaryAddressIsInvalid {
            get {
                return ResourceManager.GetString("PrimaryAddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary reason for failure.
        /// </summary>
        public static string PrimaryReasonForFailure {
            get {
                return ResourceManager.GetString("PrimaryReasonForFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Date.
        /// </summary>
        public static string ProcessedDate {
            get {
                return ResourceManager.GetString("ProcessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ProductSpecificationCodeLabel {
            get {
                return ResourceManager.GetString("ProductSpecificationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Automation.
        /// </summary>
        public static string ReadyForAutomation {
            get {
                return ResourceManager.GetString("ReadyForAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons for poor performance.
        /// </summary>
        public static string ReasonsForPoorPerformance {
            get {
                return ResourceManager.GetString("ReasonsForPoorPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received date.
        /// </summary>
        public static string ReceivedDate {
            get {
                return ResourceManager.GetString("ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot issue a result on a test without any examiner.
        /// </summary>
        public static string RequiredExaminer {
            get {
                return ResourceManager.GetString("RequiredExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot issue a result on a test without any examiner.
        /// </summary>
        public static string RequiredPaidReviewExamier {
            get {
                return ResourceManager.GetString("RequiredPaidReviewExamier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two examiner results differ and a third marking is required..
        /// </summary>
        public static string RequiredThirdMarking {
            get {
                return ResourceManager.GetString("RequiredThirdMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result checked.
        /// </summary>
        public static string ResultChecked {
            get {
                return ResourceManager.GetString("ResultChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result due.
        /// </summary>
        public static string ResultDue {
            get {
                return ResourceManager.GetString("ResultDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Letter.
        /// </summary>
        public static string ResultLetter {
            get {
                return ResourceManager.GetString("ResultLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Received.
        /// </summary>
        public static string ResultReceived {
            get {
                return ResourceManager.GetString("ResultReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has calculated a different result. The following areas differ:.
        /// </summary>
        public static string ResultsDontMatch {
            get {
                return ResourceManager.GetString("ResultsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Status.
        /// </summary>
        public static string ResultStatus {
            get {
                return ResourceManager.GetString("ResultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final rubric cannot be calculated because a false pass has been detected for {0}. A third marking is required..
        /// </summary>
        public static string RubricFalsePassDetected {
            get {
                return ResourceManager.GetString("RubricFalsePassDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final rubric cannot be calculated because examiners do not agree on results of all tasks..
        /// </summary>
        public static string RubricMismatch {
            get {
                return ResourceManager.GetString("RubricMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are editing the search &apos;{0}&apos;. What do you want to do?.
        /// </summary>
        public static string SaveCurrentOrSaveNewOne {
            get {
                return ResourceManager.GetString("SaveCurrentOrSaveNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Searches.
        /// </summary>
        public static string SavedSearches {
            get {
                return ResourceManager.GetString("SavedSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save search.
        /// </summary>
        public static string SaveSearch {
            get {
                return ResourceManager.GetString("SaveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an assessment to show the bands.
        /// </summary>
        public static string SelectBand {
            get {
                return ResourceManager.GetString("SelectBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Band.
        /// </summary>
        public static string SelectedBand {
            get {
                return ResourceManager.GetString("SelectedBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent date.
        /// </summary>
        public static string SentDate {
            get {
                return ResourceManager.GetString("SentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to payroll date.
        /// </summary>
        public static string SentToPayrollDate {
            get {
                return ResourceManager.GetString("SentToPayrollDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results.
        /// </summary>
        public static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Job.
        /// </summary>
        public static string SplitJob {
            get {
                return ResourceManager.GetString("SplitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes to split this test from related tests. This action cannot be undone..
        /// </summary>
        public static string SplitJobConfirm {
            get {
                return ResourceManager.GetString("SplitJobConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been split..
        /// </summary>
        public static string SplitJobSuccess {
            get {
                return ResourceManager.GetString("SplitJobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Letter.
        /// </summary>
        public static string StandardLetter {
            get {
                return ResourceManager.GetString("StandardLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Category.
        /// </summary>
        public static string StandardLetterCategory {
            get {
                return ResourceManager.GetString("StandardLetterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results entered are sufficient for a Pass, but you have selected Fail. Are you sure you wish to continue?.
        /// </summary>
        public static string SufficientForPass {
            get {
                return ResourceManager.GetString("SufficientForPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary.
        /// </summary>
        public static string Supplementary {
            get {
                return ResourceManager.GetString("Supplementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary result.
        /// </summary>
        public static string SupplementaryResult {
            get {
                return ResourceManager.GetString("SupplementaryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary Test.
        /// </summary>
        public static string SupplementaryTest {
            get {
                return ResourceManager.GetString("SupplementaryTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test result is not eligible for a Supplementary Test.
        /// </summary>
        public static string SupplementaryTestNotAllowed {
            get {
                return ResourceManager.GetString("SupplementaryTestNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following tasks result(s) have been changed. Are you sure you want to proceed?.
        /// </summary>
        public static string TasksResultChanged {
            get {
                return ResourceManager.GetString("TasksResultChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        public static string Tentative {
            get {
                return ResourceManager.GetString("Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a Paid Review for this test result.
        /// </summary>
        public static string TestAlreadyHasAPaidReview {
            get {
                return ResourceManager.GetString("TestAlreadyHasAPaidReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a Supplementary Test for this result.
        /// </summary>
        public static string TestAlreadyHasASupplementaryTest {
            get {
                return ResourceManager.GetString("TestAlreadyHasASupplementaryTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        public static string TestDate {
            get {
                return ResourceManager.GetString("TestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date (at Venue).
        /// </summary>
        public static string TestDateAtVenue {
            get {
                return ResourceManager.GetString("TestDateAtVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date From and To.
        /// </summary>
        public static string TestDateFromAndTo {
            get {
                return ResourceManager.GetString("TestDateFromAndTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Event ID.
        /// </summary>
        public static string TestEventId {
            get {
                return ResourceManager.GetString("TestEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test already has assets or examiners..
        /// </summary>
        public static string TestHasAssetsOrExaminers {
            get {
                return ResourceManager.GetString("TestHasAssetsOrExaminers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test has been invalidated.
        /// </summary>
        public static string TestInvalidatedMessage {
            get {
                return ResourceManager.GetString("TestInvalidatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Location.
        /// </summary>
        public static string TestLocation {
            get {
                return ResourceManager.GetString("TestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Materials.
        /// </summary>
        public static string TestMaterials {
            get {
                return ResourceManager.GetString("TestMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Overall Result for this Test Result is:.
        /// </summary>
        public static string TestMessage {
            get {
                return ResourceManager.GetString("TestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Office.
        /// </summary>
        public static string TestOffice {
            get {
                return ResourceManager.GetString("TestOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result ID.
        /// </summary>
        public static string TestResultId {
            get {
                return ResourceManager.GetString("TestResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results are out of date. Please refresh your search for the latest results..
        /// </summary>
        public static string TestResultsOutOfDateMessage {
            get {
                return ResourceManager.GetString("TestResultsOutOfDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Search.
        /// </summary>
        public static string TestSearch {
            get {
                return ResourceManager.GetString("TestSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Status.
        /// </summary>
        public static string TestStatus {
            get {
                return ResourceManager.GetString("TestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Type.
        /// </summary>
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Venue.
        /// </summary>
        public static string TestVenue {
            get {
                return ResourceManager.GetString("TestVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To English.
        /// </summary>
        public static string ToEnglish {
            get {
                return ResourceManager.GetString("ToEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Payroll.
        /// </summary>
        public static string ToPayroll {
            get {
                return ResourceManager.GetString("ToPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark as Sat.
        /// </summary>
        public static string UnmarkAsSat {
            get {
                return ResourceManager.GetString("UnmarkAsSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unmarked test as Sat.
        /// </summary>
        public static string UnmarkAsSatSuccess {
            get {
                return ResourceManager.GetString("UnmarkAsSatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Due Date.
        /// </summary>
        public static string UpdateDueDate {
            get {
                return ResourceManager.GetString("UpdateDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk update due by date.
        /// </summary>
        public static string UpdateDueDateModalTitle {
            get {
                return ResourceManager.GetString("UpdateDueDateModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Assets.
        /// </summary>
        public static string UploadAssets {
            get {
                return ResourceManager.GetString("UploadAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was Attempted.
        /// </summary>
        public static string WasAttempted {
            get {
                return ResourceManager.GetString("WasAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string Withdrawn {
            get {
                return ResourceManager.GetString("Withdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no saved searches.
        /// </summary>
        public static string YouHaveNoSavedSearches {
            get {
                return ResourceManager.GetString("YouHaveNoSavedSearches", resourceCulture);
            }
        }
    }
}
