BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tblRubricAssessementCriterionResult ADD
	CommentDate datetime NULL
GO
ALTER TABLE dbo.tblRubricAssessementCriterionResult ADD CONSTRAINT
	DF_tblRubricAssessementCriterionResult_CommentDate DEFAULT GETDATE() FOR CommentDate
GO
ALTER TABLE dbo.tblRubricAssessementCriterionResult SET (LOCK_ESCALATION = TABLE)
GO
COMMIT