//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.NAATI._20180730_ConvertTablesToIdentity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.NAATI._20180730_ConvertTablesToIdentity.Resou" +
                            "rce", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblMergeData]
        ///DROP CONSTRAINT [FK_tblMergeData_tblAddress]
        ///ALTER TABLE [dbo].[tblMailingListAddress]
        ///DROP CONSTRAINT [FK_tblMailingListAddress_tblAddress]
        ///ALTER TABLE [dbo].[tblAddressMailCategory]
        ///DROP CONSTRAINT [FK_tblAddressMailCategory_tblAddress]
        ///ALTER TABLE [dbo].[tblAddress]
        ///DROP CONSTRAINT [FK_tblAddress_tblEntity]
        ///ALTER TABLE [dbo].[tblAddress]
        ///DROP CONSTRAINT [FK_Address_ODAddressVisibilityType]
        ///ALTER TABLE [dbo].[tblAddress]
        ///DROP CONSTRAINT [FK_tblAddress_tblPostcod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertAddressToIdentity {
            get {
                return ResourceManager.GetString("ConvertAddressToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblOrder]
        ///DROP CONSTRAINT [FK_Order_Country]
        ///ALTER TABLE [dbo].[tblTestLocation]
        ///DROP CONSTRAINT [FK_TestLocation_Country]
        ///ALTER TABLE [dbo].[tblApplication]
        ///DROP CONSTRAINT [FK_tblApplication_tblCountry]
        ///ALTER TABLE [dbo].[tblPerson]
        ///DROP CONSTRAINT [FK_tblPerson_tblCountry]
        ///ALTER TABLE [dbo].[tluRegion]
        ///DROP CONSTRAINT [FK_tluRegion_tblCountry]
        ///GO
        ///DROP STATISTICS [dbo].[tblCountry].[_WA_Sys_00000003_7C8480AE]
        ///GO
        ///DROP STATISTICS [dbo].[tblCountry].[_WA_Sys_Name_7C8480AE]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertCountryToIdentity {
            get {
                return ResourceManager.GetString("ConvertCountryToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DROP STATISTICS [dbo].[tluEFTMachine].[_WA_Sys_00000004_6E814571]
        ///GO
        ///DROP STATISTICS [dbo].[tluEFTMachine].[_WA_Sys_OfficeId_6E814571]
        ///GO
        ///DROP STATISTICS [dbo].[tluEFTMachine].[_WA_Sys_RowVersion_6E814571]
        ///GO
        ///DROP STATISTICS [dbo].[tluEFTMachine].[_WA_Sys_TerminalNo_6E814571]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tluEFTMachine]&apos;,
        ///	@newname  = N&apos;tmp_26ab43b7ba174104b0094ff95af3ba03&apos;,
        ///	@objtype  = &apos;OBJECT&apos;
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[DF_tluEFTMachine_Visible]&apos;,
        ///	@ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertEFTMachineToIdentity {
            get {
                return ResourceManager.GetString("ConvertEFTMachineToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///ALTER TABLE [dbo].[tblEmailBatchRecipient]
        ///DROP CONSTRAINT [FK_tblEmailBatchRecipient_EmailId_tblEmail_EmailId]
        ///ALTER TABLE [dbo].[tblEmail]
        ///DROP CONSTRAINT [FK_tblEmail_tblEntity]
        ///GO
        ///DROP STATISTICS [dbo].[tblEmail].[_WA_Sys_00000004_00551192]
        ///GO
        ///DROP STATISTICS [dbo].[tblEmail].[_WA_Sys_00000009_00551192]
        ///GO
        ///DROP STATISTICS [dbo].[tblEmail].[_WA_Sys_Email_00551192]
        ///GO
        ///DROP STATISTICS [dbo].[tblEmail].[_WA_Sys_EntityId_00551192]
        ///GO
        ///DROP STATISTICS [dbo].[tblEmail].[_WA_Sys_IncludeInPD_0055 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertEmailToIdentity {
            get {
                return ResourceManager.GetString("ConvertEmailToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblMergeData]
        ///DROP CONSTRAINT [FK_tblMergeData_tblEntity]
        ///ALTER TABLE [dbo].[tblPhone]
        ///DROP CONSTRAINT [FK_tblPhone_tblEntity]
        ///ALTER TABLE [dbo].[tblTransaction]
        ///DROP CONSTRAINT [FK_tblTransaction_tblEntity]
        ///ALTER TABLE [dbo].[tblReminder]
        ///DROP CONSTRAINT [FK_tblReminder_tblEntity]
        ///ALTER TABLE [dbo].[tblEmailMessage]
        ///DROP CONSTRAINT [FK_EmailMessage_Entity]
        ///ALTER TABLE [dbo].[tblEventVenue]
        ///DROP CONSTRAINT [FK_tblEventVenue_tblEntity]
        ///ALTER TABLE [dbo].[tblAddress]
        ///DROP CONST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertEntityToIdentity {
            get {
                return ResourceManager.GetString("ConvertEntityToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblTestResultFailureReason]
        ///DROP CONSTRAINT [FK_tblTestResultFailureReason_tluFailureReason]
        ///ALTER TABLE [dbo].[tblAccreditationResult]
        ///DROP CONSTRAINT [FK_tblAccreditationResult_tluFailureReason]
        ///GO
        ///DROP STATISTICS [dbo].[tluFailureReason].[_WA_Sys_00000002_48CFD27E]
        ///GO
        ///DROP STATISTICS [dbo].[tluFailureReason].[_WA_Sys_00000003_48CFD27E]
        ///GO
        ///DROP STATISTICS [dbo].[tluFailureReason].[_WA_Sys_RowVersion_48CFD27E]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tluFailureReason [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertFailureReasonToIdentity {
            get {
                return ResourceManager.GetString("ConvertFailureReasonToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblInstitutionName]
        ///DROP CONSTRAINT [FK_tblInstitutionName_tblInstitution]
        ///GO
        ///DROP STATISTICS [dbo].[tblInstitutionName].[_WA_Sys_Abbreviation_08EA5793]
        ///GO
        ///DROP STATISTICS [dbo].[tblInstitutionName].[_WA_Sys_EffectiveDate_08EA5793]
        ///GO
        ///DROP STATISTICS [dbo].[tblInstitutionName].[_WA_Sys_InstitutionId_08EA5793]
        ///GO
        ///DROP STATISTICS [dbo].[tblInstitutionName].[_WA_Sys_Name_08EA5793]
        ///GO
        ///DROP STATISTICS [dbo].[tblInstitutionName].[_WA_Sys_RowVersion_08EA5793]
        ///GO
        ///DROP STATISTICS [d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertInstitutionNameToIdentity {
            get {
                return ResourceManager.GetString("ConvertInstitutionNameToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblCourseLocation]
        ///DROP CONSTRAINT [FK_tblCourseLocation_tblInstitution]
        ///ALTER TABLE [dbo].[tblProject]
        ///DROP CONSTRAINT [FK_tblProject_tblInstitution]
        ///ALTER TABLE [dbo].[tblContactPerson]
        ///DROP CONSTRAINT [FK_ContactPerson_Institution]
        ///ALTER TABLE [dbo].[tblCredentialApplication]
        ///DROP CONSTRAINT [FK_CredentialApplication_Institution]
        ///ALTER TABLE [dbo].[tblApplication]
        ///DROP CONSTRAINT [FK_tblApplication_SponsorInstitutionId_tblInstitution_InstitutionId]
        ///ALTER TABLE [dbo].[tblIns [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertInstitutionToIdentity {
            get {
                return ResourceManager.GetString("ConvertInstitutionToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblWorkshopEvent]
        ///DROP CONSTRAINT [FK_tblWorkshopEvent_tblLanguage]
        ///ALTER TABLE [dbo].[tblPanel]
        ///DROP CONSTRAINT [FK_tblPanel_tblLanguage]
        ///ALTER TABLE [dbo].[tblAlternateLanguageName]
        ///DROP CONSTRAINT [FK_AlternateLanguageName_Language]
        ///ALTER TABLE [dbo].[tblWorkshopAttendanceLanguage]
        ///DROP CONSTRAINT [FK_tblWorkshopAttendanceLanguage_tblLanguage]
        ///ALTER TABLE [dbo].[tblTestMaterial]
        ///DROP CONSTRAINT [FK_TestMaterial_Language]
        ///ALTER TABLE [dbo].[tblSkill]
        ///DROP CONSTRAINT [FK_Ski [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertLanguageToIdentity {
            get {
                return ResourceManager.GetString("ConvertLanguageToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblTestLocation]
        ///DROP CONSTRAINT [FK_TestLocation_Office]
        ///ALTER TABLE [dbo].[tblUser]
        ///DROP CONSTRAINT [FK_tblUser_tblOffice]
        ///ALTER TABLE [dbo].[tblCredentialApplication]
        ///DROP CONSTRAINT [FK_CredentialApplication_Office]
        ///ALTER TABLE [dbo].[tblTransaction]
        ///DROP CONSTRAINT [FK_tblTransaction_tblOffice]
        ///ALTER TABLE [dbo].[tblApplication]
        ///DROP CONSTRAINT [FK_tblApplication_tblOffice]
        ///ALTER TABLE [dbo].[tblEventVenue]
        ///DROP CONSTRAINT [FK_tblEventVenue_tblOffice]
        ///ALTER TABLE [dbo]. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertOfficeToIdentity {
            get {
                return ResourceManager.GetString("ConvertOfficeToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblJobExaminer]
        ///DROP CONSTRAINT [FK_JobExaminer_PanelMembership]
        ///ALTER TABLE [dbo].[tblPanelMembership]
        ///DROP CONSTRAINT [FK_tblPanelMembership_tblPanel]
        ///ALTER TABLE [dbo].[tblPanelMembership]
        ///DROP CONSTRAINT [FK_tblPanelMembership_tblPerson]
        ///ALTER TABLE [dbo].[tblPanelMembership]
        ///DROP CONSTRAINT [FK_tblPanelMembership_tluRoleType]
        ///GO
        ///DROP STATISTICS [dbo].[tblPanelMembership].[_WA_Sys_EndDate_1BFD2C07]
        ///GO
        ///DROP STATISTICS [dbo].[tblPanelMembership].[_WA_Sys_PanelId_1BFD2C07]
        ///GO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPanelMembershipToIdentity {
            get {
                return ResourceManager.GetString("ConvertPanelMembershipToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblPanelMembership]
        ///DROP CONSTRAINT [FK_tblPanelMembership_tblPanel]
        ///ALTER TABLE [dbo].[tblPanelNote]
        ///DROP CONSTRAINT [FK_tblPanelNote_tblPanel]
        ///ALTER TABLE [dbo].[tblPanel]
        ///DROP CONSTRAINT [FK_tblPanel_tblLanguage]
        ///ALTER TABLE [dbo].[tblPanel]
        ///DROP CONSTRAINT [FK_tblPanel_tluPanelType]
        ///GO
        ///DROP STATISTICS [dbo].[tblPanel].[_WA_Sys_00000004_1B0907CE]
        ///GO
        ///DROP STATISTICS [dbo].[tblPanel].[_WA_Sys_00000006_1B0907CE]
        ///GO
        ///DROP STATISTICS [dbo].[tblPanel].[_WA_Sys_00000008_1B0907CE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPanelToIdentity {
            get {
                return ResourceManager.GetString("ConvertPanelToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblPanel]
        ///DROP CONSTRAINT [FK_tblPanel_tluPanelType]
        ///GO
        ///DROP STATISTICS [dbo].[tluPanelType].[_WA_Sys_00000002_4BAC3F29]
        ///GO
        ///DROP STATISTICS [dbo].[tluPanelType].[_WA_Sys_00000003_4BAC3F29]
        ///GO
        ///DROP STATISTICS [dbo].[tluPanelType].[_WA_Sys_RowVersion_4BAC3F29]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tluPanelType]&apos;,
        ///	@newname  = N&apos;tmp_c16f6fd1d9d4449f86e45cca7b88c0e1&apos;,
        ///	@objtype  = &apos;OBJECT&apos;
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[tluPanelType]&apos;,
        ///	@newname  = N&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPanelTypeToIdentity {
            get {
                return ResourceManager.GetString("ConvertPanelTypeToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblPersonImage]
        ///DROP CONSTRAINT [FK_tblPersonImage_tblPerson]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonImage].[_WA_Sys_00000003_1AE9D794]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonImage].[_WA_Sys_00000004_1AE9D794]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonImage].[_WA_Sys_00000005_1AE9D794]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonImage].[_WA_Sys_00000006_1AE9D794]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonImage].[_WA_Sys_00000008_1AE9D794]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonImage].[_WA_Sys_PersonId_1AE9D7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPersonImageToIdentity {
            get {
                return ResourceManager.GetString("ConvertPersonImageToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblPersonName]
        ///DROP CONSTRAINT [FK_tblPersonName_tblPerson]
        ///ALTER TABLE [dbo].[tblPersonName]
        ///DROP CONSTRAINT [FK_tblPersonName_tluTitle1]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonName].[_dta_stat_629577281_1_3_4_5_6]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonName].[_dta_stat_629577281_1_3_4_5_7_6]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonName].[_dta_stat_629577281_1_5_2_4_3_6_7]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonName].[_dta_stat_629577281_2_1_7_5_3]
        ///GO
        ///DROP STATISTICS [dbo].[tblPersonName]. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPersonNameToIdentity {
            get {
                return ResourceManager.GetString("ConvertPersonNameToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblPersonImage]
        ///DROP CONSTRAINT [FK_tblPersonImage_tblPerson]
        ///ALTER TABLE [dbo].[tblCredentialApplication]
        ///DROP CONSTRAINT [FK_CredentialApplication_Person]
        ///ALTER TABLE [dbo].[tblProfessionalDevelopmentActivity]
        ///DROP CONSTRAINT [FK_ProfessionalDevelopmentActivity_Person]
        ///ALTER TABLE [dbo].[tblPDInclusion]
        ///DROP CONSTRAINT [FK_tblPDInclusion_tblPerson]
        ///ALTER TABLE [dbo].[tblTestResultAttachment]
        ///DROP CONSTRAINT [FK_tblTestResultAttachment_tblPerson_01]
        ///ALTER TABLE [dbo].[tblTest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPersonToIdentity {
            get {
                return ResourceManager.GetString("ConvertPersonToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblPhone]
        ///DROP CONSTRAINT [FK_tblPhone_tblEntity]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys_00000003_2D52A092]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys_00000004_2D52A092]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys_00000005_2D52A092]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys_00000007_2D52A092]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys_0000000C_2D52A092]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys_0000000D_2D52A092]
        ///GO
        ///DROP STATISTICS [dbo].[tblPhone].[_WA_Sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPhoneToIdentity {
            get {
                return ResourceManager.GetString("ConvertPhoneToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblAddress]
        ///DROP CONSTRAINT [FK_tblAddress_tblPostcode]
        ///ALTER TABLE [dbo].[tblPostcode]
        ///DROP CONSTRAINT [FK_tblPostcode_tblSuburb]
        ///GO
        ///DROP STATISTICS [dbo].[tblPostcode].[_dta_stat_661577395_2_3]
        ///GO
        ///DROP STATISTICS [dbo].[tblPostcode].[_dta_stat_661577395_3_1_2]
        ///GO
        ///DROP STATISTICS [dbo].[tblPostcode].[_WA_Sys_Postcode_276EDEB3]
        ///GO
        ///DROP STATISTICS [dbo].[tblPostcode].[_WA_Sys_RowVersion_276EDEB3]
        ///GO
        ///DROP STATISTICS [dbo].[tblPostcode].[_WA_Sys_SuburbId_276EDEB3]
        ///GO
        ///EXECUTE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertPoscodeToIdentity {
            get {
                return ResourceManager.GetString("ConvertPoscodeToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblTestResult]
        ///DROP CONSTRAINT [FK_TestResult_ResultType]
        ///ALTER TABLE [dbo].[tblAccreditationResult]
        ///DROP CONSTRAINT [FK_tblAccreditationResult_tluResultType]
        ///GO
        ///DROP STATISTICS [dbo].[tluResultType].[_WA_Sys_Result_5165187F]
        ///GO
        ///DROP STATISTICS [dbo].[tluResultType].[_WA_Sys_RowVersion_5165187F]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tluResultType]&apos;,
        ///	@newname  = N&apos;tmp_fe98b49e6fc54d0ea682063c9cdf81b1&apos;,
        ///	@objtype  = &apos;OBJECT&apos;
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertResultTypeToIdentity {
            get {
                return ResourceManager.GetString("ConvertResultTypeToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblRoleScreen]
        ///DROP CONSTRAINT [FK_tblRoleScreen_tluPermission]
        ///ALTER TABLE [dbo].[tblRoleScreen]
        ///DROP CONSTRAINT [FK_tblRoleScreen_tluRole]
        ///GO
        ///DROP STATISTICS [dbo].[tblRoleScreen].[_WA_Sys_PermissionId_2A4B4B5E]
        ///GO
        ///DROP STATISTICS [dbo].[tblRoleScreen].[_WA_Sys_RoleId_2A4B4B5E]
        ///GO
        ///DROP STATISTICS [dbo].[tblRoleScreen].[_WA_Sys_RowVersion_2A4B4B5E]
        ///GO
        ///DROP STATISTICS [dbo].[tblRoleScreen].[_WA_Sys_ScreenId_2A4B4B5E]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tblRoleS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertRoleScreenToIdentity {
            get {
                return ResourceManager.GetString("ConvertRoleScreenToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblRoleScreen]
        ///DROP CONSTRAINT [FK_tblRoleScreen_tluRole]
        ///ALTER TABLE [dbo].[tblUserRole]
        ///DROP CONSTRAINT [FK_tblUserRole_tblRole]
        ///GO
        ///DROP STATISTICS [dbo].[tluRole].[_WA_Sys_00000002_52593CB8]
        ///GO
        ///DROP STATISTICS [dbo].[tluRole].[_WA_Sys_00000003_52593CB8]
        ///GO
        ///DROP STATISTICS [dbo].[tluRole].[_WA_Sys_00000004_52593CB8]
        ///GO
        ///DROP STATISTICS [dbo].[tluRole].[_WA_Sys_RowVersion_52593CB8]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tblRole]&apos;,
        ///	@newname  = N&apos;tmp_a289f09621a54 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertRoleToIdentity {
            get {
                return ResourceManager.GetString("ConvertRoleToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblPanelMembership]
        ///DROP CONSTRAINT [FK_tblPanelMembership_tluRoleType]
        ///GO
        ///DROP STATISTICS [dbo].[tluRoleType].[_WA_Sys_00000003_534D60F1]
        ///GO
        ///DROP STATISTICS [dbo].[tluRoleType].[_WA_Sys_00000005_534D60F1]
        ///GO
        ///DROP STATISTICS [dbo].[tluRoleType].[_WA_Sys_Name_534D60F1]
        ///GO
        ///DROP STATISTICS [dbo].[tluRoleType].[_WA_Sys_RowVersion_534D60F1]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tluRoleType]&apos;,
        ///	@newname  = N&apos;tmp_0f6adf47c190478d84f25386208f1586&apos;,
        ///	@objtype  = &apos;OBJECT&apos;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertRoleTypeToIdentity {
            get {
                return ResourceManager.GetString("ConvertRoleTypeToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblOffice]
        ///DROP CONSTRAINT [FK_tblOffice_tluState]
        ///ALTER TABLE [dbo].[tblSuburb]
        ///DROP CONSTRAINT [FK_tblSuburb_tluState]
        ///ALTER TABLE [dbo].[tluRegion]
        ///DROP CONSTRAINT [FK_tluRegion_tluState]
        ///GO
        ///DROP STATISTICS [dbo].[tluState].[_WA_Sys_Name_5535A963]
        ///GO
        ///DROP STATISTICS [dbo].[tluState].[_WA_Sys_RowVersion_5535A963]
        ///GO
        ///DROP STATISTICS [dbo].[tluState].[_WA_Sys_State_5535A963]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tblState]&apos;,
        ///	@newname  = N&apos;tmp_bec112096cbe44d0bc7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertStateToIdentity {
            get {
                return ResourceManager.GetString("ConvertStateToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblOrder]
        ///DROP CONSTRAINT [FK_Order_Suburb]
        ///ALTER TABLE [dbo].[tblPostcode]
        ///DROP CONSTRAINT [FK_tblPostcode_tblSuburb]
        ///ALTER TABLE [dbo].[tblSuburb]
        ///DROP CONSTRAINT [FK_tblSuburb_tluState]
        ///GO
        ///DROP STATISTICS [dbo].[tblSuburb].[_dta_stat_741577680_3_2_1]
        ///GO
        ///DROP STATISTICS [dbo].[tblSuburb].[_WA_Sys_RowVersion_2C3393D0]
        ///GO
        ///DROP STATISTICS [dbo].[tblSuburb].[_WA_Sys_StateId_2C3393D0]
        ///GO
        ///DROP STATISTICS [dbo].[tblSuburb].[_WA_Sys_Suburb_2C3393D0]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertSuburbToIdentity {
            get {
                return ResourceManager.GetString("ConvertSuburbToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblRubricMarkingCompetency]
        ///DROP CONSTRAINT [FK_RubricMarkingCompetency_TestComponentType]
        ///ALTER TABLE [dbo].[tblTestComponentTypeStandardMarkingScheme]
        ///DROP CONSTRAINT [FK_TestComponentTypeStandardMarkingScheme_TestComponentType]
        ///ALTER TABLE [dbo].[tblTestComponent]
        ///DROP CONSTRAINT [FK_TestComponent_TestComponentType]
        ///ALTER TABLE [dbo].[tblTestMaterial]
        ///DROP CONSTRAINT [FK_TestMaterial_TestComponentType]
        ///ALTER TABLE [dbo].[tblExaminerTestComponentResult]
        ///DROP CONSTRAINT [FK_Ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertTestComponentTypeToIdentity {
            get {
                return ResourceManager.GetString("ConvertTestComponentTypeToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblTestResultFailureReason]
        ///DROP CONSTRAINT [FK_tblTestResultFailureReason_tluFailureReason]
        ///ALTER TABLE [dbo].[tblTestResultFailureReason]
        ///DROP CONSTRAINT [FK_TestResultFailureReason_TestResult]
        ///GO
        ///DROP STATISTICS [dbo].[tblTestResultFailureReason].[_WA_Sys_FailureReasonId_36B12243]
        ///GO
        ///DROP STATISTICS [dbo].[tblTestResultFailureReason].[_WA_Sys_RowVersion_36B12243]
        ///GO
        ///DROP STATISTICS [dbo].[tblTestResultFailureReason].[_WA_Sys_TestResultId_36B12243]
        ///GO
        ///EXECUTE [sp_rename]
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertTestFailureReasonToIdentity {
            get {
                return ResourceManager.GetString("ConvertTestFailureReasonToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[tblPersonName]
        ///DROP CONSTRAINT [FK_tblPersonName_tluTitle1]
        ///GO
        ///DROP STATISTICS [dbo].[tluTitle].[_WA_Sys_00000003_59063A47]
        ///GO
        ///DROP STATISTICS [dbo].[tluTitle].[_WA_Sys_RowVersion_59063A47]
        ///GO
        ///DROP STATISTICS [dbo].[tluTitle].[_WA_Sys_Title_59063A47]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tluTitle]&apos;,
        ///	@newname  = N&apos;tmp_aa0513a56cdb404482ddefaf86f61bea&apos;,
        ///	@objtype  = &apos;OBJECT&apos;
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[tluTitle]&apos;,
        ///	@newname  = N&apos;tmp_c28a1c4fa60346 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertTitleToIdentity {
            get {
                return ResourceManager.GetString("ConvertTitleToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblUserRole]
        ///DROP CONSTRAINT [FK_tblUserRole_tblRole]
        ///ALTER TABLE [dbo].[tblUserRole]
        ///DROP CONSTRAINT [FK_tblUserRole_tblUser]
        ///GO
        ///DROP STATISTICS [dbo].[tblUserRole].[_WA_Sys_RoleId_3A81B327]
        ///GO
        ///DROP STATISTICS [dbo].[tblUserRole].[_WA_Sys_RowVersion_3A81B327]
        ///GO
        ///DROP STATISTICS [dbo].[tblUserRole].[_WA_Sys_UserId_3A81B327]
        ///GO
        ///EXECUTE [sp_rename]
        ///	@objname  = N&apos;[dbo].[PK_tblUserRole]&apos;,
        ///	@newname  = N&apos;tmp_4172bdaafdc747af989464be5ff093c9&apos;,
        ///	@objtype  = &apos;OBJECT&apos;
        ///GO
        ///EXECUTE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertUserRoleToIdentity {
            get {
                return ResourceManager.GetString("ConvertUserRoleToIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[tblSidebar]
        ///DROP CONSTRAINT [FK_tblSidebar_tblUser]
        ///ALTER TABLE [dbo].[tblUserSearch]
        ///DROP CONSTRAINT [FK_tblUserSearch_tblUser]
        ///ALTER TABLE [dbo].[tblCredentialApplication]
        ///DROP CONSTRAINT [FK_CredentialApplication_User]
        ///ALTER TABLE [dbo].[tblCredentialApplication]
        ///DROP CONSTRAINT [FK_CredentialApplication_User2]
        ///ALTER TABLE [dbo].[tblCredentialApplication]
        ///DROP CONSTRAINT [FK_CredentialApplication_User3]
        ///ALTER TABLE [dbo].[tblPayroll]
        ///DROP CONSTRAINT [FK_tblPayroll_tblUser] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertUserToIdentity {
            get {
                return ResourceManager.GetString("ConvertUserToIdentity", resourceCulture);
            }
        }
    }
}
