CREATE VIEW dbo.vwIssuedCredentialCredentialRequest 
AS 
SELECT C.CREDENTIALID as CredentialId, MAX(CR.CREDENTIALREQUESTID) as CredentialRequestId
FROM TBLCREDENTIAL C 
INNER JOIN TBLCREDENTIALCREDENTIALREQUEST CCR ON C.CREDENTIALID = CCR.CredentialId
INNER JOIN TBLCREDENTIALREQUEST CR ON CCR.CREDENTIALREQUESTID = CR.CREDENTIALREQUESTID AND CR.CREDENTIALREQUESTSTATUSTYPEID = 12 -- CERTIFICATION ISSUED
GROUP BY C.CREDENTIALID 
