CREATE VIEW dbo.vwTestMaterialLastUsed 
AS 

SELECT TM.TESTMATERIALID as TestMaterialId, MAX(TSS.TESTDATETIME) as LastUsedDate
FROM TBLTESTMATERIAL TM 
LEFT JOIN TBLTESTSITTINGTESTMATERIAL TSTM ON TM.TESTMATERIALID = TSTM.TESTMATERIALID
LEFT JOIN TBLTESTSITTING TS ON TS.TESTSITTINGID = TSTM.TESTSITTINGID AND  TS.REJECTED = 0 AND TS.SAT = 1
LEFT JOIN TBLTESTSESSION TSS ON TSS.TESTSESSIONID = TS.TESTSESSIONID 
GROUP BY TM.TESTMATERIALID
