CREATE VIEW dbo.vwTestMaterialRequestRoundLatest 
AS 

SELECT MRR.MATERIALREQUESTID AS MATERIALREQUESTID, MAX(MRR.MATERIALREQUESTROUNDID) AS LATESTMATERIALROUNDID FROM TBLMATERIALREQUESTROUND MRR
INNER JOIN TBLMATERIALREQUEST MR ON MR.MATERIALREQUESTID = MRR.MATERIALREQUESTID
GROUP BY MRR.MATERIALREQUESTID