//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Bl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Bl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationTypeId not provided..
        /// </summary>
        internal static string ApplicationTypeIdValidation {
            get {
                return ResourceManager.GetString("ApplicationTypeIdValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CredentialTypeId not provided..
        /// </summary>
        internal static string CredentialTypeIdValidation {
            get {
                return ResourceManager.GetString("CredentialTypeIdValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one supplementary test fee found for the application type with the same credential type..
        /// </summary>
        internal static string ProductFeeValidationWithCredentialTypeForSupplementaryTest {
            get {
                return ResourceManager.GetString("ProductFeeValidationWithCredentialTypeForSupplementaryTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one test fee found for the application type with the same credential type..
        /// </summary>
        internal static string ProductFeeValidationWithCredentialTypeForTest {
            get {
                return ResourceManager.GetString("ProductFeeValidationWithCredentialTypeForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one supplementary test fee found for the application type without a credential type..
        /// </summary>
        internal static string ProductFeeValidationWithNoCredentialTypeForSupplementaryTest {
            get {
                return ResourceManager.GetString("ProductFeeValidationWithNoCredentialTypeForSupplementaryTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one test fee found for the application type without a credential type..
        /// </summary>
        internal static string ProductFeeValidationWithNoCredentialTypeForTest {
            get {
                return ResourceManager.GetString("ProductFeeValidationWithNoCredentialTypeForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
