SET IDENTITY_INSERT [dbo].[tblCredentialApplicationField] ON 

INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (13, 2, NULL, N'Training', N'Requirements', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                    
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (14, 2, NULL, N'Auslan Proficiency', N'Requirements', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                   
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (15, 2, NULL, N'English Proficiency', N'Requirements', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                             
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (16, 2, NULL, N'Ethical Competency', N'Ethics and Intercultural', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (17, 2, NULL, N'Intercultural Competency', N'Ethics and Intercultural', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                       
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (18, 2, NULL, N'To Work in the Industry', N'Reason for NAATI Credential (Mandatory)', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (19, 2, NULL, N'Skills Assessment', N'Reason for NAATI Credential (Mandatory)', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                         
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (20, 2, NULL, N'Obtain CCL Points', N'Reason for NAATI Credential (Mandatory)', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                       
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (21, 2, NULL, N'Endorsed Qualification', N'Qualifications', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                      
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (22, 2, NULL, N'Non Endorsed Qualification', N'Qualifications', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (23, 2, NULL, N'Approved Course', N'Qualifications', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (24, 2, NULL, N'Qualification Name', N'Endorsed Qualification Details', 2, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (25, 2, NULL, N'Institution', N'Endorsed Qualification Details', 2, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (26, 2, NULL, N'Student ID', N'Endorsed Qualification Details', 2, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (27, 2, NULL, N'Qualification Start Date', N'Endorsed Qualification Details', 3, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                      
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (28, 2, NULL, N'Qualification Completion Date', N'Endorsed Qualification Details', 3, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                       
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (29, 2, NULL, N'More than 3 Years', N'Endorsed Qualification Details', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                        
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (30, 2, NULL, N'AIIC', N'Membership (for Certified Advanced Translator and Certified Conference Interpreter only)', 1, NULL, 0, N'', 0, NULL)
                                                                                                                                                                                                                                                       
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (31, 2, NULL, N'AITC', N'Membership (for Certified Advanced Translator and Certified Conference Interpreter only)', 1, NULL, 0, N'`', 0, NULL)

INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (32, 3, NULL, N'Obtain CCL Points', N'General', 1, NULL, 0, N'', 1, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (33, 3, NULL, N'Sponsored Application', N'Sponsor Organisation', 1, NULL, 0, N'', 1, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (34, 3, NULL, N'Organisation Name', N'Sponsor Organisation', 2, NULL, 0, N'', 0, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (35, 3, NULL, N'Contact Person Name', N'Sponsor Organisation', 2, NULL, 0, N'', 0, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (36, 3, NULL, N'Contact Person Email', N'Sponsor Organisation', 2, NULL, 0, N'', 0, NULL)

INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (37, 2, NULL, N'Sponsored Application', N'Sponsor Organisation', 1, NULL, 0, N'', 1, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (38, 2, NULL, N'Organisation Name', N'Sponsor Organisation', 2, NULL, 0, N'', 0, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (39, 2, NULL, N'Contact Person Name', N'Sponsor Organisation', 2, NULL, 0, N'', 0, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (40, 2, NULL, N'Contact Person Email', N'Sponsor Organisation', 2, NULL, 0, N'', 0, NULL)

INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (41, 2, NULL, N'Qualification Name', N'Non-Endorsed Qualification Details', 2, NULL, 0, N'', 0, NULL)
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (42, 2, NULL, N'Institution', N'Non-Endorsed Qualification Details', 2, NULL, 0, N'', 0, NULL)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (43, 2, NULL, N'Qualification Completion Date', N'Non-Endorsed Qualification Details', 3, NULL, 0, N'', 0, NULL)

INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (44, 2, NULL, N'Student ID', N'Non-Endorsed Qualification Details', 2, NULL, 0, N'', 0, NULL)
SET IDENTITY_INSERT [dbo].[tblCredentialApplicationField] OFF
