//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.NAATI._20171017_InitialDataPopulationNov {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.NAATI._20171017_InitialDataPopulationNov.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationField] ON 
        ///
        ///INSERT [dbo].[tblCredentialApplicationField] ([CredentialApplicationFieldId], [CredentialApplicationTypeId], [Reference], [Name], [Section], [DataTypeId], [DefaultValue], [PerCredentialRequest], [Description], [Mandatory], [DisplayOrder]) VALUES (13, 2, NULL, N&apos;Training&apos;, N&apos;Requirements&apos;, 1, NULL, 0, N&apos;&apos;, 0, NULL)
        ///                                                                                                                                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFieldInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFieldInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormActionType] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormActionType] ([CredentialApplicationFormActionTypeId], [Name], [DisplayName]) VALUES (1, N&apos;Delete&apos;, N&apos;Delete&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormActionType] ([CredentialApplicationFormActionTypeId], [Name], [DisplayName]) VALUES (2, N&apos;Redirect&apos;, N&apos;Redirect&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormActionType] ([CredentialApplicationFormActionTypeId], [Name], [DisplayName]) V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormActionTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormActionTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormAnswerOptionActionType] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerOptionActionType] ([CredentialApplicationFormAnswerOptionActionTypeId], [CredentialApplicationFormAnswerOptionId], [CredentialApplicationFormActionTypeId], [Parameter], [Order]) VALUES (1, 1, 1, N&apos;[[ExternalUrl_Applications_URL]]/2&apos;, 0)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerOptionActionType] ([CredentialApplicationFormAnswerOptionActionTypeId], [CredentialAppli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormAnswerOptionActionTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormAnswerOptionActionTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormAnswerOptionDocumentType] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerOptionDocumentType] ([CredentialApplicationFormAnswerOptionDocumentTypeId], [CredentialApplicationFormAnswerOptionId], [DocumentTypeId]) VALUES (1, 17, 11)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerOptionDocumentType] ([CredentialApplicationFormAnswerOptionDocumentTypeId], [CredentialApplicationFormAnswerOptionId], [DocumentTypeId]) VALUES (2, 19, 15)
        ///
        ///INSERT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormAnswerOptionDocumentTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormAnswerOptionDocumentTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormAnswerOption] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerOption] ([CredentialApplicationFormAnswerOptionId], [Option], [CredentialApplicationFormQuestionTypeId], [Description]) VALUES (1, N&apos;To work as a translator or interpreter&apos;, 1, N&apos;If you wish to work as a translator or interpreter, you will need to apply for certification instead.  Click &lt;b&gt;Finish&lt;/b&gt; to be redirected to the correct application.&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormAnswerOptionInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormAnswerOptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormAnswerType] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerType] ([CredentialApplicationFormAnswerTypeId], [Name], [DisplayName]) VALUES (1, N&apos;RadioOptions&apos;, N&apos;Radio Options&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerType] ([CredentialApplicationFormAnswerTypeId], [Name], [DisplayName]) VALUES (2, N&apos;CheckOptions&apos;, N&apos;Check Options&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormAnswerType] ([CredentialApplicationFormAnswerTypeId], [Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormAnswerTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormAnswerTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[tblCredentialApplicationForm] ON 
        ///
        ///INSERT [dbo].[tblCredentialApplicationForm] ([CredentialApplicationFormId], [CredentialApplicationTypeId], [Name], [Description], [LoginRequired]) VALUES (1, 3, N&apos;CCL Testing&apos;, N&apos;CCL Application&apos;, 0)
        ///
        ///INSERT [dbo].[tblCredentialApplicationForm] ([CredentialApplicationFormId], [CredentialApplicationTypeId], [Name], [Description], [LoginRequired]) VALUES (2, 2, N&apos;Certification &amp; Recognised Practising&apos;, N&apos;Certification Application&apos;, 0)
        ///
        ///SET  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormQuestionAnswerOption] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestionAnswerOption] ([CredentialApplicationFormQuestionAnswerOptionId], [CredentialApplicationFormQuestionId], [CredentialApplicationFormAnswerOptionId], [DefaultAnswer], [CredentialApplicationFieldId], [DisplayOrder], [CredentialApplicationFieldOptionOptionId], [FieldData]) VALUES (1, 1, 1, 0, NULL, 0, NULL, NULL)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestionAnswerOption [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormQuestionAnswerOptionInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormQuestionAnswerOptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormQuestion] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestion] ([CredentialApplicationFormQuestionId], [CredentialApplicationFormSectionId], [CredentialApplicationFormQuestionTypeId], [CredentialApplicationFieldId], [DisplayOrder]) VALUES (1, 1, 1, NULL, 0)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestion] ([CredentialApplicationFormQuestionId], [CredentialApplicationFormSectionId], [CredentialApplicationFormQuestionTypeId], [CredentialAppl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormQuestionInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormQuestionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormQuestionLogic] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestionLogic] ([CredentialApplicationFormQuestionLogicId], [CredentialApplicationFormQuestionId], [CredentialApplicationFormQuestionAnswerOptionId], [Not], [And]) VALUES (1, 10, 8, 0, 0)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestionLogic] ([CredentialApplicationFormQuestionLogicId], [CredentialApplicationFormQuestionId], [CredentialApplicationFormQuestionAnswerOptionId], [Not], [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormQuestionLogicInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormQuestionLogicInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormQuestionType] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestionType] ([CredentialApplicationFormQuestionTypeId], [Text], [CredentialApplicationFormAnswerTypeId], [Description]) VALUES (1, N&apos;Why are you taking this test?&apos;, 1, N&apos;&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormQuestionType] ([CredentialApplicationFormQuestionTypeId], [Text], [CredentialApplicationFormAnswerTypeId], [Description]) VALUES (2, N&apos;&apos;, 5, N&apos;You will need to upload a cop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormQuestionTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormQuestionTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationFormSection] ON 
        ///
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormSection] ([CredentialApplicationFormSectionId], [CredentialApplicationFormId], [Name], [DisplayOrder], [Description]) VALUES (1, 1, N&apos;Application Selection&apos;, 1, N&apos;&apos;)
        ///
        ///INSERT [dbo].[tblCredentialApplicationFormSection] ([CredentialApplicationFormSectionId], [CredentialApplicationFormId], [Name], [DisplayOrder], [Description]) VALUES (2, 1, N&apos;Person Details&apos;, 0, N&apos;&apos;)
        ///
        ///INSERT [dbo].[tblCredent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationFormSectionInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationFormSectionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblCredentialApplicationType ON
        ///INSERT INTO tblCredentialApplicationType (CredentialApplicationTypeId, Name, DisplayName, Online, BackOffice, RequiresChecking, RequiresAssessment, PendingAllowed, AssessmentReviewAllowed) VALUES (2, &apos;Certification&apos;, &apos;Certification&apos;, 1, 0, 1, 1, 1, 0)
        ///INSERT INTO tblCredentialApplicationType (CredentialApplicationTypeId, Name, DisplayName, Online, BackOffice, RequiresChecking, RequiresAssessment, PendingAllowed, AssessmentReviewAllowed) VALUES (3, &apos;CCL&apos;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationStatusType] ON 
        ///
        ///INSERT [dbo].[tblCredentialApplicationStatusType] ([CredentialApplicationStatusTypeId], [Name], [DisplayName]) VALUES (7, N&apos;Deleted&apos;, N&apos;Deleted&apos;)
        ///
        ///SET IDENTITY_INSERT [dbo].[tblCredentialApplicationStatusType] OFF
        ///.
        /// </summary>
        internal static string CredentialApplicationStatusTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationStatusTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT tblCredentialApplicationTypeCredentialType ON
        ///INSERT INTO tblCredentialApplicationTypeCredentialType (CredentialApplicationTypeCredentialTypeId, CredentialApplicationTypeId, CredentialTypeId, HasTest) VALUES (14, 2, 2, 1)
        ///INSERT INTO tblCredentialApplicationTypeCredentialType (CredentialApplicationTypeCredentialTypeId, CredentialApplicationTypeId, CredentialTypeId, HasTest) VALUES (15, 2, 6, 1)
        ///INSERT INTO tblCredentialApplicationTypeCredentialType (CredentialApplicationTypeCredential [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationTypeCredentialTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationTypeCredentialTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblCredentialApplicationTypeDocumentType] ON 
        ///INSERT INTO [dbo].[tblCredentialApplicationTypeDocumentType] ([CredentialApplicationTypeDocumentTypeId],[CredentialApplicationTypeId],[DocumentTypeId] ,[Mandatory])  VALUES (5,2,9,1)
        ///INSERT INTO [dbo].[tblCredentialApplicationTypeDocumentType] ([CredentialApplicationTypeDocumentTypeId],[CredentialApplicationTypeId],[DocumentTypeId] ,[Mandatory])  VALUES (6,2,10,0)
        ///INSERT INTO [dbo].[tblCredentialApplicationTypeDocumentType] ([Creden [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialApplicationTypeDocumentTypeInsert {
            get {
                return ResourceManager.GetString("CredentialApplicationTypeDocumentTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into tblStoredFile (
        ///   ExternalFileId
        ///  ,FileSize
        ///  ,[FileName]
        ///  ,UploadedByPersonId
        ///  ,UploadedByUserId
        ///  ,UploadedDateTime
        ///  ,DocumentTypeId
        ///) VALUES 
        ///   (N&apos;CredentialLetterTemplate\TranslatorCredentialLetterTemplate.docx&apos;,138075,&apos;TranslatorCredentialLetterTemplate.docx&apos;,NULL,40,GETDATE(),22),
        ///   (N&apos;CredentialLetterTemplate\InterpreterCredentialLetterTemplate.docx&apos;,141385,&apos;InterpreterCredentialLetterTemplate.docx&apos;,NULL,40,GETDATE(),22),
        ///   (N&apos;CertificateTemplate\CredentialCertificateTe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialTypeTemplateInsert {
            get {
                return ResourceManager.GetString("CredentialTypeTemplateInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tblDataType] ON 
        ///
        ///
        ///INSERT [dbo].[tblDataType] ([DataTypeId], [Name], [DisplayName]) VALUES (2, N&apos;Text&apos;, N&apos;Text&apos;)
        ///
        ///INSERT [dbo].[tblDataType] ([DataTypeId], [Name], [DisplayName]) VALUES (3, N&apos;Date&apos;, N&apos;Date&apos;)
        ///
        ///INSERT [dbo].[tblDataType] ([DataTypeId], [Name], [DisplayName]) VALUES (4, N&apos;CountryLookup&apos;, N&apos;CountryLookup&apos;)
        ///
        ///INSERT [dbo].[tblDataType] ([DataTypeId], [Name], [DisplayName]) VALUES (5, N&apos;Options&apos;, N&apos;Options&apos;)
        ///
        ///SET IDENTITY_INSERT [dbo].[tblDataType] OFF
        ///.
        /// </summary>
        internal static string DataTypeInsert {
            get {
                return ResourceManager.GetString("DataTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[tluDocumentType] ON 
        ///
        ///
        ///INSERT [dbo].[tluDocumentType] ([DocumentTypeId], [Name], [DisplayName], [ExaminerToolsDownload],[ExaminerToolsUpload], [DocumentTypeCategoryId]) VALUES (24, N&apos;PurchaseOrder&apos;, N&apos;Purchase Order&apos;,0,0,2)
        ///
        ///
        ///SET IDENTITY_INSERT [dbo].[tluDocumentType] OFF.
        /// </summary>
        internal static string DocumentTypeInsert {
            get {
                return ResourceManager.GetString("DocumentTypeInsert", resourceCulture);
            }
        }
    }
}
