//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.ReportsScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.ReportsScripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[ApplicationCustomFields] AS
        ///SELECT
        ///	[ApplicationCustomFieldId] 
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]	
        ///	,[PersonId]
        ///	,[ApplicationId]
        ///	,[ApplicationType]
        ///	,[ApplicationStatus]
        ///	,[ApplicationStatusModifiedDate]
        ///	,[ApplicationEnteredDate]
        ///	,[Section]
        ///	,[FieldName]
        ///	,[Type]
        ///	,[Value]	
        ///FROM [ApplicationCustomFieldsLatest] a
        ///--FROM [ApplicationCustomFieldsHistory] a
        ///--where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string ApplicationCustomFieldsView {
            get {
                return ResourceManager.GetString("ApplicationCustomFieldsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Application] AS
        ///SELECT
        ///	[ApplicationId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[PersonId]
        ///	,[NAATINumber]
        ///	,[PractitionerNumber]
        ///	,[EnteredDate]
        ///	,[EnteredOffice]
        ///	,[ApplicationStatus]
        ///	,[StatusDateModified]
        ///	,[Sponsor]
        ///	,[Title]
        ///	,[GivenName]
        ///	,[OtherNames]
        ///	,[FamilyName]
        ///	,[PrimaryAddress]
        ///	,[State]
        ///	,[Postcode]
        ///	,[Country]
        ///	,[PrimaryPhone]
        ///	,[PrimaryEmail]
        ///	,[ApplicationType]
        ///	,[ApplicationReference]
        ///	,[ApplicationOwner]
        ///	,[EnteredUser] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApplicationView {
            get {
                return ResourceManager.GetString("ApplicationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[CredentialRequests] AS
        ///SELECT
        ///	[CredentialRequestId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[PersonId]
        ///	,[NAATINumber]
        ///	,[PractitionerNumber]
        ///	,[Title]
        ///	,[GivenName]
        ///	,[OtherNames]
        ///	,[FamilyName]
        ///	,[PrimaryAddress]
        ///	,[State]
        ///	,[Postcode]
        ///	,[Country]
        ///	,[PrimaryPhone]
        ///	,[PrimaryEmail]
        ///	,[ApplicationId]
        ///	,[ApplicationType]
        ///	,[ApplicationReference]
        ///	,[ApplicationOwner]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[Certificatio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CredentialRequestsView {
            get {
                return ResourceManager.GetString("CredentialRequestsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Credentials] AS
        ///SELECT
        ///	[CredentialId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[PersonId]
        ///	,[NAATINumber]
        ///	,[PractitionerNumber]
        ///	,[Title]
        ///	,[GivenName]
        ///	,[OtherNames]
        ///	,[FamilyName]
        ///	,[PrimaryAddress]
        ///	,[State]
        ///	,[Postcode]
        ///	,[Country]
        ///	,[PrimaryPhone]
        ///	,[PrimaryEmail]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[Language1]
        ///	,[Language1Code]
        ///	,[Language1Group]
        ///	,[Language2]
        ///	,[Language2Code]
        ///	,[Language2Group]
        ///	,[Certif [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CredentialsView {
            get {
                return ResourceManager.GetString("CredentialsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[EndorsedQualification] AS
        ///SELECT
        ///	[EndorsedQualificationId]
        ///	,[InstitutionId]
        ///	,[NAATINumber]
        ///	,[InstitutionName]
        ///	,[Location]
        ///	,[Qualification]
        ///	,[CredentialTypeId]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[EndorsementPeriodFrom]
        ///	,[EndorsementPeriodTo]
        ///	,[Notes]
        ///	,[Active]
        ///	
        ///FROM [EndorsedQualificationHistory] a
        ///where [RowStatus] = &apos;Latest&apos;
        ///.
        /// </summary>
        public static string EndorsedQualificationView {
            get {
                return ResourceManager.GetString("EndorsedQualificationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[ExaminerJob] AS
        ///SELECT
        ///	[JobExaminerId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[TestSittingId]
        ///	,[JobId]
        ///	,[ApplicationTypeId]
        ///	,[ApplicationType]
        ///	,[ExaminerCustomerNumber]
        ///	,[CredentialTypeId]
        ///	,[CredentialType]
        ///	,[SkillId]
        ///	,[Skill]
        ///	,[DateAllocated]
        ///	,[ReceivedDate]
        ///	,[DueDate]
        ///	,[ExaminerCost]
        ///	,[ProductSpecificationId]
        ///	,[ProductSpecificationCode]
        ///	,[ProductSpecificationDescription]
        ///	,[GLCodeId]
        ///	,[GLCode]
        ///	,[ExaminerPayRollStatusId]
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExaminerJobView {
            get {
                return ResourceManager.GetString("ExaminerJobView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION [dbo].[GetDates]
        ///(
        ///	@startDate datetime,
        ///	@endDate datetime
        ///)
        ///RETURNS TABLE 
        ///AS
        ///RETURN 
        ///(
        ///	SELECT TOP (DATEDIFF(DAY, @startDate, @endDate) + 1)
        ///        Date = DATEADD(DAY, ROW_NUMBER() OVER(ORDER BY a.object_id) - 1, @startDate)
        ///	FROM    sys.all_objects a
        ///			CROSS JOIN sys.all_objects b
        ///)
        ///.
        /// </summary>
        public static string GetDates {
            get {
                return ResourceManager.GetString("GetDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION [dbo].[GetExaminerComponentMarks]
        ///(
        ///	@testResultId int
        ///)
        ///RETURNS TABLE 
        ///AS
        ///RETURN 
        ///(
        ///	SELECT
        ///		etcr.[Mark]
        ///		,etcr.[TotalMarks]
        ///		,em.[JobExaminerId]
        ///		,etcr.[ComponentNumber]
        ///	FROM [naati_db]..[tblExaminerTestComponentResult] etcr
        ///	INNER JOIN [naati_db]..[tblExaminerMarking] em ON em.[ExaminerMarkingID] = etcr.[ExaminerMarkingID]
        ///	INNER JOIN [naati_db]..[tblTestResult] tr ON tr.[TestResultID] = em.[TestResultID]
        ///	WHERE tr.[TestResultId] = @testResultId
        ///)
        ///.
        /// </summary>
        public static string GetExaminerComponentMarks {
            get {
                return ResourceManager.GetString("GetExaminerComponentMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION [dbo].[GetExaminerOverallMark]
        ///(
        ///	@testResultId int,
        ///	@jobExaminerId int
        ///)
        ///RETURNS TABLE 
        ///AS
        ///RETURN 
        ///(
        ///	SELECT
        ///		[OverallMark] AS &apos;ExaminerOverallMark&apos;
        ///		,[TotalMarks] AS &apos;ExaminerTotalMarks&apos;
        ///	FROM
        ///	(
        ///		SELECT
        ///			tr2.[TestResultId]
        ///			,componentMarks.[JobExaminerId]
        ///			,SUM(componentMarks.[Mark]) AS &apos;OverallMark&apos;
        ///			,SUM(componentMarks.[TotalMarks]) AS &apos;TotalMarks&apos;
        ///		FROM [naati_db]..[tblTestResult] tr2
        ///		OUTER APPLY [dbo].[GetExaminerComponentMarks](tr2.[TestResultId]) co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetExaminerOverallMark {
            get {
                return ResourceManager.GetString("GetExaminerOverallMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION [dbo].[GetPhoneNumber]
        ///(
        ///	@entityId int
        ///	,@PrimaryContact bit
        ///)
        ///RETURNS TABLE
        ///AS
        ///RETURN
        ///(
        ///	SELECT TOP 1
        ///		[Number]
        ///		,[Invalid]
        ///	FROM [naati_db]..[tblPhone] phone
        ///	WHERE phone.[EntityId] = @entityId AND phone.[PrimaryContact] = @PrimaryContact AND phone.[Invalid] = 0
        ///)
        ///.
        /// </summary>
        public static string GetPhoneNumber {
            get {
                return ResourceManager.GetString("GetPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION [dbo].[GetSystemValue](@ValueKey varchar(80))
        ///RETURNS varchar(max)
        ///AS 
        ///BEGIN
        ///    Declare @Value varchar(max)
        ///	select @Value = [Value] from tblSystemValue where ValueKey = @ValueKey
        ///    RETURN  @Value
        ///END;.
        /// </summary>
        public static string GetSystemValue {
            get {
                return ResourceManager.GetString("GetSystemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION [dbo].[GetTestResultOverallMark]
        ///(
        ///	@testResultId int
        ///)
        ///RETURNS TABLE 
        ///AS
        ///RETURN 
        ///(
        ///	SELECT
        ///		SUM([Mark]) AS &apos;TestResultOverallMark&apos;
        ///	FROM [naati_db]..[tblTestComponentResult]
        ///	WHERE [TestResultId] = @testResultId
        ///	GROUP BY [TestResultId]
        ///)
        ///.
        /// </summary>
        public static string GetTestResultOverallMark {
            get {
                return ResourceManager.GetString("GetTestResultOverallMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER Procedure LogExecutionError(@EntityName varchar(200), @Message varchar(Max))
        ///AS
        ///BEGIN
        ///	
        ///	Insert into tblJobExecutionLog(LogDate,EntityName,Message,JobExecutionLogTypeId) values(GETDATE(),@EntityName,@Message,3)	
        ///	PRINT CONVERT(NVARCHAR(MAX), GETDATE(), 121) + &apos; &apos; + &apos;Error in Entity: &apos; + @EntityName + &apos;. Message: &apos; + @Message
        ///END.
        /// </summary>
        public static string LogExecutionError {
            get {
                return ResourceManager.GetString("LogExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER Procedure LogExecutionInfo(@EntityName varchar(200), @Message varchar(Max))
        ///AS
        ///BEGIN
        ///
        ///	Declare @DisableInfoLog varchar(max)
        ///	set @DisableInfoLog = dbo.GetSystemValue(&apos;DisableInfoLog&apos;)
        ///
        ///	IF @DisableInfoLog &lt;&gt; &apos;1&apos; 
        ///	BEGIN 
        ///		Insert into tblJobExecutionLog(LogDate,EntityName,Message,JobExecutionLogTypeId) values(GETDATE(),@EntityName,@Message,1)		
        ///	END
        ///	
        ///END.
        /// </summary>
        public static string LogExecutionInfo {
            get {
                return ResourceManager.GetString("LogExecutionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER Procedure LogExecutionWarning(@EntityName varchar(200), @Message varchar(Max))
        ///AS
        ///BEGIN
        ///	
        ///	Insert into tblJobExecutionLog(LogDate,EntityName,Message,JobExecutionLogTypeId) values(GETDATE(),@EntityName,@Message,2)	
        ///	PRINT CONVERT(NVARCHAR(MAX), GETDATE(), 121) + &apos; &apos; + &apos;Warning on Entity: &apos; + @EntityName + &apos;. Message: &apos; + @Message
        ///END.
        /// </summary>
        public static string LogExecutionWarning {
            get {
                return ResourceManager.GetString("LogExecutionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[MarkRubric] AS
        ///SELECT
        ///    [TestResultId]
        ///    ,[TestComponentId]
        ///    ,[JobExaminerId]
        ///    ,[RubricAssessementCriterionResultId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[TestSittingId]
        ///	,[TestSessionId]
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[CandidateName]
        ///	,[PaidReview]
        ///	,[Supplementary]
        ///	,[TestTaskTypeLabel]
        ///	,[TestTaskTypeName]
        ///	,[TestTaskLabel]
        ///	,[TestTaskName]
        ///	,[TestTaskNumber]
        ///	,[MarkType]
        ///	,[ResultType]
        ///	,[ExaminerCustomerNo]
        ///	,[ExaminerName]
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarkRubricView {
            get {
                return ResourceManager.GetString("MarkRubricView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Mark] AS
        ///SELECT
        ///    [MarkId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[PersonId]
        ///    ,[TestSittingId]
        ///    ,[TestResultId]
        ///    ,[ComponentName]
        ///    ,[ExaminerNAATINumber]
        ///    ,[ExaminerName]
        ///    ,[ExaminerType]
        ///    ,[Cost]
        ///    ,[PaperLost]
        ///    ,[PaperReceived]
        ///    ,[SentToPayroll]
        ///    ,[IncludeMarks]
        ///    ,[Mark]
        ///    ,[PassMark]
        ///    ,[TotalMark]
        ///    ,[OverallMark]
        ///    ,[OverallPassMark]
        ///    ,[OverallTotalMark]
        ///    ,[PrimaryFailureReason]
        ///    ,[P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarkView {
            get {
                return ResourceManager.GetString("MarkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[MaterialRequest] AS
        ///SELECT
        ///	 [MaterialRequestId]    
        ///	,[PanelId]	
        ///	,[Panel]
        ///	,[SourceMaterialId]
        ///	,[SourceMaterialName]
        ///	,[OutputMaterialId]
        ///	,[OutputMaterialName]
        ///	,[CredentialType]
        ///	,[Skill]
        ///	,[Status]
        ///	,[NumberOfRounds]
        ///	,[MaxBillableHours]
        ///	,[ProductSpecificationName]
        ///	,[GLCode]
        ///	,[CostPerHour]
        ///	,[CreatedDate]
        ///	,[CreatedBy]
        ///	,[OwnedBy]	
        ///FROM [MaterialRequestHistory] tr
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string MaterialRequest {
            get {
                return ResourceManager.GetString("MaterialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[MaterialRequestPanelMember] AS
        ///SELECT	
        ///     [MaterialRequestPanelMembershipId]
        ///    ,[MaterialRequestId]
        ///	,[OutputMaterialName]
        ///	,[PanelMemberShipId]
        ///	,[MemberType]		
        ///FROM [MaterialRequestPanelMemberHistory] tr
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string MaterialRequestPanelMember {
            get {
                return ResourceManager.GetString("MaterialRequestPanelMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[MaterialRequestPayroll] AS
        ///SELECT	
        ///	 [MaterialRequestPayrollId]
        ///	,[PanelMemberShipId] 
        ///	,[MaterialRequestId]
        ///	,[ApprovedDate]
        ///	,[ApprovedByUserId]
        ///	,[PaidByUserId]
        ///	,[PaymentDate]
        ///	,[Amount]
        ///	,[PaymentReference]		
        ///FROM [MaterialRequestPayrollHistory] tr
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string MaterialRequestPayroll {
            get {
                return ResourceManager.GetString("MaterialRequestPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[MaterialRequestRound] AS
        ///SELECT
        ///	 [MaterialRequestRoundId]
        ///    ,[MaterialRequestId]
        ///	,[OutputMaterialName]
        ///	,[DueDate]
        ///	,[RequestedDate]
        ///	,[SubmittedDate]
        ///	,[Status]		
        ///FROM [MaterialRequestRoundHistory] tr
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string MaterialRequestRound {
            get {
                return ResourceManager.GetString("MaterialRequestRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[MaterialRequestTaskHours] AS
        ///SELECT
        ///	 [MaterialRequestPanelMembershipTaskId]
        ///	,[MaterialRequestId]
        ///	,[OutputMaterialName]
        ///	,[PanelMemberShipId]
        ///	,[Task]
        ///	,[Hours]	
        ///FROM [MaterialRequestTaskHoursHistory] tr
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string MaterialRequestTaskHours {
            get {
                return ResourceManager.GetString("MaterialRequestTaskHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[OrganisationContacts] AS
        ///SELECT
        ///	[ContactPersonId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[OrganisationId]
        ///	,[Name]
        ///	,[Email]
        ///	,[Phone]
        ///	,[Address]
        ///	,[Description]
        ///	,[Inactive]	
        ///FROM [OrganisationContactsHistory] 
        ///where [RowStatus] = &apos;Latest&apos;
        ///.
        /// </summary>
        public static string OrganisationContactsView {
            get {
                return ResourceManager.GetString("OrganisationContactsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Organisation] AS
        ///SELECT
        ///	[OrganisationId]
        ///	,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[NAATINumber]
        ///	,[Name]
        ///	,[PrimaryAddress]
        ///	,[Suburb]
        ///	,[Country]
        ///	,[PrimaryPhone]
        ///	,[PrimaryEmail]
        ///	,[TrustedPayer]	
        ///FROM [OrganisationHistory] a
        ///where [RowStatus] = &apos;Latest&apos;
        ///.
        /// </summary>
        public static string OrganisationView {
            get {
                return ResourceManager.GetString("OrganisationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [PanelMembershipCredentialTypes] AS
        ///SELECT
        ///	 [PanelMemberShipCredentialTypeId]
        ///	,[PanelMembershipId]
        ///	,[PanelId]	
        ///	,[PanelName]
        ///	,[Role]
        ///	,[PersonId]
        ///	,[PersonName]
        ///	,[NaatiNumber]	
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]	
        ///	,[ModifiedDate]	
        ///FROM [PanelMembershipCredentialTypesHistory] c
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string PanelMembershipCredentialTypesView {
            get {
                return ResourceManager.GetString("PanelMembershipCredentialTypesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[PanelMembers] AS
        ///SELECT
        ///    [PanelId]
        ///	,[PanelMembersId]
        ///	,[PersonId]
        ///    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///    ,[PersonName]
        ///    ,[NAATINumber]
        ///    ,[Role]
        ///    ,[StartDate]
        ///    ,[EndDate]	
        ///FROM [PanelMembersHistory] a
        ///where [RowStatus] = &apos;Latest&apos;
        ///.
        /// </summary>
        public static string PanelMembersView {
            get {
                return ResourceManager.GetString("PanelMembersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Panel] AS
        ///SELECT
        ///    [PanelId]
        ///    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///    ,[PanelName]
        ///    ,[PanelType]
        ///    ,[Language]
        ///    ,[CommissionedDate]	
        ///FROM [PanelHistory] a
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string PanelView {
            get {
                return ResourceManager.GetString("PanelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Person] AS
        ///SELECT
        ///    [PersonId]
        ///    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[NAATINumber]
        ///	,[PractitionerNumber]
        ///    ,[GivenName]
        ///    ,[OtherNames]
        ///    ,[FamilyName]
        ///    ,[Title]
        ///    ,[Gender]
        ///    ,[DateOfBirth]
        ///    ,[CountryOfBirth]
        ///    ,[PrimaryAddress]
        ///    ,[Suburb]
        ///	,[State]
        ///	,[Postcode]
        ///    ,[Country]
        ///    ,[PrimaryEmail]
        ///    ,[PrimaryPhone]
        ///	,[SecondaryAddress]
        ///	,[SecondaryPhone]
        ///	,[SecondaryEmail]
        ///	,[DoNotSendCorrespondence]
        ///	,[Ethical [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PersonView {
            get {
                return ResourceManager.GetString("PersonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW[dbo].[ProfessionalDevelopment] AS
        ///SELECT
        ///      [ProfessionalDevelopmentActivityId]
        ///    , DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS[DateRecorded]
        ///    , [PersonId]
        ///    , [CustomerNumber]
        ///    , [PractitionerNumber]
        ///	, [ApplicationID]
        ///    , [ApplicationStatus]
        ///    , [CertificationPeriodID]    
        ///    , [CertificationPeriodStartDate]
        ///    , [CertificationPeriodOriginalEndDate]
        ///    , [CertificationPeriodEndDate]    
        ///	, [DateCompleted]
        ///	, [Description]
        ///	, [SectionID]
        ///	, [SectionName]
        ///	, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfessionalDevelopment {
            get {
                return ResourceManager.GetString("ProfessionalDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshop_EndorsedQualification]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @EndorsedQualificationHistory as table([EndorsedQualificationId] [int] NOT NULL,[InstitutionId] [int] NOT NULL,[NAATINumber] [int] NOT NULL,[InstitutionName] [nvarchar](100) NOT NULL,[Location] [nvarchar](200) NOT NULL,[Qualification] [nvarchar](200) NOT NULL,[CredentialTypeId] [int] NOT NULL,
        ///												   [CredentialTypeInternalName] [nvarchar](50) NOT NULL,[CredentialTypeExternalName] [nvarchar](50) NO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshop_EndorsedQualification {
            get {
                return ResourceManager.GetString("ReportingSnapshop_EndorsedQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshop_ExaminerJob]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///
        ///		DECLARE @ExaminerJobHistory as table( [JobExaminerId] [int] NOT NULL,[TestSittingId] [int] NOT NULL,[JobId] [int] NULL,[ApplicationTypeId] [int] NULL,[ApplicationType] [nvarchar](100) NULL,[ExaminerCustomerNumber] [int] NULL,[CredentialTypeId] [int] NULL,[CredentialType] [nvarchar](100) NULL,
        ///										  [SkillId] [int] NULL,[Skill] [nvarchar](300) NULL,[DateAllocated] [datetime] NULL,[ReceivedDate] [datetime] NULL,[DueD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshop_ExaminerJob {
            get {
                return ResourceManager.GetString("ReportingSnapshop_ExaminerJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshop_MaterialRequestPayroll]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @MaterialRequestPayrollHistory as table([MaterialRequestPayrollId] [int] NOT NULL,[PanelMembershipId] [int] NOT NULL,[MaterialRequestId] [int] NOT NULL,[ApprovedDate] [datetime] NULL,[ApprovedByUserId] [int] NULL,[PaidByUserId] [int] NULL,[PaymentDate] [datetime] NULL,
        ///													[Amount] [money] NULL,[PaymentReference] [nvarchar](255) NULL,[ModifiedDate] [datetime] NOT NULL,[RowStatus] nvarchar(50))    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshop_MaterialRequestPayroll {
            get {
                return ResourceManager.GetString("ReportingSnapshop_MaterialRequestPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER PROCEDURE [dbo].[ReportingSnapshop_TestMaterial]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///
        ///DECLARE @TestMaterialHistory as table([TestMaterialId] [int] NOT NULL,[Title] [nvarchar](255) NOT NULL,[LanguageId] [int] NULL,[Language] [nvarchar](50) NULL,[SkillId] [int] NULL,[Skill] [nvarchar](max) NULL,[Available] [bit] NOT NULL,[MaterialRequestId] [int] NULL,
        ///									  [TestMaterialTypeId] [int] NOT NULL,[TestMaterialType] [nvarchar](255) NOT NULL,[TestMaterialDomainId] [int] NOT NULL,[TestMaterialDomain] [nvarc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshop_TestMaterial {
            get {
                return ResourceManager.GetString("ReportingSnapshop_TestMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Application]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @ApplicationHistory as table ([ApplicationId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL DEFAULT GETDATE(),[PersonId] [int] NOT NULL,[EnteredDate] [datetime] NOT NULL,[EnteredOffice] [varchar](100) NOT NULL,[ApplicationStatus] [nvarchar](100) NULL,[StatusDateModified] [datetime] NULL,[Sponsor] [nvarchar](100) NULL,
        ///									  [Title] [nvarchar](50) NULL,[GivenName] [nvarchar](100) NULL,[OtherNames] [nvarchar]( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Application {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Application_Latest]
        ///AS
        ///BEGIN
        ///
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;ApplicationLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO ApplicationLatest FROM ApplicationHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN
        ///			BEGIN TRANSACTION 	
        ///
        ///				--Merge operation Latest
        ///				MERGE ApplicationLatest AS Target USING(select * from ApplicationHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON Target.[ApplicationId] = Source.[ApplicationId] AND Target.RowSta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Application_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Application_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_ApplicationCustomFIelds]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @ApplicationCustomFieldsHistory as table([ApplicationCustomFieldId] [int] NOT NULL,[PersonId] [int] NOT NULL,[ApplicationId] [int] NOT NULL,[ApplicationType] [nvarchar](50) NOT NULL,[ApplicationStatus] [nvarchar](50) NOT NULL,
        ///		[ApplicationStatusModifiedDate] [datetime] NOT NULL,[ApplicationEnteredDate] [datetime] NOT NULL,[Section] [nvarchar](100) NULL,[FieldName] [nvarchar](50) NOT NULL,[Type] [nvarcha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_ApplicationCustomFIelds {
            get {
                return ResourceManager.GetString("ReportingSnapshot_ApplicationCustomFIelds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_ApplicationCustomFields_Latest]
        ///AS
        ///BEGIN
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;ApplicationCustomFieldsLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO ApplicationCustomFieldsLatest FROM ApplicationCustomFieldsHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN	
        ///		BEGIN TRANSACTION
        ///				MERGE ApplicationCustomFieldsHistory AS Target USING(	select * from ApplicationCustomFieldsHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON Target.ApplicationCustomFie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_ApplicationCustomFIelds_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_ApplicationCustomFIelds_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_CredentialRequests]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @CredentialRequestsHistory as table([CredentialRequestId] [int] NOT NULL,[PersonId] [int] NOT NULL,[Title] [nvarchar](50) NULL,[GivenName] [nvarchar](100) NULL,[OtherNames] [nvarchar](100) NULL,[FamilyName] [nvarchar](100) NULL,[PrimaryAddress] [nvarchar](500) NULL,[Country] [nvarchar](50) NULL,
        ///													   [PrimaryEmail] [nvarchar](200) NULL,[PrimaryPhone] [nvarchar](60) NULL,[ApplicationId] [int] NOT NU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_CredentialRequests {
            get {
                return ResourceManager.GetString("ReportingSnapshot_CredentialRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_CredentialRequestsLatest]
        ///
        ///AS
        ///BEGIN
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;CredentialRequestsLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO CredentialRequestsLatest FROM CredentialRequestsHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN		
        ///			BEGIN TRANSACTION
        ///			
        ///			--Merge operation Latest
        ///			MERGE CredentialRequestsHistory AS Target USING(select * from CredentialRequestsHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON Target.CredentialReque [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_CredentialRequests_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_CredentialRequests_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Credentials]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @CredentialsHistory as table([CredentialId] [int] NOT NULL,[PersonId] [int] NOT NULL,[Title] [nvarchar](50) NULL,[GivenName] [nvarchar](100) NULL,[OtherNames] [nvarchar](100) NULL,[FamilyName] [nvarchar](100) NULL,[PrimaryAddress] [nvarchar](500) NULL,[Country] [nvarchar](50) NULL,
        ///									 [PrimaryPhone] [nvarchar](60) NULL,[PrimaryEmail] [nvarchar](200) NULL,[CredentialTypeInternalName] [nvarchar](50) NOT NULL,[Di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Credentials {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Main]	
        ///AS
        ///BEGIN
        ///
        ///	Declare @DisableReportingExecution varchar(max)
        ///	set @DisableReportingExecution = dbo.GetSystemValue(&apos;DisableReportingExecution&apos;)
        ///
        ///	IF @DisableReportingExecution &lt;&gt; &apos;1&apos; 
        ///	BEGIN
        ///		DECLARE @Date datetime = DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)	
        ///	
        ///		EXEC LogExecutionInfo &apos;ReportingSnapshot_Main&apos;,&apos;Exection Started...&apos;
        ///
        ///		EXEC ReportingSnapshot_Runner @Date, &apos;ReportingSnapshop_ExaminerJob&apos;
        ///		EXEC ReportingSnapshot_Runner @Date, &apos;Report [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Main {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Mark]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	
        ///	DECLARE @MarkHistory as table([PersonId] [int] NOT NULL,[TestSittingId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[ExaminerNAATINumber] [int] NULL,[ExaminerName] [nvarchar](252) NULL,[IncludeMarks] [bit] NULL,[MarkId] [int] NOT NULL,[Mark] [float] NULL,[TotalMark] [int] NULL,[OverallMark] [float] NULL,
        ///							  [TestResultId] [int] NULL,[ComponentName] [nvarchar](100) NULL,[ExaminerType] [nvarchar](50) NULL,[Cost] [mone [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Mark {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Mark_Latest]
        ///AS
        ///BEGIN
        ///	
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;MarkLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO MarkLatest FROM MarkHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN	
        ///	
        ///	BEGIN TRANSACTION 
        ///		MERGE MarkLatest AS Target USING(	select * from MarkHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON Target.[MarkId] = Source.[MarkId] AND Target.RowStatus = &apos;Latest&apos; 
        ///		WHEN MATCHED THEN 
        ///		  UPDATE Set     
        ///		  Target.PersonId = Sourc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Mark_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Mark_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_MarkRubric]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	
        ///	DECLARE @MarkRubricHistory as table([TestResultId] [int] NOT NULL,[TestComponentId] [int] NOT NULL,[JobExaminerId] [int] NOT NULL,[RubricAssessementCriterionResultId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[TestSittingId] [int] NULL,[TestSessionId] [int] NULL,[PersonId] [int] NOT NULL,
        ///									[CustomerNo] [int] NULL,[CandidateName] [nvarchar](252) NULL,[PaidReview] [bit] NULL,[Supplementary] [bit] NULL,[TestT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_MarkRubric {
            get {
                return ResourceManager.GetString("ReportingSnapshot_MarkRubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_MarkRubric_Latest]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;MarkRubricLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO MarkRubricLatest FROM MarkRubricHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN
        ///		BEGIN TRANSACTION
        ///			MERGE MarkRubricLatest AS Target USING(select * from MarkRubricHistory where [RowStatus] = &apos;Latest&apos;) AS Source ON (Target.[TestResultId] = Source.[TestResultId] AND Target.[TestComponentId] = Source.[TestCom [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_MarkRubric_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_MarkRubric_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_MaterialRequest]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///
        ///DECLARE @MaterialRequestHistory as table([MaterialRequestId] [int],[PanelId] [int],[Panel] [nvarchar](100) NULL,[OutputMaterialId] [int] NOT NULL,[SourceMaterialId] [int] NULL,[SourceMaterialName] [nvarchar](255) NULL,[OutputMaterialName] [nvarchar](255) NULL,[CredentialType] [nvarchar](255) NULL,
        ///										 [Skill] [nvarchar](4000) NULL,[Status] [nvarchar](255) NULL,[NumberOfRounds] [int] NOT NULL,[MaxBillableHours] [ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_MaterialRequest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_MaterialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_MaterialRequestPanelMember]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///
        ///DECLARE @MaterialRequestPanelMemberHistory as table([MaterialRequestPanelMembershipId] [int] NOT NULL,[MaterialRequestId] [int] NOT NULL,[OutputMaterialName] [nvarchar](255) NULL,[PanelMemberShipId] [int] NOT NULL,[MemberType] [nvarchar](255) NULL,
        ///													[ModifiedDate] [datetime] NOT NULL,	[RowStatus] nvarchar(50))   
        ///
        ///	IF(@Date is NULL)
        ///	set @Date = GETDATE()	
        ///	SELECT @Date = DATEADD(dd, DATEDIFF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_MaterialRequestPanelMember {
            get {
                return ResourceManager.GetString("ReportingSnapshot_MaterialRequestPanelMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_MaterialRequestRound]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @MaterialRequestRoundHistory as table([MaterialRequestRoundId] [int] NOT NULL,[MaterialRequestId] [int] NOT NULL,[OutputMaterialName] [nvarchar](255) NULL,[DueDate] [datetime] NULL,[RequestedDate] [datetime] NULL,[SubmittedDate] [datetime] NULL,[Status] [nvarchar](255) NULL,
        ///												  [ModifiedDate] [datetime] NOT NULL,[RowStatus] nvarchar(50))   
        ///												  												  	
        ///	IF(@Date is NULL)
        ///	set [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_MaterialRequestRound {
            get {
                return ResourceManager.GetString("ReportingSnapshot_MaterialRequestRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_MaterialRequestTaskHours]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @MaterialRequestTaskHoursHistory as table([MaterialRequestPanelMembershipTaskId] [int] NOT NULL,[MaterialRequestId] [int] NOT NULL,[OutputMaterialName] [nvarchar](255) NULL,[PanelMemberShipId] [int] NOT NULL,[Task] [nvarchar](255) NULL,[Hours] [float] NOT NULL,
        ///												  [ModifiedDate] [datetime] NOT NULL, [RowStatus] nvarchar(50))   
        ///
        ///	IF(@Date is NULL)
        ///	set @Date = GETDATE()	
        ///	SELECT @Date = DA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_MaterialRequestTaskHours {
            get {
                return ResourceManager.GetString("ReportingSnapshot_MaterialRequestTaskHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Organisation]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @OrganisationHistory as table( OrganisationId int, NAATINumber int, Name nvarchar(100),PrimaryAddress nvarchar(500),Suburb nvarchar(50),Country nvarchar(50),PrimaryPhone nvarchar(60),PrimaryEmail nvarchar(200),TrustedPayer bit,ModifiedDate datetime not null DEFAULT GETDATE(), [RowStatus] nvarchar(50))   
        ///	
        ///	IF(@Date is NULL)
        ///	set @Date = GETDATE()	
        ///	SELECT @Date = DATEADD(dd, DATEDIFF(dd, 0, @Date), 0) 
        ///
        ///	INSE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Organisation {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_OrganisationContacts]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///
        ///DECLARE @OrganisationContactsHistory as table(ContactPersonId int,OrganisationId int,Name nvarchar(max),Email nvarchar(500),Phone nvarchar(500),Address nvarchar(max),Description nvarchar(max),ModifiedDate datetime not null DEFAULT GETDATE(),[Inactive] [bit] NULL, [RowStatus] nvarchar(50))   
        /// 
        ///IF(@Date is NULL)
        ///	SET @Date = GETDATE()
        ///SET @Date = DATEADD(dd, DATEDIFF(dd, 0, @Date), 0) 
        ///
        ///INSERT into @Organisati [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_OrganisationContacts {
            get {
                return ResourceManager.GetString("ReportingSnapshot_OrganisationContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Panel]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @PanelHistory as table([PanelId] [int] NOT NULL,[PanelName] [nvarchar](100) NULL,[PanelType] [nvarchar](50) NULL,[Language] [nvarchar](50) NULL,[CommissionedDate] [datetime] NULL,	ModifiedDate datetime not null DEFAULT GETDATE(), [RowStatus] nvarchar(50))   
        ///	
        ///	
        ///	IF(@Date is NULL)
        ///	set @Date = GETDATE()
        ///	SELECT @Date = DATEADD(dd, DATEDIFF(dd, 0, @Date), 0) 
        ///
        ///	INSERT into @PanelHistory
        ///SELECT
        ///		CASE WHEN [Source]. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Panel {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_PanelMembers]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @PanelMembersHistory as table([PanelMembersId] [int] NOT NULL,[PanelId] [int] NOT NULL,[PersonName] [nvarchar](252) NULL,[ModifiedDate] [datetime] NOT NULL,[NAATINumber] [nvarchar](50) NOT NULL,[Role] [nvarchar](50) NULL,[StartDate] [datetime] NOT NULL,[EndDate] [datetime] NULL,
        ///									      [PersonId] [int] NOT NULL, [RowStatus] nvarchar(50))   
        ///	
        ///	IF(@Date is NULL)
        ///	set @Date = GETDATE()	
        ///	SELECT @Date = DA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_PanelMembers {
            get {
                return ResourceManager.GetString("ReportingSnapshot_PanelMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_PanelMembershipCredentialTypes]
        ///	@Date DateTime
        ///AS
        ///BEGIN	
        ///DECLARE @PanelMembershipCredentialTypesHistory as table([PanelMemberShipCredentialTypeId] [int] NOT NULL,[PanelMembershipId] [int] NOT NULL,[PanelId] [int] NOT NULL,[PanelName] [nvarchar](200) NULL,[Role] [nvarchar](200) NULL,[PersonId] [int] NOT NULL,[PersonName] [nvarchar](400) NOT NULL,[NaatiNumber] [int] NOT NULL,
        ///														[CredentialTypeInternalName] [nvarchar](200) NOT NULL,[CredentialTypeExter [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_PanelMembershipCredentialTypes {
            get {
                return ResourceManager.GetString("ReportingSnapshot_PanelMembershipCredentialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Person]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @PersonHistory as table([PersonId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[GivenName] [varchar](100) NULL,[OtherNames] [varchar](100) NULL,[FamilyName] [varchar](100) NULL,[Title] [varchar](50) NULL,[Gender] [char](1) NOT NULL,[DateOfBirth] [datetime] NULL,
        ///									[CountryOfBirth] [varchar](50) NULL,[PrimaryAddress] [nvarchar](500) NULL,[Country] [varchar](50) NULL,[PrimaryEmail] [nvarchar](200) NULL,[Primary [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Person {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_ProfessionalDevelopment]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @ProfessionalDevelopmentHistory as table([ProfessionalDevelopmentActivityId] [int] NOT NULL,[PersonId] [int] NOT NULL,[CustomerNumber] [int] NOT NULL,[PractitionerNumber] [nvarchar](50) NOT NULL,	[ApplicationID] [int] NOT NULL,	[ApplicationStatus] [nvarchar](100) NULL,
        ///										         [CertificationPeriodID] [int] NOT NULL,[CertificationPeriodStartDate] [datetime] NULL,[CertificationPeriodOriginalEndDa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_ProfessionalDevelopment {
            get {
                return ResourceManager.GetString("ReportingSnapshot_ProfessionalDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_Runner]	
        /// @Date datetime, @StoreProcedureName varchar(200)
        ///AS
        ///BEGIN
        ///	
        ///	BEGIN TRY
        ///		
        ///		Declare @DisableReportingExecution varchar(max)
        ///		set @DisableReportingExecution = dbo.GetSystemValue(&apos;DisableReportingExecution&apos;)
        ///
        ///		IF @DisableReportingExecution &lt;&gt; &apos;1&apos; 
        ///		BEGIN
        ///			EXEC LogExecutionInfo @StoreProcedureName,&apos;Running...&apos;
        ///			EXEC @StoreProcedureName @Date;	
        ///			EXEC LogExecutionInfo @StoreProcedureName,&apos;Finished.&apos;
        ///		END
        ///		ELSE
        ///		BEGIN
        ///			EXEC LogExec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Runner {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Runner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE ReportingSnapshot_Test
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @TestHistory as table([TestSittingId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[CredentialRequestId] [int] NULL,[TestResultId] [int] NULL,[CredentialApplicationId] [int] NOT NULL,[PersonId] [int] NOT NULL,[Rejected] [bit] NOT NULL,[Sat] [bit] NULL,[ResultType] [varchar](50) NULL,
        ///							  [ThirdExaminerRequired] [bit] NULL,[ProcessedDate] [datetime] NULL,[SatDate] [datetime] NULL,[ResultChecked] [bit] NULL,[Venue] [nvarcha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Test {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE ReportingSnapshot_Test_Latest
        ///AS
        ///BEGIN
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;TestLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO TestLatest FROM TestHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN	
        ///	BEGIN TRANSACTION
        ///
        ///		MERGE TestLatest AS Target USING(select * from TestHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON (Target.[TestSittingId] = Source.[TestSittingId] AND Target.[CredentialRequestId] = Source.[CredentialRequestId] And (ISNULL(Target.[TestResultId],0) =  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_Test_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_Test_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestResult]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @TestResultHistory as table([TestResultId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[PersonId] [int] NULL,[TestSittingId] [int] NULL,[ResultDueDate] [datetime] NULL,[LanguageName1] [nvarchar](50) NULL,[CandidateName] [nvarchar](252) NULL,
        ///									[NAATINumber] [int] NULL,[NAATINumberDisplay] [nvarchar](50) NULL,[PaidReview] [bit] NULL,[TotalMarks] [float] NULL,[PassMark] [float] NULL,[TotalCost] [money] NULL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestResult {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestResult_Latest]
        ///AS
        ///BEGIN
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;TestResultLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO TestResultLatest FROM TestResultHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN	
        ///	BEGIN TRANSACTION
        ///	
        ///		--Merge operation Latest
        ///		MERGE TestResultLatest AS Target USING(select * from TestResultHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON Target.[TestResultId] = Source.[TestResultId] AND Target.RowStatus = &apos;Latest&apos;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestResult_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestResult_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestResultExaminerRubricMarkingHistory]
        ///	@Date DateTime -- this is here because of the snapshot runner, it is not used in this stored procedure 
        ///-- rubric marking
        ///AS
        ///
        ///-- Extract
        ///
        ///DECLARE @LastRun as DateTime;
        ///DECLARE @NextRun as DateTime;
        ///
        ///SELECT @NextRun = GetDate();
        ///
        ///SELECT @LastRun = CONVERT(datetime, [Value], 126) --126 here is ISO 8601 format for date which is what is used in system value table
        ///FROM  
        ///	[naati_db]..tblSystemValue 
        ///WHERE 
        ///	ValueKey [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestResultExaminerRubricMarkingHistory {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestResultExaminerRubricMarkingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE ReportingSnapshot_TestResultExaminerStandardMarkingHistory
        ///	@Date DateTime -- this is here because of the snapshot runner, it is not used in this stored procedure
        ///-- standard marking
        ///AS
        ///
        ///-- Extract
        ///
        ///DECLARE @LastRun as DateTime;
        ///DECLARE @NextRun as DateTime;
        ///
        ///SELECT @NextRun = GetDate();
        ///
        ///SELECT  @LastRun = CONVERT(datetime,[Value], 126) FROM  [naati_db]..tblSystemValue WHERE ValueKey = &apos;TestResultExaminerStandardMarkingHistory_LastRun&apos;
        ///
        ///DROP TABLE IF EXISTS #tmpExtract;
        ///
        ///SEL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestResultExaminerStandardMarkingHistory {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestResultExaminerStandardMarkingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestResultRubric]
        ///	@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @TestResultRubricHistory as table([TestResultId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[TestSittingId] [int] NULL,[TestSessionId] [int] NULL,[PersonId] [int] NULL,[CustomerNo] [int] NULL,[CandidateName] [nvarchar](252) NULL,[ResultDueDate] [datetime] NULL,
        ///											  [Language1] [nvarchar](50) NULL,[Language1Code] [nvarchar](10) NULL,[Language1Group] [nvarchar](100) NULL,[Language2] [nvarchar](50)  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestResultRubric {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestResultRubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestSessionRolePlayer]
        ///	@Date DateTime
        ///AS
        ///BEGIN	
        ///	DECLARE @TestSessionRolePlayerHistory as table(	[TestSessionRolePlayerId] [int] NOT NULL,[TestSessionId] [int] NOT NULL,[TestSessionName] [nvarchar](200) NULL,	[TestLocationName] [nvarchar](1000) NULL,[TestLocationState] [nvarchar](50) NULL,[TestLocationCountry] [nvarchar](50) NULL,
        ///	[TestDate] [datetime] NULL,[CredentialTypeInternalName] [nvarchar](100) NULL,[CredentialTypeExternalName] [nvarchar](100) NULL,[Per [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestSessionRolePlayer {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestSessionRolePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestSessionRolePlayerDetails]
        ///	@Date DateTime
        ///AS
        ///BEGIN	
        ///DECLARE @TestSessionRolePlayerDetailsHistory as table([TestSessionRolePlayerDetailId] [int] NOT NULL,[TestSessionId] [int] NOT NULL,[TestSessionName] [nvarchar](200) NULL,[TestDate] [datetime] NULL,[PersonId] [int] NOT NULL,[CustomerNo] [int] NULL,[Status] [nvarchar](100) NULL,
        ///													  [TaskName] [nvarchar](100) NULL,[Language] [nvarchar](100) NULL,[Position] [nvarchar](100) NULL,[ModifiedDate] [date [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestSessionRolePlayerDetails {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestSessionRolePlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestSessions]
        ///		@Date DateTime
        ///AS
        ///BEGIN
        ///	DECLARE @TestSessionsHistory as table([TestSittingId] [int] NOT NULL,[TestSessionId] [int] NOT NULL,[CredentialRequestId] [int] NOT NULL,[TestSessionName] [nvarchar](200) NULL,[TestLocationState] [nvarchar](50) NULL,[TestLocationCountry] [nvarchar](50) NULL,
        ///										  [TestLocationName] [nvarchar](1000) NULL,[VenueName] [nvarchar](200) NULL,[VenueAddress] [nvarchar](510) NULL,[TestDate] [datetime] NULL,[TestStartTime] [ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestSessions {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestSessions_Latest]
        ///AS
        ///BEGIN
        ///	IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = N&apos;TestSessionsLatest&apos;)
        ///		BEGIN
        ///			SELECT * INTO TestSessionsLatest FROM TestSessionsHistory WHERE RowStatus = &apos;Latest&apos;
        ///		END
        ///	ELSE
        ///		BEGIN		
        ///		BEGIN TRANSACTION
        ///		
        ///		--Merge operation Latest
        ///		MERGE TestSessionsHistory AS Target USING(select * from TestSessionsHistory where [RowStatus] = &apos;Latest&apos; ) AS Source ON (Target.[TestSittingId] = Source.[TestSittingId] AND Target.[Te [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestSessions_Latest {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestSessions_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_TestSittingTestMaterial]
        ///		@Date DateTime
        ///AS
        ///BEGIN
        ///
        ///DECLARE @TestSittingTestMaterialHistory as table([TestSittingTestMaterialId] [int] NOT NULL,[ModifiedDate] [datetime] NOT NULL,[TestSittingId] [int] NULL,[TestSessionId] [int] NULL,[TestMaterialId] [int] NULL,[SatDate] [datetime] NULL,[TestLocationName] [nvarchar](1000) NULL,
        ///												 [TestLocationState] [nvarchar](50) NULL,[CredentialRequestId] [int] NULL,[CredentialApplicationId] [int] NULL,[PersonId] [i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_TestSittingTestMaterial {
            get {
                return ResourceManager.GetString("ReportingSnapshot_TestSittingTestMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[ReportingSnapshot_WorkPractice]
        ///		@Date DateTime
        ///AS
        ///BEGIN
        ///DECLARE @WorkPracticeHistory as table([WorkPracticeId] [int] NOT NULL,[PersonID] [int] NOT NULL,[CustomerNumber] [int] NOT NULL,[PractitionerNumber] [nvarchar](50) NOT NULL,[ApplicationID] [int] NOT NULL,[ApplicationStatus] [nvarchar](100) NULL,[CredentialTypeInternalName] [nvarchar](50) NULL,
        ///									  [CredentialTypeExternalName] [nvarchar](50) NULL,[Skill] [nvarchar](200) NULL,[CertificationPeriodID] [int] NULL,[Certif [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportingSnapshot_WorkPractice {
            get {
                return ResourceManager.GetString("ReportingSnapshot_WorkPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW RubricTestComponentResult AS
        ///	SELECT
        ///		rtcr.[RubricTestComponentResultId]
        ///		,rtcr.[TestComponentId]
        ///		,racr.[RubricAssessementCriterionResultId]
        ///		,rtcr.WasAttempted WasAttempted
        ///		,rtcr.Successful Successful
        ///		,rmc.Label RubricCompetencyLabel
        ///		,rmc.Name RubricCompetencyName
        ///		,rmac.Name RubricCriterionName
        ///		,rmac.Label RubricCriterionLabel
        ///		,rmb.Label RubricSelectedBandLabel
        ///		,rmb.Level RubricSelectedBandLevel
        ///		,rtcr.MarkingResultTypeId
        ///	FROM [naati_db]..[tblRubricTestComponen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RubricTestComponentResultView {
            get {
                return ResourceManager.GetString("RubricTestComponentResultView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[TestMaterial] AS
        ///SELECT
        ///	[TestMaterialId]
        ///	,[Title]
        ///	,[LanguageId]
        ///	,[Language]
        ///	,[SkillId]
        ///	,[Skill]
        ///	,[Available]
        ///	,[MaterialRequestId]
        ///	,[TestMaterialTypeId]
        ///	,[TestMaterialType]
        ///	,[TestMaterialDomainId]
        ///	,[TestMaterialDomain]	
        ///FROM [TestMaterialHistory] a
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string TestMaterialView {
            get {
                return ResourceManager.GetString("TestMaterialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[TestResultRubric] AS
        ///SELECT
        ///	[TestResultId]
        ///	,DATEADD(dd,DATEDIFF(dd,0,GETDATE()),0)AS[DateRecorded]
        ///	,[TestSittingId]
        ///	,[TestSessionId]
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[CandidateName]
        ///	,[ResultDueDate]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[Language1]
        ///	,[Language1Code]
        ///	,[Language1Group]
        ///	,[Language2]
        ///	,[Language2Code]
        ///	,[Language2Group]
        ///	,[Skill]
        ///	,[PaidReview]
        ///	,[Supplementary]
        ///	,[OverallResult]
        ///	,[ResultDate]
        ///	,[EligibleForSupplementary]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestResultRubricView {
            get {
                return ResourceManager.GetString("TestResultRubricView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[TestResult] AS
        ///SELECT
        ///    [TestResultId]
        ///    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///    ,[PersonId]
        ///    ,[TestSittingId]
        ///    ,[ResultDueDate]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///    ,[LanguageName1]
        ///    ,[LanguageName2]
        ///    ,[CandidateName]
        ///    ,[NAATINumber]
        ///    ,[NAATINumberDisplay]
        ///    ,[PaidReview]
        ///    ,[TotalMarks]
        ///    ,[PassMark]
        ///    ,[TotalCost]
        ///    ,[GeneralComments]
        ///    ,[OverallResult]
        ///    ,[ResultDate]
        ///	,[Elig [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestResultView {
            get {
                return ResourceManager.GetString("TestResultView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW TestRubricComponent AS
        ///	SELECT
        ///		j.[JobId]
        ///		,tct.[TestComponentId]
        ///		,tr.[TestResultId] 
        ///		,ts.[TestSittingId] 
        ///		,ts.[TestSessionId] 
        ///		,p.[PersonId]
        ///		,e.[NaatiNumber] CustomerNo
        ///		,(
        ///			SELECT TOP 1
        ///				[Title] + &apos; &apos; + [GivenName] + &apos; &apos; + [SurName]
        ///			FROM [naati_db]..[tblPersonName] pn
        ///			LEFT JOIN [naati_db]..[tluTitle] t ON pn.[TitleId] = t.[TitleId]
        ///			WHERE pn.[PersonId] = p.[PersonId]
        ///			ORDER BY pn.[EffectiveDate] DESC
        ///		) CandidateName
        ///		,CAST(CASE WHEN j.[ReviewFromJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestRubricComponentView {
            get {
                return ResourceManager.GetString("TestRubricComponentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter VIEW [dbo].[TestSessionRolePlayerDetails] AS
        ///SELECT
        ///	 [TestSessionRolePlayerDetailId]
        ///	,[TestSessionId]	
        ///	,[TestSessionName]
        ///	,[TestDate]	
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[Status]
        ///	,[TaskName]
        ///    ,[Language]
        ///    ,[Position]
        ///	,[ModifiedDate]	
        ///FROM [TestSessionRolePlayerDetailsHistory] c
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string TestSessionRolePlayerDetailsView {
            get {
                return ResourceManager.GetString("TestSessionRolePlayerDetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[TestSessionRolePlayer] AS
        ///SELECT
        ///	 [TestSessionRolePlayerId]
        ///	,[TestSessionId]	
        ///	,[TestSessionName]
        ///	,[TestLocationState]
        ///	,[TestLocationCountry]
        ///	,[TestLocationName]
        ///	,[TestDate]	
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[Status]
        ///	,[Rehearsed]
        ///	,[Attended]
        ///	,[Rejected]	
        ///	,[ModifiedDate]		
        ///FROM [TestSessionRolePlayerHistory] c
        ///where [RowStatus] = &apos;Latest&apos;.
        /// </summary>
        public static string TestSessionRolePlayerView {
            get {
                return ResourceManager.GetString("TestSessionRolePlayerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[TestSessions] AS
        ///SELECT * FROM TestSessionsLatest
        ///--SELECT
        ///--	[TestSittingId]
        ///--	,[TestSessionId]
        ///--	,[CredentialRequestId]
        ///--	,[TestSessionName]
        ///--	,[TestLocationState]
        ///--	,[TestLocationCountry]
        ///--	,[TestLocationName]
        ///--	,[VenueName]
        ///--	,[VenueAddress]
        ///--	,[TestDate]
        ///--	,[TestStartTime]
        ///--	,[TestArrivalTime]
        ///--	,[TestEndTime]
        ///--	,[ApplicationType]
        ///--	,[CredentialTypeInternalName]
        ///--	,[CredentialTypeExternalName]
        ///--	,[TestSessionCompleted]
        ///--	,[PersonId]
        ///--	,[CustomerN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestSessionsView {
            get {
                return ResourceManager.GetString("TestSessionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[TestSittingTestMaterial] AS
        ///SELECT
        ///	[TestSittingTestMaterialId]
        ///    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///	,[TestSittingId]
        ///	,[TestSessionId]
        ///	,[TestMaterialId]
        ///	,[SatDate]
        ///	,[TestLocationName]
        ///	,[TestLocationState]
        ///	,[CredentialRequestId]
        ///	,[CredentialApplicationId]
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[CandidateName]
        ///	,[Language1]
        ///	,[Language1Code]
        ///	,[Language1Group]
        ///	,[Language2]
        ///	,[Language2Code]
        ///	,[Language2Group]
        ///	,[Skill]
        ///	,[TestMaterialTitle]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestSittingTestMaterialView {
            get {
                return ResourceManager.GetString("TestSittingTestMaterialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[Test] AS
        ///SELECT
        ///    [TestSittingId]
        ///    ,DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS [DateRecorded]
        ///    ,[CredentialRequestId]
        ///    ,[TestResultId]
        ///    ,[CredentialApplicationId]
        ///    ,[PersonId]
        ///    ,[CandidateName]
        ///    ,[LanguageName1]
        ///    ,[LanguageName2]
        ///    ,[Rejected]
        ///    ,[Sat]
        ///    ,[ResultType]
        ///    ,[ThirdExaminerRequired]
        ///    ,[ProcessedDate]
        ///    ,[SatDate]
        ///    ,[ResultChecked]
        ///    ,[Venue]
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[Skill [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestView {
            get {
                return ResourceManager.GetString("TestView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW[dbo].[WorkPractice] AS
        ///SELECT
        ///      [WorkPracticeId]
        ///    , DATEADD(dd, DATEDIFF(dd, 0, GETDATE()), 0) AS[DateRecorded]
        ///    , [PersonId]
        ///    , [CustomerNumber]
        ///    , [PractitionerNumber]
        ///    , [ApplicationID]
        ///	, [ApplicationStatus]
        ///	, [CredentialTypeInternalName]
        ///	, [CredentialTypeExternalName]
        ///	, [Skill]
        ///    , [CertificationPeriodID]
        ///    , [CertificationPeriodStartDate]
        ///    , [CertificationPeriodOriginalEndDate]
        ///    , [CertificationPeriodEndDate]
        ///    , [DateCompleted]
        ///    , [Desc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WorkPractice {
            get {
                return ResourceManager.GetString("WorkPractice", resourceCulture);
            }
        }
    }
}
