//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.Naati.Common.Migrations.Reports._20190130_AddTestSessionRolePlayerTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F1Solutions.Naati.Common.Migrations.Reports._20190130_AddTestSessionRolePlayerTab" +
                            "le.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[ReportingSnapshot_TestSessionRolePlayer]
        ///AS
        ///BEGIN	
        ///
        ///	SELECT 
        ///		CASE WHEN [Source].[TestSessionRolePlayerId] IS NULL THEN [TestSessionRolePlayer].[TestSessionRolePlayerId] ELSE [Source].[TestSessionRolePlayerId] END AS [TestSessionRolePlayerId]
        ///		,CASE WHEN [Source].[TestSessionId] IS NULL THEN [TestSessionRolePlayer].[TestSessionId] ELSE [Source].[TestSessionId] END AS [TestSessionId]		
        ///		,CASE WHEN [Source].[TestSessionName] IS NULL THEN [TestSessionRolePlayer].[TestSessionNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTestSessionRolePlayerProcedure {
            get {
                return ResourceManager.GetString("CreateTestSessionRolePlayerProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[TestSessionRolePlayer] AS
        ///SELECT
        ///	 [TestSessionRolePlayerId]
        ///	,[TestSessionId]	
        ///	,[TestSessionName]
        ///	,[TestLocationState]
        ///	,[TestLocationCountry]
        ///	,[TestLocationName]
        ///	,[TestDate]	
        ///	,[CredentialTypeInternalName]
        ///	,[CredentialTypeExternalName]
        ///	,[PersonId]
        ///	,[CustomerNo]
        ///	,[Status]
        ///	,[Rehearsed]
        ///	,[Attended]
        ///	,[Rejected]	
        ///	,[ModifiedDate]
        ///	,[ObsoletedDate]
        ///	,[DeletedDate]
        ///FROM [TestSessionRolePlayerHistory] c
        ///WHERE c.[ModifiedDate] =
        ///(
        ///    SELECT MAX([ModifiedDate])        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTestSessionRolePlayerView {
            get {
                return ResourceManager.GetString("CreateTestSessionRolePlayerView", resourceCulture);
            }
        }
    }
}
